(function(global, factory) { function extractNS(){ var g = {}; return factory.call(g, global),g.jsnx;} if(typeof define === 'function' && define.amd){ /*AMD*/ define(extractNS); } else if (typeof module !== 'undefined' && module.exports){ /*node*/ module.exports = extractNS(); } else { factory.call(global, global); } }(this, function(window) {var h,ba=this;function ca(){}
function l(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function m(a){return void 0!==a}function da(a){return"array"==l(a)}function n(a){var b=l(a);return"array"==b||"object"==b&&"number"==typeof a.length}function r(a){return"string"==typeof a}function s(a){return"boolean"==typeof a}function ea(a){return"number"==typeof a}function fa(a){return"function"==l(a)}function ga(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var ja="closure_uid_"+(1E9*Math.random()>>>0),ka=0;
function la(a,b,c){return a.call.apply(a.bind,arguments)}function ma(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function na(a,b,c){na=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?la:ma;return na.apply(null,arguments)}
function t(a,b){var c=a.split("."),d=ba;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}function oa(a,b){function c(){}c.prototype=b.prototype;a.Ob=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){var g=Array.prototype.slice.call(arguments,2);return b.prototype[c].apply(a,g)}};function pa(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")}Math.random();var u=Array.prototype,ra=u.indexOf?function(a,b,c){return u.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(r(a))return r(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},v=u.forEach?function(a,b,c){u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},sa=u.filter?function(a,b,c){return u.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=r(a)?
a.split(""):a,k=0;k<d;k++)if(k in g){var p=g[k];b.call(c,p,k,a)&&(e[f++]=p)}return e},x=u.map?function(a,b,c){return u.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=r(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},wa=u.reduce?function(a,b,c,d){d&&(b=na(b,d));return u.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;v(a,function(c,g){e=b.call(d,e,c,g,a)});return e},xa=u.some?function(a,b,c){return u.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?
a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};function ya(a){if(!da(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0}function za(a,b){var c=ra(a,b);0<=c&&u.splice.call(a,c,1)}function Aa(a){return u.concat.apply(u,arguments)}function Ba(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ca(a,b,c,d){u.splice.apply(a,Ea(arguments,1))}function Ea(a,b,c){return 2>=arguments.length?u.slice.call(a,b):u.slice.call(a,b,c)}
function Fa(a,b,c){if(!n(a)||!n(b)||a.length!=b.length)return!1;var d=a.length;c=c||Ga;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return!1;return!0}function Ha(a,b){return a>b?1:a<b?-1:0}function Ga(a,b){return a===b}function Ia(a){for(var b=[],c=0;c<a;c++)b[c]=0;return b}function Ja(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}}
function Ka(a){for(var b=Math.random,c=a.length-1;0<c;c--){var d=Math.floor(b()*(c+1)),e=a[c];a[c]=a[d];a[d]=e}};var y={Jb:function(a){return Math.floor(Math.random()*a)},Pb:function(a,b){return a+Math.random()*(b-a)},clamp:function(a,b,c){return Math.min(Math.max(a,b),c)},sb:function(a,b){var c=a%b;return 0>c*b?c+b:c},Gb:function(a,b,c){return a+c*(b-a)},Ib:function(a,b,c){return Math.abs(a-b)<=(c||1E-6)},Ua:function(a){return y.sb(a,360)},eb:function(a){return a*Math.PI/180},Ab:function(a){return 180*a/Math.PI},Cb:function(a,b){return b*Math.cos(y.eb(a))},Db:function(a,b){return b*Math.sin(y.eb(a))},angle:function(a,
b,c,d){return y.Ua(y.Ab(Math.atan2(d-b,c-a)))},Bb:function(a,b){var c=y.Ua(b)-y.Ua(a);180<c?c-=360:-180>=c&&(c=360+c);return c},Mb:function(a){return 0==a?0:0>a?-1:1},Hb:function(a,b,c,d){c=c||function(a,b){return a==b};d=d||function(b){return a[b]};for(var e=a.length,f=b.length,g=[],k=0;k<e+1;k++)g[k]=[],g[k][0]=0;for(var p=0;p<f+1;p++)g[0][p]=0;for(k=1;k<=e;k++)for(p=1;p<=f;p++)c(a[k-1],b[p-1])?g[k][p]=g[k-1][p-1]+1:g[k][p]=Math.max(g[k-1][p],g[k][p-1]);for(var w=[],k=e,p=f;0<k&&0<p;)c(a[k-1],b[p-
1])?(w.unshift(d(k-1,p-1)),k--,p--):g[k-1][p]>g[k][p-1]?k--:p--;return w},sum:function(a){return wa(arguments,function(a,c){return a+c},0)},lb:function(a){return y.sum.apply(null,arguments)/arguments.length},yb:function(a){var b=arguments.length;if(2>b)return 0;var c=y.lb.apply(null,arguments);return y.sum.apply(null,x(arguments,function(a){return Math.pow(a-c,2)}))/(b-1)},Nb:function(a){return Math.sqrt(y.yb.apply(null,arguments))},Fb:function(a){return isFinite(a)&&0==a%1},Eb:function(a){return isFinite(a)&&
!isNaN(a)},Lb:function(a,b){return Math.floor(a+(b||2E-15))},Kb:function(a,b){return Math.ceil(a-(b||2E-15))}};var z="StopIteration"in ba?ba.StopIteration:Error("StopIteration");function A(){}A.prototype.next=function(){throw z;};A.prototype.oa=function(){return this};function B(a){if(a instanceof A)return a;if("function"==typeof a.oa)return a.oa(!1);if(n(a)){var b=0,c=new A;c.next=function(){for(;;){if(b>=a.length)throw z;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function E(a,b,c){if(n(a))try{v(a,b,c)}catch(d){if(d!==z)throw d;}else{a=B(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==z)throw e;}}}function F(a,b,c){var d=B(a);a=new A;a.next=function(){for(;;){var a=d.next();return b.call(c,a,void 0,d)}};return a}function La(a,b){var c=0;E(a,function(a){c=b.call(void 0,c,a)});return c}
function Ma(a){var b=B(arguments),c=new A,d=null;c.next=function(){for(;;){if(null==d){var a=b.next();d=B(a)}try{return d.next()}catch(c){if(c!==z)throw c;d=null}}};return c}function Na(a){if(n(a))return Ba(a);a=B(a);var b=[];E(a,function(a){b.push(a)});return b}function Qa(a,b){try{return B(a).next()}catch(c){if(c!=z)throw c;return b}};function Ra(){}Ra.ob=function(){return Ra.Za?Ra.Za:Ra.Za=new Ra};Ra.prototype.tb=0;function Sa(a){if(!n(a))return!1;for(var b=0,c=a.length;b<c;b++)if(isNaN(a[b]))return!1;return!0}t("jsnx.utils.misc.is_list_of_ints",Sa);t("jsnx.utils.is_list_of_ints",Sa);function Ta(a){var b=0;return F(a,function(a){return b+=a})}t("jsnx.utils.misc.cumulative_sum",Ta);t("jsnx.utils.cumulative_sum",Ta);function Ua(){return":"+(Ra.ob().tb++).toString(36)}t("jsnx.utils.misc.generate_unique_node",Ua);t("jsnx.utils.generate_unique_node",Ua);function G(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Va(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function H(a){var b=0,c;for(c in a)b++;return b}function Wa(a){for(var b in a)return b}function Xa(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ya(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Za(a){for(var b in a)delete a[b]}function ab(a,b){b in a&&delete a[b]}function J(a,b,c){return b in a?a[b]:c}
function bb(a){var b={},c;for(c in a)b[c]=a[c];return b}var cb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function K(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<cb.length;f++)c=cb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}
function db(a){var b=arguments.length;if(1==b&&da(arguments[0]))return db.apply(null,arguments[0]);if(b%2)throw Error("Uneven number of arguments");for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};function eb(a){var b=arguments;1===arguments.length&&n(arguments[0])&&(b=arguments[0]);this.La="t";for(var c=0,d=b.length;c<d;c++)this[c]=b[c],this.La+=fb(b[c]);this.length=b.length;b=this;Object.isFrozen&&!Object.isFrozen(this)&&(b=Object.create(this),Object.freeze(b));return b}eb.prototype.La="";eb.prototype.length=0;t("jsnx.contrib.Tuple.prototype.length",eb.prototype.length);eb.prototype.toString=function(){return this.La};t("jsnx.contrib.Tuple.prototype.toString",eb.prototype.toString);
function gb(a){return n(arguments[0])?new eb(arguments[0]):new eb(arguments)}t("jsnx.Tuple",gb);t("jsnx.t",gb);function hb(a){this.name="JSNetworkXException";this.message=a}t("jsnx.exception.JSNetworkXException",hb);hb.prototype=Error();hb.prototype.constructor=hb;t("jsnx.JSNetworkXException",hb);function L(a){hb.call(this,a);this.name="JSNetworkXError"}oa(L,hb);t("jsnx.exception.JSNetworkXError",L);t("jsnx.JSNetworkXError",L);function ib(a){hb.call(this,a);this.name="JSNetworkXPointlessConcept"}oa(ib,hb);t("jsnx.exception.JSNetworkXPointlessConcept",ib);t("jsnx.JSNetworkXPointlessConcept",ib);
function jb(a){hb.call(this,a);this.name="JSNetworkXAlgorithmError"}oa(jb,hb);t("jsnx.exception.JSNetworkXAlgorithmError",jb);t("jsnx.JSNetworkXAlgorithmError",jb);function kb(a){jb.call(this,a);this.name="JSNetworkXUnfeasible"}oa(kb,jb);t("jsnx.exception.JSNetworkXUnfeasible",kb);t("jsnx.JSNetworkXUnfeasible",kb);function lb(a){kb.call(this,a);this.name="JSNetworkXNoPath"}oa(lb,kb);t("jsnx.exception.JSNetworkXNoPath",lb);t("jsnx.JSNetworkXNoPath",lb);
function mb(a){jb.call(this,a);this.name="JSNetworkXUnbounded"}oa(mb,jb);t("jsnx.exception.JSNetworkXUnbounded",mb);t("jsnx.JSNetworkXUnbounded",mb);function M(a){this.name="KeyError";this.message=a}M.prototype=Error();M.prototype.constructor=M;t("jsnx.KeyError",M);t("jsnx.version","0.2.0");function fb(a,b){var c=typeof a;return"object"===c||"function"===c?a.hasOwnProperty("__hash__")?a.__hash__:a.toString!==Object.prototype.toString&&a.toString!==Array.prototype.toString?a.toString():b?b(a):"o"+(a[ja]||(a[ja]=++ka)):c.substr(0,1)+a}t("jsnx.contrib.misc.get_hash",fb);function N(a){this.ma={};this.la={};this.ia={};this.O={};if(null!=a)if(nb(a)||n(a))O(a,function(a){this.set.apply(this,a)},this);else if(ga(a))for(var b in a)this.set(isNaN(+b)?b:+b,a[b])}t("jsnx.contrib.Map",N);t("jsnx.Map",N);function ob(a,b){switch(typeof b){case "number":return a.la;case "string":return a.ma;default:return a.ia}}N.prototype.get=function(a,b){var c=ob(this,a);if("undefined"!==typeof c[a])return c[a];if(m(b))return b;throw new M("Map does not contain key "+pb(a));};
N.prototype.get=N.prototype.get;N.prototype.has=function(a){return"undefined"!==typeof ob(this,a)[a]};N.prototype.has=N.prototype.has;N.prototype.set=function(a,b){var c=ob(this,a);c[a]=b;c===this.ia&&(this.O[a]=a);return b};N.prototype.set=N.prototype.set;N.prototype.remove=function(a){var b=ob(this,a);if("undefined"!==typeof b[a])delete b[a],b===this.ia&&delete this.O[a];else throw new M("Map does not contain key "+pb(a));};N.prototype.remove=N.prototype.remove;
N.prototype.items=function(){var a=[],b;for(b in this.la)a.push([+b,this.la[b]]);for(b in this.ma)a.push([b,this.ma[b]]);for(b in this.ia)a.push([this.O[b],this.ia[b]]);return a};N.prototype.items=N.prototype.items;N.prototype.copy=function(a){return qb(this,a)};N.prototype.keys=function(){return x(Ya(this.la),function(a){return+a}).concat(Ya(this.ma)).concat(Xa(this.O))};N.prototype.keys=N.prototype.keys;N.prototype.values=function(){return Xa(this.la).concat(Xa(this.ma)).concat(Xa(this.ia))};
N.prototype.values=N.prototype.values;N.prototype.oa=function(){var a=new A,b=Ya(this.ma),c=Ya(this.la),d=Ya(this.ia),e=0,f=0,g=0;a.next=na(function(){var a;if(e<c.length)return a=c[e++],[+a,this.la[a]];if(f<b.length)return a=b[f++],[a,this.ma[a]];if(g<d.length)return a=d[g++],[this.O[a],this.ia[a]];throw z;},this);return a};N.prototype.count=function(){return H(this.ia)+H(this.la)+H(this.ma)};N.prototype.count=N.prototype.count;N.prototype.clear=function(){Za(this.ma);Za(this.la);Za(this.ia);Za(this.O)};
N.prototype.clear=N.prototype.clear;N.prototype.forEach=function(a,b){E(this,function(c){a.apply(b,c)})};N.prototype.forEach=N.prototype.forEach;function P(a){this.F=new N;null!=a&&(nb(a)||n(a))&&O(a,function(a){this.add(a)},this)}t("jsnx.contrib.Set",P);t("jsnx.Set",P);P.prototype.has=function(a){return this.F.has(a)};P.prototype.has=P.prototype.has;P.prototype.add=function(a){this.F.set(a,!0)};P.prototype.add=P.prototype.add;P.prototype.remove=function(a){try{this.F.remove(a)}catch(b){if(!(b instanceof M))throw b;}};P.prototype.remove=P.prototype.remove;P.prototype.copy=function(a){return qb(this,a)};P.prototype.values=function(){return this.F.keys()};
P.prototype.values=P.prototype.values;P.prototype.oa=function(){return F(this.F,function(a){return a[0]})};P.prototype.ta=function(a){for(var b=new P(this.values()),c=0,d=arguments.length;c<d;c++){var e=arguments[c];e instanceof P&&(e=e.values());for(var f=0,g=e.length;f<g;f++)b.remove(e[f])}return b};P.prototype.difference=P.prototype.ta;
P.prototype.da=function(a){for(var b=new P,c=0,d=arguments.length;c<d;c++){var e=arguments[c];e instanceof P&&(e=e.values());for(var f=0,g=e.length;f<g;f++)this.has(e[f])&&b.add(e[f])}return b};P.prototype.intersection=P.prototype.da;P.prototype.count=function(){return this.F.count()};P.prototype.count=P.prototype.count;P.prototype.clear=function(){this.F.clear()};P.prototype.clear=P.prototype.clear;P.prototype.forEach=function(a,b){E(this,a,b)};P.prototype.forEach=P.prototype.forEach;t("jsnx.filter",function(a,b,c){var d=B(a);a=new A;a.next=function(){for(;;){var a=d.next();if(b.call(c,a,void 0,d))return a}};return a});function ub(a){var b=0;m(b)||(b=null);var c=new N;O(a,function(a){c.set(a,b)});return c}function nb(a){return null!=a&&(a instanceof A||fa(a.oa))}function vb(a){if(a instanceof Q)return a.xa();if(r(a)||n(a))return a.length;if(wb(a))return H(a);throw new TypeError;}
function O(a,b,c,d){s(c)&&(d=c,c=null);if(d){var e=b;b=function(a){e.apply(this,a)}}a instanceof Q?E(xb(a),b,c):nb(a)?E(a,b,c):n(a)||r(a)?v(a,b,c):ga(a)&&O(Ya(a),b,c)}t("jsnx.forEach",O);function R(a,b,c){if(a instanceof Q)return R(xb(a),b,c);if(n(a))return x(a,b,c);if(nb(a))return F(a,b,c);if(ga(a))return Va(a,b,c);throw new TypeError;}t("jsnx.map",R);
function yb(a){var b=arguments,c=b[0];if(n(c))return Ja.apply(null,b);if(nb(c)){var c=new A,d=b.length;c.next=function(){for(var a=[],c=0;c<d;c++)a.push(b[c].next());return a};return c}if(ga(c))return Ja.apply(null,x(b,Ya));throw new TypeError;}function zb(a,b){a=fa(b)?S(R(a,function(){return b.apply(null,arguments)})):S(a);return Math.max.apply(null,a)}
function T(a,b,c){if(0===arguments.length)return B([]);if(1===arguments.length)b=a,a=0,c=1;else if(2===arguments.length)c=1;else if(3===arguments.length&&0===arguments[2])throw"range() step argument must not be zero";var d=new A,e=0>c,f=a,g;d.next=function(){if(e&&f<=b||!e&&f>=b)throw z;g=f;f+=c;return g};return d}
function Ab(a){var b=S(a),c=b.length;if(2>c)return new A;var d=S(T(2));a=new A;a.next=function(){var a=x(d,function(a){return b[a]});this.next=function(){var a=!1,e;for(e=2;e--;)if(d[e]!=e+c-2){a=!0;break}if(!a)throw z;d[e]+=1;for(a=e+1;2>a;a++)d[a]=d[a-1]+1;return x(d,function(a){return b[a]})};return a};return a}
function Bb(a){var b=S(a),c=b.length,d=ea(2)?2:c;if(d>c)return new A;var e=S(T(c)),f=S(T(c,c-d,-1));a=new A;var g=new A,k,p=!0;a.next=function(){this.next=k.next;return x(e.slice(0,d),function(a){return b[a]})};g.next=function(){return p};k=W(g,function(a){if(!a)throw z;p=!1;return T(d-1,-1,-1)},function(a){if(!p)if(f[a]-=1,0===f[a])e.splice.apply(e,[a,e.length].concat(e.slice(a+1).concat([e[a]]))),f[a]=c-a;else{var g=f[a],k=e[a];e[a]=e[e.length-g];e[e.length-g]=k;p=!0;return xb([x(e.slice(0,d),function(a){return b[a]})])}},
function(a){return a});return a}function Cb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)m(a[c])&&"object"===l(a[c])?"object"===l(a[c])&&"object"===l(d)&&Cb(a[c],d[c]):a[c]=X(d[c]);for(var f=0;f<cb.length;f++)c=cb[f],Object.prototype.hasOwnProperty.call(d,c)&&(m(a[c])&&"object"===l(a[c])?"object"===l(a[c])&&"object"===l(d)&&Cb(a[c],d[c]):a[c]=X(d[c]))}}
function S(a){if(a instanceof Q)return S(xb(a));if(n(a))return Ba(a);if(nb(a))return Na(a);if(ga(a))return Ya(a);throw new TypeError;}t("jsnx.toArray",S);function Db(a){var b=new A,c=B(Ya(a));b.next=function(){var b=c.next();return[b,a[b]]};return b}function xb(a){if(a instanceof Q)return xb(a.adj.keys());"object"!==l(a)||n(a)||nb(a)||(a=Ya(a));return B(a)}
function W(a,b){var c=new A,d=Ea(arguments,1);if(0===d.length)return a;try{a=B(a)}catch(e){return c.next=function(){if("Not implemented"===e.message)throw new TypeError;},c}var f=0,g=d.length,k=[a];c.next=function(){do try{var a,b;do a=k[f].next(),m(a)&&(b=d[f](a));while(!m(a));if(nb(b)){if(f===g-1)return b;k.push(b);f+=1}else if(m(b))return b}catch(c){if(c!==z)throw c;if(0<f)k.pop(),f-=1;else throw c;}while(1)};return c}
t("jsnx.sentinelIterator",function(a,b){var c=new A;c.next=function(){return Qa(a,b)};return c});function wb(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==l(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var d in a);return void 0===d||b.call(a,d)}
function X(a,b){b=b||[];var c=l(a);if("object"==c&&(fa(a.copy)||wb(a))||"array"==c){for(var d=0,e=b.length;d<e;d+=2)if(a===b[d])return b[d+1];if(fa(a.copy))return c=a.copy(b),b.push(a,c),c;c="array"==c?[]:{};b.push(a,c);for(var f in a)c[f]=X(a[f],b);return c}return a}function qb(a,b){function c(){}var d={},e,f;c.prototype=a.constructor.prototype;for(e in a)a.hasOwnProperty(e)&&(d[e]=a[e]);d=X(d,b);f=new c;for(e in d)f[e]=d[e];return f}var Fb=function Eb(b,c){return 0===c?b:Eb(c,b%c)};function Gb(a,b){var c=new N;if(null!=b){b=S(b);var d=function(a){return 0<=ra(b,a)};v(b,function(b){c.set(b,sa(a.ja(b),d))})}else O(a,function(b){c.set(b,a.ja(b))});return c}t("jsnx.contrib.convert.to_map_of_lists",Gb);t("jsnx.to_map_of_lists",Gb);function Hb(a,b){var c=Ib(b);c.Q(a.keys());if(c.aa()&&!c.u()){var d=new N;a.forEach(function(a,b){v(b,function(b){d.has(b)||c.q(a,b)});d.set(a,1)})}else a.forEach(function(a,b){v(b,function(b){c.q(a,b)})});return c}
t("jsnx.contrib.convert.from_map_of_lists",Hb);t("jsnx.contrib.convert.to_map_of_maps",function(a,b,c){var d=new N;null!=b?(b=S(b),null!=c?v(b,function(e){var f=d.set(e,new N);a.get(e).forEach(function(a){0<=ra(b,a)&&f.set(a,c)})}):v(b,function(c){var f=d.set(c,new N);a.get(c).forEach(function(a,c){0<=ra(b,a)&&f.set(a,c)})})):null!=c?E(a.ca(),function(a,b){var g=d.set(b,new N);a.forEach(function(a){g.set(a,c)})}):E(a.ca(),function(a,b){var c=d.set(b,new N);a.forEach(function(a,b){c.set(a,b)})});return d});
function Jb(a,b,c){var d=Ib(b),e=new N,f=[];d.Q(a.keys());c?d.u()?d.aa()?a.forEach(function(a,b){if(n(b))throw Error("Value is not a map.");b.forEach(function(b,c){G(c,function(c,e){d.q(a,b,e,c)})})}):a.forEach(function(a,b){if(n(b))throw Error();b.forEach(function(b,c){G(c,function(c){d.q(a,b,c)})})}):d.aa()?a.forEach(function(a,b){if(n(b))throw Error();b.forEach(function(b,c){f[0]=a;f[1]=b;e.has(f)||(G(c,function(c,e){d.q(a,b,e,c)}),f[0]=b,f[1]=a,e.set(f,1))})}):a.forEach(function(a,b){if(n(b))throw Error();
b.forEach(function(b,c){f[0]=a;f[1]=b;e.has(f)||(G(c,function(c){d.q(a,b,c)}),f[0]=b,f[1]=a,e.set(f,1))})}):d.aa()&&!d.u()?a.forEach(function(a,b){if(n(b))throw Error();b.forEach(function(b,c){f[0]=a;f[1]=b;e.has(f)||(d.q(a,b,c),f[0]=b,f[1]=a,e.set(f,1))})}):a.forEach(function(a,b){if(n(b))throw Error();b.forEach(function(b,c){d.q(a,b,c)})});return d}t("jsnx.contrib.convert.from_map_of_maps",Jb);function Kb(a){if("function"==typeof a.ua)return a.ua();if(r(a))return a.split("");if(n(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Xa(a)};function Lb(a,b){this.F={};this.O=[];this.Ka=this.pa=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.Ra(a)}h=Lb.prototype;h.Na=function(){return this.pa};h.ua=function(){Mb(this);for(var a=[],b=0;b<this.O.length;b++)a.push(this.F[this.O[b]]);return a};h.Sa=function(){Mb(this);return this.O.concat()};h.Xa=function(a){return Nb(this.F,a)};h.Oa=function(){return 0==this.pa};
h.clear=function(){this.F={};this.Ka=this.pa=this.O.length=0};h.remove=function(a){return Nb(this.F,a)?(delete this.F[a],this.pa--,this.Ka++,this.O.length>2*this.pa&&Mb(this),!0):!1};function Mb(a){if(a.pa!=a.O.length){for(var b=0,c=0;b<a.O.length;){var d=a.O[b];Nb(a.F,d)&&(a.O[c++]=d);b++}a.O.length=c}if(a.pa!=a.O.length){for(var e={},c=b=0;b<a.O.length;)d=a.O[b],Nb(e,d)||(a.O[c++]=d,e[d]=1),b++;a.O.length=c}}h.get=function(a,b){return Nb(this.F,a)?this.F[a]:b};
h.set=function(a,b){Nb(this.F,a)||(this.pa++,this.O.push(a),this.Ka++);this.F[a]=b};h.Ra=function(a){var b;a instanceof Lb?(b=a.Sa(),a=a.ua()):(b=Ya(a),a=Xa(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};h.Ma=function(){return new Lb(this)};h.oa=function(a){Mb(this);var b=0,c=this.O,d=this.F,e=this.Ka,f=this,g=new A;g.next=function(){for(;;){if(e!=f.Ka)throw Error("The map has changed since the iterator was created");if(b>=c.length)throw z;var g=c[b++];return a?g:d[g]}};return g};
function Nb(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Ob(a){this.F=new Lb;a&&this.Ra(a)}function Pb(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ja]||(a[ja]=++ka)):b.substr(0,1)+a}h=Ob.prototype;h.Na=function(){return this.F.Na()};h.add=function(a){this.F.set(Pb(a),a)};h.Ra=function(a){a=Kb(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};h.remove=function(a){return this.F.remove(Pb(a))};h.clear=function(){this.F.clear()};h.Oa=function(){return this.F.Oa()};h.contains=function(a){return this.F.Xa(Pb(a))};
h.da=function(a){var b=new Ob;a=Kb(a);for(var c=0;c<a.length;c++){var d=a[c];this.contains(d)&&b.add(d)}return b};h.ta=function(a){var b=this.Ma();a=Kb(a);for(var c=a.length,d=0;d<c;d++)b.remove(a[d]);return b};h.ua=function(){return this.F.ua()};h.Ma=function(){return new Ob(this)};h.oa=function(){return this.F.oa(!1)};function Ib(a){if(null!=a)try{a.clear()}catch(b){throw Error("Input graph is not a jsnx graph type");}else a=new Q;return a}
function Qb(a,b,c){var d=null;if(a.hasOwnProperty("adj"))try{return d=Jb(a.adj,b,a.aa()),"graph"in a&&"object"===l(a.graph)&&(d.graph=bb(a.graph)),"node"in a&&a.node instanceof N&&(d.node=new N,a.node.forEach(function(a,b){d.node.set(a,bb(b))})),d}catch(e){throw e;}if(a instanceof N)try{return Jb(a,b,c)}catch(f){try{return Hb(a,b)}catch(g){throw Error("Input is not known type.");}}if("object"===l(a))try{return Rb(a,b,c)}catch(k){try{return Sb(a,b)}catch(p){throw Error("Input is not known type.");
}}if(n(a))try{return Tb(a,b)}catch(w){throw Error("Input is not valid edge list");}return d}t("jsnx.convert.to_networkx_graph",Qb);t("jsnx.to_networkx_graph",Qb);function Ub(a){return a.Aa()}t("jsnx.convert.convert_to_undirected",Ub);t("jsnx.convert_to_undirected",Ub);function Vb(a){return a.ra()}t("jsnx.convert.convert_to_directed",Vb);t("jsnx.convert_to_undirected",Vb);
function Wb(a,b){function c(a){return 0<=ra(b,a)}var d={};null!=b?b=S(b):(b=a,c=function(a){return b.ba(a)});O(b,function(b){d[b]=sa(a.ja(b),c)});return d}t("jsnx.convert.to_dict_of_lists",Wb);t("jsnx.to_dict_of_lists",Wb);
function Sb(a,b){var c=Ib(b);c.Q(F(Db(a),function(a){return isNaN(a[0])?a[0]:+a[0]}));if(c.aa()&&!c.u()){var d={};G(a,function(a,b){b=isNaN(b)?b:+b;v(a,function(a){a in d||c.q(b,a)});d[b]=1})}else{var e=[];G(a,function(a,b){b=isNaN(b)?b:+b;v(a,function(a){e.push([b,a])})});c.D(e)}return c}t("jsnx.convert.from_dict_of_lists",Sb);
t("jsnx.convert.to_dict_of_dicts",function(a,b,c){var d={};null!=b?(b=S(b),null!=c?v(b,function(e){d[e]={};G(a.get(e),function(a,g){0<=ra(b,g)&&(d[e][g]=c)})}):v(b,function(c){d[c]={};G(a.get(c),function(a,g){0<=ra(b,g)&&(d[c][g]=a)})})):null!=c?E(a.ca(),function(a,b){d[b]=Va(a,function(){return c})}):E(a.ca(),function(a,b){d[b]=bb(a)});return d});
function Rb(a,b,c){var d=Ib(b),e,f;d.Q(F(Db(a),function(a){return isNaN(a[0])?a[0]:+a[0]}));c?d.u()?(d.aa()?(e=[],G(a,function(a,b){if(n(a))throw Error();b=isNaN(b)?b:+b;G(a,function(a,c){c=isNaN(c)?c:+c;G(a,function(a,d){e.push([b,c,d,a])})})})):(e=[],G(a,function(a,b){if(n(a))throw Error();b=isNaN(b)?b:+b;G(a,function(a,c){c=isNaN(c)?c:+c;G(a,function(a){e.push([b,c,a])})})})),d.D(e)):d.aa()?(f=new Ob,G(a,function(a,b){if(n(a))throw Error();b=isNaN(b)?b:+b;G(a,function(a,c){c=isNaN(c)?c:+c;f.contains([b,
c].toString())||(e=[],G(a,function(a,d){e.push([b,c,d,a])}),d.D(e),f.add([c,b].toString()))})})):(f=new Ob,G(a,function(a,b){if(n(a))throw Error();b=isNaN(b)?b:+b;G(a,function(a,c){c=isNaN(c)?c:+c;f.contains([b,c].toString())||(e=[],G(a,function(a){e.push([b,c,a])}),d.D(e),f.add([c,b].toString()))})})):d.aa()&&!d.u()?(f=new Ob,G(a,function(a,b){if(n(a))throw Error();b=isNaN(b)?b:+b;G(a,function(a,c){c=isNaN(c)?c:+c;f.contains([b,c].toString())||(d.q(b,c,a),f.add([c,b].toString()))})})):(e=[],G(a,
function(a,b){if(n(a))throw Error();b=isNaN(b)?b:+b;G(a,function(a,c){c=isNaN(c)?c:+c;e.push([b,c,a])})}),d.D(e));return d}t("jsnx.convert.from_dict_of_dicts",Rb);t("jsnx.convert.to_edgelist",function(a,b){return null!=b?a.edges(b,!0):a.edges(null,!0)});function Tb(a,b){var c=Ib(b);c.D(a);return c}t("jsnx.convert.from_edgelist",Tb);function pb(a){var b=[];Xb(new Yb,a,b);return b.join("")}function Yb(){this.Qa=void 0}
function Xb(a,b,c){switch(typeof b){case "string":Zb(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(da(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Xb(a,a.Qa?a.Qa.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),Zb(f,c),
c.push(":"),Xb(a,a.Qa?a.Qa.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var $b={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},ac=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Zb(a,b){b.push('"',a.replace(ac,function(a){if(a in $b)return $b[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return $b[a]=e+b.toString(16)}),'"')};function Q(a,b){if(!(this instanceof Q))return new Q(a,b);this.graph={};this.node=new N;this.adj=new N;null!=a&&Qb(a,this);K(this.graph,b||{});this.edge=this.adj}t("jsnx.classes.Graph",Q);t("jsnx.Graph",Q);Q.__name__="Graph";Q.prototype.pb=null;Q.prototype.graph=Q.prototype.pb;Q.prototype.node=null;Q.prototype.node=Q.prototype.node;Q.prototype.jb=null;Q.prototype.adj=Q.prototype.jb;Q.prototype.edge=null;Q.prototype.edge=Q.prototype.edge;
Q.prototype.name=function(a){if(m(a))this.graph.name=a.toString();else return this.graph.name||""};Q.prototype.name=Q.prototype.name;Q.prototype.toString=function(){return this.name()};Q.prototype.toString=Q.prototype.toString;Q.prototype.get=function(a){try{return this.adj.get(a)}catch(b){if(!(b instanceof M))throw b;throw new M("Graph does not contain node "+a+".");}};Q.prototype.get=Q.prototype.get;
Q.prototype.sa=function(a,b){null!=b||(b={});if("object"!==l(b))throw new L("The attr_dict argument must be an object.");this.adj.has(a)?K(this.node.get(a),b):(this.adj.set(a,new N),this.node.set(a,b))};Q.prototype.add_node=Q.prototype.sa;
Q.prototype.Q=function(a,b){null!=b||(b={});O(a,function(a){if(da(a)&&2===a.length&&ga(a[1])){var d=a[0];a=a[1];if(this.adj.has(d))d=this.node.get(d),K(d,b,a);else{this.adj.set(d,new N);var e=bb(b);K(e,a);this.node.set(d,e)}}else this.adj.has(a)?K(this.node.get(a),b):(this.adj.set(a,new N),this.node.set(a,bb(b)))},this)};Q.prototype.add_nodes_from=Q.prototype.Q;
Q.prototype.za=function(a){var b=this.adj;try{var c=this.adj.get(a).keys();this.node.remove(a);v(c,function(c){b.get(c).remove(a)});b.remove(a)}catch(d){if(!(d instanceof M))throw d;throw new L(pa("The node %s is not in the graph",pb(a)));}};Q.prototype.remove_node=Q.prototype.za;Q.prototype.Ia=function(a){var b=this.adj;O(a,function(a){try{this.node.remove(a),b.get(a).forEach(function(d){b.get(d).remove(a)}),b.remove(a)}catch(d){if(!(d instanceof M))throw d;}},this)};
Q.prototype.remove_nodes_from=Q.prototype.Ia;Q.prototype.ka=function(a){return a?B(this.node):B(this.adj.keys())};Q.prototype.nodes_iter=Q.prototype.ka;Q.prototype.nodes=function(a){return a?this.node.items():this.node.keys()};Q.prototype.nodes=Q.prototype.nodes;Q.prototype.xa=function(){return this.adj.count()};Q.prototype.number_of_nodes=Q.prototype.xa;Q.prototype.order=function(){return this.adj.count()};Q.prototype.order=Q.prototype.order;
Q.prototype.ba=function(a){try{return this.adj.has(a)}catch(b){if(b instanceof TypeError)return!1;throw b;}};Q.prototype.has_node=Q.prototype.ba;Q.prototype.q=function(a,b,c){c=c||{};if("object"!==l(c))throw new L("The attr_dict argument must be an object.");this.adj.has(a)||(this.adj.set(a,new N),this.node.set(a,{}));this.adj.has(b)||(this.adj.set(b,new N),this.node.set(b,{}));var d=this.adj.get(a).get(b,{});K(d,c);this.adj.get(a).set(b,d);this.adj.get(b).set(a,d)};Q.prototype.add_edge=Q.prototype.q;
Q.prototype.D=function(a,b){b=b||{};if("object"!==l(b))throw new L("The attr_dict argument must be an object.");O(a,function(a){var d=vb(a),e;if(3===d)d=a[0],e=a[1],a=a[2];else if(2===d)d=a[0],e=a[1],a={};else throw new L(pa("Edge tuple %s must be a 2-tuple or 3-tuple.",pb(a)));this.adj.has(d)||(this.adj.set(d,new N),this.node.set(d,{}));this.adj.has(e)||(this.adj.set(e,new N),this.node.set(e,{}));var f=this.adj.get(d).get(e,{});K(f,b,a);this.adj.get(d).set(e,f);this.adj.get(e).set(d,f)},this)};
Q.prototype.add_edges_from=Q.prototype.D;Q.prototype.ib=function(a,b,c){c=c||{};r(b)||(c=b,b="weight");this.D(R(a,function(a){var c={};c[b]=a[2];if(!m(c[b]))throw new TypeError("Values must consist of three elements: "+pb(a));return[a[0],a[1],c]}),c)};Q.prototype.add_weighted_edges_from=Q.prototype.ib;
Q.prototype.ha=function(a,b){try{this.adj.get(a).remove(b),fb(a)!==fb(b)&&this.adj.get(b).remove(a)}catch(c){if(c instanceof M)throw new L(pa("The edge %s-%s is not in the graph",pb(a),pb(b)));throw c;}};Q.prototype.remove_edge=Q.prototype.ha;Q.prototype.qa=function(a){O(a,function(a){var c=a[0];a=a[1];this.adj.has(c)&&this.adj.get(c).has(a)&&(this.adj.get(c).remove(a),fb(c)!==fb(a)&&this.adj.get(a).remove(c))},this)};Q.prototype.remove_edges_from=Q.prototype.qa;
Q.prototype.ya=function(a,b){return this.adj.has(a)&&this.adj.get(a).has(b)};Q.prototype.has_edge=Q.prototype.ya;Q.prototype.ja=function(a){try{return this.adj.get(a).keys()}catch(b){if(b instanceof M)throw new L(pa("The node %s is not in the graph.",pb(a)));throw b;}};Q.prototype.neighbors=Q.prototype.ja;Q.prototype.Ga=function(a){try{return B(this.adj.get(a).keys())}catch(b){if(b instanceof M)throw new L(pa("The node %s is not in the graph.",pb(a)));throw b;}};Q.prototype.neighbors_iter=Q.prototype.Ga;
Q.prototype.edges=function(a,b){return Na(this.K(a,b))};Q.prototype.edges=Q.prototype.edges;
Q.prototype.K=function(a,b){s(a)&&(b=a,a=null);var c=new N,d,e;d=null!=a?F(this.J(a),function(a){return[a,this.adj.get(a)]},this):B(this.adj);return b?W(d,function(a){e=a[0];var b=new A,d=B(a[1]);b.next=function(){try{return d.next()}catch(a){throw a===z&&c.set(e,1),a;}};return b},function(a){if(!c.has(a[0]))return[e,a[0],a[1]]}):W(d,function(a){e=a[0];var b=new A,d=B(a[1]);b.next=function(){try{return d.next()}catch(a){throw a===z&&c.set(e,1),a;}};return b},function(a){if(!c.has(a[0]))return[e,a[0]]})};
Q.prototype.edges_iter=Q.prototype.K;Q.prototype.Ba=function(a,b,c){try{return this.adj.get(a).get(b)}catch(d){if(d instanceof M)return c;throw d;}};Q.prototype.get_edge_data=Q.prototype.Ba;Q.prototype.kb=function(){return Na(F(this.ca(),function(a){return a[1].keys()}))};Q.prototype.adjacency_list=Q.prototype.kb;Q.prototype.ca=function(){return B(this.adj)};Q.prototype.adjacency_iter=Q.prototype.ca;Q.prototype.fa=function(a,b){return null!=a&&this.ba(a)?this.ga(a,b).next()[1]:new N(this.ga(a,b))};
Q.prototype.degree=Q.prototype.fa;Q.prototype.ga=function(a,b){var c;c=null!=a?F(this.J(a),function(a){return[a,this.adj.get(a)]},this):B(this.adj);return b?F(c,function(a){var c=a[0],f=a[1],g=0;f.forEach(function(a,c){g+=+J(c,b,1)});g+=+(f.has(c)&&J(f.get(c),b,1));a[1]=g;return a}):F(c,function(a){a[1]=a[1].count()+ +a[1].has(a[0]);return a})};Q.prototype.degree_iter=Q.prototype.ga;Q.prototype.clear=function(){this.name("");this.adj.clear();this.node.clear();Za(this.graph)};Q.prototype.clear=Q.prototype.clear;
Q.prototype.copy=function(){return qb(this)};Q.prototype.copy=Q.prototype.copy;Q.prototype.aa=function(){return!1};Q.prototype.is_multigraph=Q.prototype.aa;Q.prototype.u=function(){return!1};Q.prototype.is_directed=Q.prototype.u;Q.prototype.ra=function(){var a=new Y;a.name(this.name());a.Q(this);a.D(function(){var a;return W(this.ca(),function(c){a=c[0];return B(c[1])},function(c){c[2]=X(c[1]);c[1]=c[0];c[0]=a;return c})}.call(this));a.graph=X(this.graph);a.node=X(this.node);return a};
Q.prototype.to_directed=Q.prototype.ra;Q.prototype.Aa=function(){return qb(this)};Q.prototype.to_undirected=Q.prototype.Aa;Q.prototype.na=function(a){a=this.J(a);var b=new this.constructor,c=b.adj,d=this.adj;E(a,function(a){var b=new N;c.set(a,b);d.get(a).forEach(function(d,k){c.has(d)&&(b.set(d,k),c.get(d).set(a,k))})});O(b,function(a){b.node.set(a,this.node.get(a))},this);b.graph=this.graph;return b};Q.prototype.subgraph=Q.prototype.na;
Q.prototype.ub=function(){return x(sa(this.adj.items(),function(a){return a[1].has(a[0])}),function(a){return a[0]})};Q.prototype.nodes_with_selfloops=Q.prototype.ub;Q.prototype.Ja=function(a){return a?x(sa(this.adj.items(),function(a){return a[1].has(a[0])}),function(a){a[2]=a[1].get(a[0]);a[1]=a[0];return a}):x(sa(this.adj.items(),function(a){return a[1].has(a[0])}),function(a){a[1]=a[0];return a})};Q.prototype.selfloop_edges=Q.prototype.Ja;Q.prototype.vb=function(){return this.Ja().length};
Q.prototype.number_of_selfloops=Q.prototype.vb;Q.prototype.size=function(a){var b=y.sum.apply(null,this.fa(null,a).values())/2;return null!=a?b:Math.floor(b)};Q.prototype.size=Q.prototype.size;Q.prototype.wa=function(a,b){return null!=a?this.adj.get(a).has(b)?1:0:Math.floor(this.size())};Q.prototype.number_of_edges=Q.prototype.wa;Q.prototype.hb=function(a,b){var c=S(a),d=c[0],c=F(Ea(c,1),function(a){return[d,a]});this.D(c,b)};Q.prototype.add_star=Q.prototype.hb;
Q.prototype.gb=function(a,b){var c=S(a),c=Ja(Ea(c,0,c.length-1),Ea(c,1));this.D(c,b)};Q.prototype.add_path=Q.prototype.gb;Q.prototype.fb=function(a,b){var c=S(a),c=Ja(c,Aa(Ea(c,1),[c[0]]));this.D(c,b)};Q.prototype.add_cycle=Q.prototype.fb;
Q.prototype.J=function(a){return null!=a?this.ba(a)?B([a]):function(a,c){var d=new A,e=W(a,function(a){if(c.has(a))return a});d.next=function(){try{return e.next()}catch(a){if(a instanceof TypeError)throw new L("nbunch is not a node or a sequence of nodes");throw a;}};return d}(a,this.adj):B(this.adj.keys())};Q.prototype.nbunch_iter=Q.prototype.J;function Y(a,b){if(!(this instanceof Y))return new Y(a,b);this.graph={};this.node=new N;this.adj=new N;this.pred=new N;this.succ=this.adj;null!=a&&Qb(a,this);K(this.graph,b||{});this.edge=this.adj}t("jsnx.classes.DiGraph",Y);t("jsnx.DiGraph",Y);oa(Y,Q);Y.__name__="DiGraph";Y.prototype.wb=null;Y.prototype.pred=Y.prototype.wb;Y.prototype.zb=null;Y.prototype.succ=Y.prototype.zb;
Y.prototype.sa=function(a,b){null!=b||(b={});if("object"!==l(b))throw new L("The attr_dict argument must be an object.");this.succ.has(a)?K(this.node.get(a),b):(this.succ.set(a,new N),this.pred.set(a,new N),this.node.set(a,b))};Y.prototype.add_node=Y.prototype.sa;
Y.prototype.Q=function(a,b){var c,d,e,f,g;null!=b||(b={});O(xb(a),function(a){c=!this.succ.has(a);da(a)&&2===a.length&&ga(a[1])?(d=a[0],e=a[1],this.succ.has(d)?(g=this.node.get(d),K(g,b,e)):(this.succ.set(d,new N),this.pred.set(d,new N),f=bb(b),K(f,e),this.node.set(d,f))):c?(this.succ.set(a,new N),this.pred.set(a,new N),this.node.set(a,bb(b))):K(this.node.get(a),b)},this)};Y.prototype.add_nodes_from=Y.prototype.Q;
Y.prototype.za=function(a){var b;try{b=this.succ.get(a),this.node.remove(a)}catch(c){if(!(c instanceof M))throw c;throw new L(pa("The node %s is not in the graph",pb(a)));}b.forEach(function(b){this.pred.get(b).remove(a)},this);this.succ.remove(a);this.pred.get(a).forEach(function(b){this.succ.get(b).remove(a)},this);this.pred.remove(a)};Y.prototype.remove_node=Y.prototype.za;
Y.prototype.Ia=function(a){var b;O(a,function(a){this.succ.has(a)&&(b=this.succ.get(a),this.node.remove(a),b.forEach(function(b){this.pred.get(b).remove(a)},this),this.succ.remove(a),this.pred.get(a).forEach(function(b){this.succ.get(b).remove(a)},this),this.pred.remove(a))},this)};Y.prototype.remove_nodes_from=Y.prototype.Ia;
Y.prototype.q=function(a,b,c){c=c||{};if("object"!==l(c))throw new L("The attr_dict argument must be an object.");this.succ.has(a)||(this.succ.set(a,new N),this.pred.set(a,new N),this.node.set(a,{}));this.succ.has(b)||(this.succ.set(b,new N),this.pred.set(b,new N),this.node.set(b,{}));var d=this.adj.get(a).get(b,{});K(d,c);this.succ.get(a).set(b,d);this.pred.get(b).set(a,d)};Y.prototype.add_edge=Y.prototype.q;
Y.prototype.D=function(a,b){b=b||{};if("object"!==l(b))throw new L("The attr_dict argument must be an object.");O(a,function(a){var d=vb(a),e;if(3===d)d=a[0],e=a[1],a=a[2];else if(2===d)d=a[0],e=a[1],a={};else throw new L("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple.");this.succ.has(d)||(this.succ.set(d,new N),this.pred.set(d,new N),this.node.set(d,{}));this.succ.has(e)||(this.succ.set(e,new N),this.pred.set(e,new N),this.node.set(e,{}));var f=this.adj.get(d).get(e,{});K(f,b,a);this.succ.get(d).set(e,
f);this.pred.get(e).set(d,f)},this)};Y.prototype.add_edges_from=Y.prototype.D;Y.prototype.ha=function(a,b){try{this.succ.get(a).remove(b),this.pred.get(b).remove(a)}catch(c){if(c instanceof TypeError)throw new L(pa("The edge %s-%s is not in the graph",pb(a),pb(b)));throw c;}};Y.prototype.remove_edge=Y.prototype.ha;Y.prototype.qa=function(a){O(a,function(a){var c=a[0];a=a[1];try{this.succ.get(c).remove(a),this.pred.get(a).remove(c)}catch(d){}},this)};Y.prototype.remove_edges_from=Y.prototype.qa;
Y.prototype.rb=function(a,b){return this.succ.has(a)&&this.succ.get(a).has(b)};Y.prototype.has_successor=Y.prototype.rb;Y.prototype.qb=function(a,b){return this.pred.has(a)&&this.pred.get(a).has(b)};Y.prototype.has_predecessor=Y.prototype.qb;Y.prototype.Va=function(a){try{return F(this.succ.get(a),function(a){return a[0]})}catch(b){if(!(b instanceof M))throw b;throw new L("The node "+a+" is not in the digraph.");}};Y.prototype.successors_iter=Y.prototype.Va;
Y.prototype.bb=function(a){try{return F(this.pred.get(a),function(a){return a[0]})}catch(b){if(!(b instanceof M))throw b;throw new L("The node "+a+" is not in the digraph.");}};Y.prototype.predecessors_iter=Y.prototype.bb;Y.prototype.cb=function(a){try{return this.succ.get(a).keys()}catch(b){if(!(b instanceof M))throw b;throw new L("The node "+a+" is not in the digraph.");}};Y.prototype.successors=Y.prototype.cb;
Y.prototype.xb=function(a){try{return this.pred.get(a).keys()}catch(b){if(!(b instanceof M))throw b;throw new L("The node "+a+" is not in the digraph.");}};Y.prototype.predecessors=Y.prototype.xb;Y.prototype.ja=Y.prototype.cb;Y.prototype.neighbors=Y.prototype.ja;Y.prototype.Ga=Y.prototype.Va;Y.prototype.neighbors_iter=Y.prototype.Ga;
Y.prototype.K=function(a,b){s(a)&&(b=a,a=null);var c,d;if(null!=a){var e=[];c=R(this.J(a),function(a){e[0]=a;e[1]=this.adj.get(a);return e},this)}else c=this.adj;return b?W(c,function(a){d=a[0];return B(a[1])},function(a){return[d,a[0],a[1]]}):W(c,function(a){d=a[0];return B(a[1])},function(a){return[d,a[0]]})};Y.prototype.edges_iter=Y.prototype.K;Y.prototype.Pa=Y.prototype.K;Y.prototype.out_edges_iter=Y.prototype.Pa;Y.prototype.Ta=Q.prototype.edges;Y.prototype.out_edges=Y.prototype.Ta;
Y.prototype.va=function(a,b){s(a)&&(b=a,a=null);var c,d;if(null!=a){var e=[];c=R(this.J(a),function(a){e[0]=a;e[1]=this.pred.get(a);return e},this)}else c=this.pred;return b?W(c,function(a){d=a[0];return B(a[1])},function(a){a[2]=a[1];a[1]=d;return a}):W(c,function(a){d=a[0];return B(a[1])},function(a){a[1]=d;return a})};Y.prototype.in_edges_iter=Y.prototype.va;Y.prototype.Da=function(a,b){return S(this.va(a,b))};Y.prototype.in_edges=Y.prototype.Da;
Y.prototype.ga=function(a,b){var c;c=null!=a?yb(F(this.J(a),function(a){return[a,this.succ.get(a)]},this),R(this.J(a),function(a){return[a,this.pred.get(a)]},this)):yb(B(this.succ),B(this.pred));return r(b)?R(c,function(a){var c=a[1][1],f=0;a[0][1].forEach(function(a,c){f+=+J(c,b,1)});c.forEach(function(a,c){f+=+J(c,b,1)});return[a[0][0],f]}):F(c,function(a){return[a[0][0],a[0][1].count()+a[1][1].count()]})};Y.prototype.degree_iter=Y.prototype.ga;
Y.prototype.Ca=function(a,b){var c;c=null!=a?R(this.J(a),function(a){return[a,this.pred.get(a)]},this):this.pred;return null!=b?R(c,function(a){var c=0;a[1].forEach(function(a,d){c+=+J(d,b,1)});a[1]=c;return a}):R(c,function(a){a[1]=a[1].count();return a})};Y.prototype.in_degree_iter=Y.prototype.Ca;
Y.prototype.Ha=function(a,b){var c;if(null!=a){var d=[];c=R(this.J(a),function(a){d[0]=a;d[1]=this.succ.get(a);return d},this)}else c=B(this.succ);return null!=b?R(c,function(a){var c=0;a[1].forEach(function(a,d){c+=+J(d,b,1)});return[a[0],c]}):R(c,function(a){return[a[0],a[1].count()]})};Y.prototype.out_degree_iter=Y.prototype.Ha;Y.prototype.Ya=function(a,b){return null!=a&&this.ba(a)?this.Ca(a,b).next()[1]:new N(this.Ca(a,b))};Y.prototype.in_degree=Y.prototype.Ya;
Y.prototype.ab=function(a,b){return null!=a&&this.ba(a)?this.Ha(a,b).next()[1]:new N(this.Ha(a,b))};Y.prototype.out_degree=Y.prototype.ab;Y.prototype.clear=function(){this.succ.clear();this.pred.clear();this.node.clear();Za(this.graph)};Y.prototype.clear=Y.prototype.clear;Y.prototype.aa=function(){return!1};Y.prototype.is_multigraph=Y.prototype.aa;Y.prototype.u=function(){return!0};Y.prototype.is_directed=Y.prototype.u;Y.prototype.ra=function(){return qb(this)};Y.prototype.to_directed=Y.prototype.ra;
Y.prototype.Aa=function(a){var b=new Q;b.name(this.name());b.Q(this);var c=this.pred,d=[];a?b.D(W(this.ca(),function(a){d[0]=a[0];return B(a[1])},function(a){if(c.get(d[0]).has(a[0]))return d[1]=a[0],d[2]=X(a[1]),d})):b.D(W(this.ca(),function(a){d[0]=a[0];return B(a[1])},function(a){d[1]=a[0];d[2]=X(a[1]);return d}));b.graph=X(this.graph);b.node=X(this.node);return b};Y.prototype.to_undirected=Y.prototype.Aa;
Y.prototype.reverse=function(a){(a=!m(a)||a)?(a=new this.constructor(null,{name:"Reverse of ("+this.name()+")"}),a.Q(this),a.D(R(this.K(null,!0),function(a){var c=a[0];a[0]=a[1];a[1]=c;a[2]=X(a[2]);return a})),a.graph=X(this.graph),a.node=X(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};Y.prototype.reverse=Y.prototype.reverse;
Y.prototype.na=function(a){a=this.J(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;O(a,function(a){c.set(a,new N);d.set(a,new N)});c.forEach(function(a,b){e.get(a).forEach(function(e,p){c.has(e)&&(b.set(e,p),d.get(e).set(a,p))})});O(b,function(a){b.node.set(a,this.node.get(a))},this);b.graph=this.graph;return b};Y.prototype.subgraph=Y.prototype.na;function Z(a,b){if(!(this instanceof Z))return new Z(a,b);Q.call(this,a,b)}oa(Z,Q);t("jsnx.classes.MultiGraph",Z);t("jsnx.MultiGraph",Z);Z.__name__="MultiGraph";
Z.prototype.q=function(a,b,c,d){var e,f;null==c||r(c)||ea(c)||(d=c,c=null);d=d||{};if("object"!==l(d))throw new L("The attr_dict argument must be an object.");this.adj.has(a)||(this.adj.set(a,new N),this.node.set(a,{}));this.adj.has(b)||(this.adj.set(b,new N),this.node.set(b,{}));if(this.adj.get(a).has(b)){f=this.adj.get(a).get(b);if(null==c)for(c=H(f);c in f;)c+=1;e=J(f,""+c,{});K(e,d);f[c]=e}else null!=c||(c=0),e={},K(e,d),f=db(c,e),this.adj.get(a).set(b,f),this.adj.get(b).set(a,f)};
Z.prototype.add_edge=Z.prototype.q;Z.prototype.D=function(a,b){b=b||{};if("object"!==l(b))throw new L("The attr_dict argument must be an object.");O(a,function(a){var d=vb(a),e,f=null,g={};if(4===d)d=a[0],e=a[1],f=a[2],g=a[3];else if(3===d)d=a[0],e=a[1],g=a[2];else if(2===d)d=a[0],e=a[1];else throw new L("Edge tuple "+pb(a)+" must be a 2-tuple, 3-tuple or 4-tuple.");a=this.adj.has(d)?this.adj.get(d).get(e,{}):{};if(null==f)for(f=H(a);f in a;)f+=1;a=J(a,f,{});K(a,b,g);this.q(d,e,f,a)},this)};
Z.prototype.add_edges_from=Z.prototype.D;Z.prototype.ha=function(a,b,c){var d;try{d=this.adj.get(a).get(b)}catch(e){if(!(e instanceof M))throw e;throw new L("The edge "+a+"-"+b+" is not in the graph");}if(null!=c){if(!(c in d))throw new L("The edge "+a+"-"+b+" with key "+c+" is not in the graph");ab(d,c)}else ab(d,Wa(d));0===H(d)&&(this.adj.get(a).remove(b),a!==b&&this.adj.get(b).remove(a))};Z.prototype.remove_edge=Z.prototype.ha;
Z.prototype.qa=function(a){O(a,function(a){try{this.ha(a[0],a[1],a[2])}catch(c){if(!(c instanceof L))throw c;}},this)};Z.prototype.remove_edges_from=Z.prototype.qa;Z.prototype.ya=function(a,b,c){try{var d;if(null!=c){var e=this.adj.get(a).get(b);d=c in e}else d=this.adj.get(a).has(b);return d}catch(f){if(!(f instanceof M))throw f;return!1}};Z.prototype.has_edge=Z.prototype.ya;Z.prototype.edges=function(a,b,c){return Na(this.K(a,b,c))};Z.prototype.edges=Z.prototype.edges;
Z.prototype.K=function(a,b,c){s(a)&&(s(b)&&(c=b),b=a,a=null);var d=new N,e,f;if(null!=a){var g=[];a=R(this.J(a),function(a){g[0]=a;g[1]=this.adj.get(a);return g},this)}else a=B(this.adj);return b?W(a,function(a){e=a[0];var b=new A,c=B(a[1]);b.next=function(){try{return c.next()}catch(a){throw a===z&&d.set(e,!0),a;}};return b},function(a){f=a[0];if(!d.has(f))return Db(a[1])},function(a){return c?[e,f,a[0],a[1]]:[e,f,a[1]]}):W(a,function(a){e=a[0];var b=new A,c=B(a[1]);b.next=function(){try{return c.next()}catch(a){throw a===
z&&d.set(e,!0),a;}};return b},function(a){f=a[0];if(!d.has(f))return Db(a[1])},function(a){return c?[e,f,a[0]]:[e,f]})};Z.prototype.edges_iter=Z.prototype.K;Z.prototype.Ba=function(a,b,c,d){m(d)||(d=null);try{return null!=c?J(this.adj.get(a).get(b),""+c,d):this.adj.get(a).get(b)}catch(e){if(!(e instanceof M))throw e;return d}};Z.prototype.get_edge_data=Z.prototype.Ba;
Z.prototype.ga=function(a,b){var c;if(null!=a){var d=[];c=R(this.J(a),function(a){d[0]=a;d[1]=this.adj.get(a);return d},this)}else c=B(this.adj);return null!=b?F(c,function(a){var c=a[0];a=a[1];var d=0;a.forEach(function(a,c){G(c,function(a){d+=J(a,b,1)})});a.has(c)&&G(a.get(c),function(a){d+=J(a,b,1)});return[c,d]}):F(c,function(a){var b=a[0];a=a[1];var c=0;a.forEach(function(a,b){c+=H(b)});return[b,c+ +(a.has(b)&&H(a.get(b)))]})};Z.prototype.degree_iter=Z.prototype.ga;Z.prototype.aa=function(){return!0};
Z.prototype.is_multigraph=Z.prototype.aa;Z.prototype.u=function(){return!1};Z.prototype.is_directed=Z.prototype.u;Z.prototype.ra=function(){var a=new $;a.Q(this);a.D(function(){var a,c;return W(this.ca(),function(c){a=c[0];return B(c[1])},function(a){c=a[0];return Db(a[1])},function(d){return[a,c,d[0],X(d[1])]})}.call(this));a.graph=X(this.graph);a.node=X(this.node);return a};Z.prototype.to_directed=Z.prototype.ra;
Z.prototype.Ja=function(a,b){var c=[];a?b?this.adj.forEach(function(a,b){b.has(a)&&G(b.get(a),function(b,e){c.push([a,a,e,b])})}):this.adj.forEach(function(a,b){b.has(a)&&G(b.get(a),function(b){c.push([a,a,b])})}):b?this.adj.forEach(function(a,b){b.has(a)&&G(b.get(a),function(b,e){c.push([a,a,e])})}):this.adj.forEach(function(a,b){b.has(a)&&G(b.get(a),function(){c.push([a,a])})});return c};Z.prototype.selfloop_edges=Z.prototype.Ja;
Z.prototype.wa=function(a){if(null==a)return this.size();try{return H(this.adj.get(a).get(a))}catch(b){if(!(b instanceof M))throw b;return 0}};Z.prototype.number_of_edges=Z.prototype.wa;Z.prototype.na=function(a){a=this.J(a);var b=new this.constructor,c=b.adj,d=this.adj;E(a,function(a){var b=new N;c.set(a,b);d.get(a).forEach(function(d,k){if(c.has(d)){var p=bb(k);b.set(d,p);c.get(d).set(a,p)}})});this.node.forEach(function(a,c){b.node.set(a,c)});b.graph=this.graph;return b};Z.prototype.subgraph=Z.prototype.na;function $(a,b){if(!(this instanceof $))return new $(a,b);Y.call(this,a,b)}oa($,Y);var bc=$.prototype,cc=Z.prototype,dc;for(dc in cc)cc.hasOwnProperty(dc)&&"constructor"!==dc&&(bc[dc]=cc[dc]);t("jsnx.classes.MultiDiGraph",$);t("jsnx.MultiDiGraph",$);$.__name__="MultiDiGraph";
$.prototype.q=function(a,b,c,d){var e,f;null==c||r(c)||ea(c)||(d=c,c=null);d=d||{};if("object"!==l(d))throw new L("The attr_dict argument must be an object.");this.succ.has(a)||(this.succ.set(a,new N),this.pred.set(a,new N),this.node.set(a,{}));this.succ.has(b)||(this.succ.set(b,new N),this.pred.set(b,new N),this.node.set(b,{}));if(this.succ.get(a).has(b)){f=this.adj.get(a).get(b);if(null==c)for(c=H(f);c in f;)c+=1;e=J(f,c.toString(),{});K(e,d);f[c]=e}else null!=c||(c=0),e={},K(e,d),f=db(c,e),this.succ.get(a).set(b,
f),this.pred.get(b).set(a,f)};$.prototype.add_edge=$.prototype.q;$.prototype.ha=function(a,b,c){var d;try{d=this.adj.get(a).get(b)}catch(e){if(!(e instanceof M))throw e;throw new L("The edge "+a+"-"+b+" is not in the graph");}if(null!=c){if(!(c in d))throw new L("The edge "+a+"-"+b+" with key "+c+" is not in the graph");ab(d,c)}else ab(d,Wa(d));0===H(d)&&(this.succ.get(a).remove(b),this.pred.get(b).remove(a))};$.prototype.remove_edge=$.prototype.ha;
$.prototype.K=function(a,b,c){s(a)&&(s(b)&&(c=b),b=a,a=null);var d,e;if(null!=a){var f=[];a=R(this.J(a),function(a){f[0]=a;f[1]=this.adj.get(a);return f},this)}else a=B(this.adj);return b?W(a,function(a){d=a[0];return B(a[1])},function(a){e=a[0];return Db(a[1])},function(a){return c?[d,e,a[0],a[1]]:[d,e,a[1]]}):W(a,function(a){d=a[0];return B(a[1])},function(a){e=a[0];return Db(a[1])},function(a){return c?[d,e,a[0]]:[d,e]})};$.prototype.edges_iter=$.prototype.K;$.prototype.Pa=$.prototype.K;
$.prototype.out_edges_iter=$.prototype.Pa;$.prototype.Ta=function(a,b,c){return Na(this.Pa(a,b,c))};$.prototype.out_edges=$.prototype.Ta;
$.prototype.va=function(a,b,c){s(a)&&(b=a,a=null);var d,e;if(null!=a){var f=[];a=R(this.J(a),function(a){f[0]=a;f[1]=this.pred.get(a);return f},this)}else a=B(this.pred);return b?W(a,function(a){d=a[0];return B(a[1])},function(a){e=a[0];return Db(a[1])},function(a){return c?[e,d,a[0],a[1]]:[e,d,a[1]]}):W(a,function(a){d=a[0];return B(a[1])},function(a){e=a[0];return Db(a[1])},function(a){return c?[e,d,a[0]]:[e,d]})};$.prototype.in_edges_iter=$.prototype.va;
$.prototype.Da=function(a,b,c){return Na(this.va(a,b,c))};$.prototype.in_edges=$.prototype.Da;
$.prototype.ga=function(a,b){var c;if(null!=a){var d=[],e=[];c=yb(F(this.J(a),function(a){d[0]=a;d[1]=this.succ.get(a);return d},this),F(this.J(a),function(a){e[0]=a;e[1]=this.pred.get(a);return e},this))}else c=yb(B(this.succ),B(this.pred));return null!=b?R(c,function(a){var c=a[0][1],d=0;a[1][1].forEach(function(a,c){G(c,function(a){d+=+J(a,b,1)})});c.forEach(function(a,c){G(c,function(a){d+=+J(a,b,1)})});return[a[0][0],d]}):R(c,function(a){var b=0,c=0;a[1][1].forEach(function(a,c){b+=H(c)});a[0][1].forEach(function(a,
b){c+=H(b)});return[a[0][0],b+c]})};$.prototype.degree_iter=$.prototype.ga;$.prototype.Ca=function(a,b){var c;if(null!=a){var d=[];c=R(this.J(a),function(a){d[0]=a;d[1]=this.pred.get(a);return d},this)}else c=B(this.pred);return null!=b?R(c,function(a){var c=0;a[1].forEach(function(a,d){G(d,function(a){c+=+J(a,b,1)})});return[a[0],c]}):R(c,function(a){var b=0;a[1].forEach(function(a,c){b+=H(c)});return[a[0],b]})};$.prototype.in_degree_iter=$.prototype.Ca;
$.prototype.Ha=function(a,b){var c;if(null!=a){var d=[];c=R(this.J(a),function(a){d[0]=a;d[1]=this.succ.get(a);return d},this)}else c=B(this.succ);return null!=b?R(c,function(a){var c=0;a[1].forEach(function(a,d){G(d,function(a){c+=+J(a,b,1)})});return[a[0],c]}):R(c,function(a){var b=0;a[1].forEach(function(a,c){b+=H(c)});return[a[0],b]})};$.prototype.out_degree_iter=$.prototype.Ha;$.prototype.aa=function(){return!0};$.prototype.is_multigraph=$.prototype.aa;$.prototype.u=function(){return!0};
$.prototype.is_directed=$.prototype.u;$.prototype.ra=function(){return qb(this)};$.prototype.to_directed=$.prototype.ra;
$.prototype.Aa=function(a){var b=new Z;b.name(this.name());b.Q(this);var c,d;a?b.D(W(this.ca(),function(a){c=a[0];return B(a[1])},function(a){d=a[0];return Db(a[1])},na(function(a){if(this.ya(d,c,a[0]))return[c,d,a[0],X(a[1])]},this))):b.D(W(this.ca(),function(a){c=a[0];return B(a[1])},function(a){d=a[0];return Db(a[1])},function(a){return[c,d,a[0],X(a[1])]}));b.graph=X(this.graph);b.node=X(this.node);return b};$.prototype.to_undirected=$.prototype.Aa;
$.prototype.na=function(a){a=this.J(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;E(a,function(a){c.set(a,new N);d.set(a,new N)});c.forEach(function(a,b){e.get(a).forEach(function(e,p){if(c.has(e)){var w=bb(p);b.set(e,w);d.get(e).set(a,w)}})});this.node.forEach(function(a,c){b.node.set(a,c)});b.graph=this.graph;return b};$.prototype.subgraph=$.prototype.na;
$.prototype.reverse=function(a){(a=!m(a)||a)?(a=new this.constructor(null,{name:"Reverse of ("+this.name()+")"}),a.Q(this),a.D(F(this.K(null,!0,!0),function(a){return[a[1],a[0],a[2],X(a[3])]})),a.graph=X(this.graph),a.node=X(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};$.prototype.reverse=$.prototype.reverse;function ec(a){return a.nodes()}t("jsnx.classes.func.nodes",ec);t("jsnx.nodes",ec);function fc(a){return a.ka()}t("jsnx.classes.func.nodes_iter",fc);t("jsnx.nodes_iter",fc);function gc(a,b){return a.edges(b)}t("jsnx.classes.func.edges",gc);t("jsnx.edges",gc);function hc(a,b){return a.K(b)}t("jsnx.classes.func.edges_iter",hc);t("jsnx.edges_iter",hc);t("jsnx.degree",function(a,b,c){return a.fa(b,c)});function ic(a,b){return a.ja(b)}t("jsnx.classes.func.neighbors",ic);t("jsnx.neighbors",ic);
function jc(a){return a.xa()}t("jsnx.classes.func.number_of_nodes",jc);t("jsnx.number_of_nodes",jc);function kc(a){return a.wa()}t("jsnx.classes.func.number_of_edges",kc);t("jsnx.number_of_edges",kc);function lc(a){var b=a.xa(),c=a.wa();return 0===c?0:a.u()?c/(b*(b-1)):2*c/(b*(b-1))}t("jsnx.classes.func.density",lc);t("jsnx.density",lc);function mc(a){a=a.fa().values();var b=Math.max.apply(Math,a)+1,c=Ia(b);v(a,function(a){c[a]+=1});return c}t("jsnx.classes.func.degree_histogram",mc);
t("jsnx.degree_histogram",mc);function nc(a){return a.u()}t("jsnx.classes.func.is_directed",nc);t("jsnx.is_directed",nc);function oc(a){function b(){throw new L("Frozen graph can't be modified");}a.add_node=a.sa=b;a.add_nodes_from=a.Q=b;a.remove_node=a.za=b;a.remove_nodes_from=a.Ia=b;a.add_edge=a.q=b;a.add_edges_from=a.D=b;a.remove_edge=a.ha=b;a.remove_edges_from=a.qa=b;a.clear=a.clear=b;a.frozen=a.nb=!0;return a}t("jsnx.classes.func.freeze",oc);t("jsnx.freeze",oc);function pc(a){return!!a.nb}
t("jsnx.classes.func.is_frozen",pc);t("jsnx.is_frozen",pc);function qc(a,b){return a.na(b)}t("jsnx.classes.func.subgraph",qc);t("jsnx.subgraph",qc);function rc(a,b){m(b)||(b=!0);var c=new a.constructor;b&&c.Q(a);return c}t("jsnx.classes.func.create_empty_copy",rc);t("jsnx.create_empty_copy",rc);
function sc(a,b){var c="";if(null!=b){if(!a.ba(b))throw new L("node "+b+" not in graph");c=c+("Node "+b+" has the following properties:\n")+("Degree: "+a.fa(b)+"\n");c+="Neighbors: "+a.ja(b).join(" ")}else{var c=c+("Name: "+a.name()+"\n"),c=c+("Type: "+a.constructor.__name__+"\n"),c=c+("Number of nodes: "+a.xa()+"\n"),c=c+("Number of edges: "+a.wa()+"\n"),d=a.xa();if(0<d)if(a.u())c+="Average in degree: "+(y.sum.apply(null,a.Ya().values())/d).toFixed(4)+"\n",c+="Average out degree: "+(y.sum.apply(null,
a.ab().values())/d).toFixed(4);else var e=y.sum.apply(null,a.fa().values()),c=c+("Average degree: "+(e/d).toFixed(4))}return c}t("jsnx.classes.func.info",sc);t("jsnx.info",sc);function tc(a,b,c){G(c,function(c,e){a.node.get(e)[b]=c})}t("jsnx.classes.func.set_node_attributes",tc);t("jsnx.set_node_attributes",tc);function uc(a,b){var c=new N;a.node.forEach(function(a,e){b in e&&c.set(a,e[b])});return c}t("jsnx.classes.func.get_node_attributes",uc);t("jsnx.get_node_attributes",uc);
function vc(a,b,c){c.forEach(function(c,e){a.get(c[0]).get(c[1])[b]=e})}t("jsnx.classes.func.set_edge_attributes",vc);t("jsnx.set_edge_attributes",vc);function wc(a,b){var c=new N;G(a.edges(null,!0),function(a){if(b in a[2]){var e=a[2][b];a.length=2;c.set(a,e)}});return c}t("jsnx.classes.func.get_edge_attributes",wc);t("jsnx.get_edge_attributes",wc);function xc(a,b){if(a.u())throw new L("triangles() is not defined for directed graphs.");if(null!=b&&a.ba(b))return Math.floor(yc(a,b).next()[2]/2);var c=new N;E(yc(a,b),function(a){c.set(a[0],Math.floor(a[2]/2))});return c}t("jsnx.algorithms.cluster.triangles",xc);t("jsnx.triangles",xc);
function yc(a,b){if(a.aa())throw new L("Not defined for multigraphs.");var c;c=null!=b?W(a.J(b),function(b){return[b,a.get(b)]}):B(a.adj);return F(c,function(b){var c=new P(b[1].keys()),f=0;c.remove(b[0]);E(c,function(b){var d=new P(a.get(b).keys());d.remove(b);f+=c.da(d).count()});return[b[0],c.count(),f]})}
function zc(a,b,c){if(a.aa())throw new L("Not defined for multigraphs.");r(c)||(c="weight");var d;d=0===a.wa()?1:zb(a.edges(!0),function(a){return J(a[2],c,1)});b=null!=b?W(a.J(b),function(b){return[b,a.get(b)]}):B(a.adj);return F(b,function(b){var f=b[0],g=new P(b[1].keys());g.remove(f);var k=0,p=new P;E(g,function(b){var e=J(a.get(f).get(b),c,1)/d;p.add(b);var C=(new P(a.get(b).keys())).ta(p);E(g.da(C),function(g){var p=J(a.get(b).get(g),c,1)/d;g=J(a.get(f).get(g),c,1)/d;k+=Math.pow(e*p*g,1/3)})});
return[f,g.count(),2*k]})}function Ac(a,b,c,d){2===arguments.length?r(b)?(c=b,b=null):s(b)&&(d=b,b=null):3===arguments.length&&s(c)&&(d=c,c=null);null!=d||(d=!0);var e=Bc(a,b,c).values();d||(e=sa(e,function(a){return 0<a}));return y.sum.apply(y,e)/e.length}t("jsnx.algorithms.cluster.average_clustering",Ac);t("jsnx.average_clustering",Ac);
function Bc(a,b,c){if(a.u())throw new L("Clustering algorithms are not defined for directed graphs.");c=null!=c?zc(a,b,c):yc(a,b);var d=new N;E(c,function(a){d.set(a[0],0===a[2]?0:a[2]/(a[1]*(a[1]-1)))});return null!=b&&a.ba(b)?d.values()[0]:d}t("jsnx.algorithms.cluster.clustering",Bc);t("jsnx.clustering",Bc);function Cc(a){var b=0,c=0;E(yc(a),function(a){c+=a[1]*(a[1]-1);b+=a[2]});return 0===b?0:b/c}t("jsnx.algorithms.cluster.transitivity",Cc);t("jsnx.transitivity",Cc);
function Dc(a,b){var c=null!=b?a.J(b):xb(a),d=new N;E(c,function(b){d.set(b,0);var c=0;E(Ab(a.get(b).keys()),function(g){var k=g[0];g=g[1];var p=(new P(a.get(k).keys())).da(a.get(g).keys());p.remove(b);p=p.count();d.set(b,d.get(b)+p);var w=p+1;a.get(k).has(g)&&(w+=1);c+=(a.get(k).count()-w)*(a.get(g).count()-w)+p});0<c&&d.set(b,d.get(b)/c)});return null!=b&&a.ba(b)?d.values()[0]:d}t("jsnx.algorithms.cluster.square_clustering",Dc);t("jsnx.square_clustering",Dc);function Ec(a){var b=-1,c=new N,d=new P;E(a.ca(),function(a){var e=new P(a[1].keys());e.remove(a[0]);var f=e.count();f>b?(c.set(a[0],e),d=e,b=f):c.set(a[0],e)});var e=new P(c.keys()),f=e.ta(d),g=new P,k=[],p=[];a=new A;a.next=function(){if(0===f.count()&&0===k.length)throw z;var a,q;if(0<f.count())a=B(f).next(),f.remove(a);else{var C=k.pop();e=C[0];g=C[1];f=C[2];p.pop();return this.next()}p.push(a);e.remove(a);g.add(a);var U=c.get(a),C=e.da(U),U=g.da(U);if(0===C.count()&&(0===U.count()&&(q=Ba(p)),
p.pop(),q))return q;if(0===U.count()&&1===C.count())return q=Aa(p,C.values()),p.pop(),q;var ha=C.count(),D=-1,aa,V;for(q=B(U);null!==(a=Qa(q,null))&&!(a=C.da(c.get(a)),V=a.count(),V>D&&(aa=a,D=V,D===ha)););if(D===ha)return p.pop(),this.next();b=-1;for(q=B(C);null!==(a=Qa(q,null))&&!(a=C.da(c.get(a)),V=a.count(),V>b&&(d=a,b=V,b===ha-1)););D>b&&(d=aa);k.push([e,g,f]);e=C;g=U;f=e.ta(d);return this.next()};return a}t("jsnx.algorithms.clique.find_cliques",Ec);t("jsnx.find_cliques",Ec);
function Fc(a){var b=new N;E(a.ca(),function(a){var c=new P(a[1].keys());c.remove(a[0]);b.set(a[0],c)});if(0===b.count())return[];a=new P(b.keys());var c=new P,d=[];Gc(b,a,c,[],d);return d}t("jsnx.algorithms.clique.find_cliques_recursive",Fc);t("jsnx.find_cliques_recursive",Fc);
function Gc(a,b,c,d,e){var f=-1,g=b.count(),k,p,w,q;for(p=B(c);null!==(w=Qa(p,null));)if(w=b.da(a.get(w)),q=w.count(),q>f&&(k=w,f=q,q===g))return;E(b,function(c){c=b.da(a.get(c));var d=c.count();d>f&&(k=c,f=d)});g=b.ta(k);E(g,function(f){b.remove(f);d.push(f);var g=a.get(f);f=b.da(g);g=c.da(g);0===f.count()&&0===g.count()?e.push(Ba(d)):0===g.count()&&1===f.count()?e.push(Aa(d,f.values())):Gc(a,f,g,d,e);c.add(d.pop())})}
function Hc(a,b){null!=b||(b=Ec(a));var c=0;O(b,function(a){c=a.length>c?a.length:c});return c}t("jsnx.algorithms.clique.graph_clique_number",Hc);t("jsnx.graph_clique_number",Hc);function Ic(a,b){null!=b||(b=Ec(a));return S(b).length}t("jsnx.algorithms.clique.graph_number_of_cliques",Ic);t("jsnx.graph_number_of_cliques",Ic);
function Jc(a,b,c){c=null!=c?Na(c):Na(Ec(a));null!=b||(b=a.nodes());var d;if(da(b))d=new N,v(b,function(a){d.set(a,sa(c,function(b){return(new P(b)).has(a)}).length)});else{var e=b;d=sa(c,function(a){return(new P(a)).has(e)}).length}return d}t("jsnx.algorithms.clique.number_of_cliques",Jc);t("jsnx.number_of_cliques",Jc);function Kc(a,b){if(a.order()!=b.order())return!1;var c=a.fa(),d=xc(a),e=Jc(a),f=[];c.forEach(function(a){f.push([c.get(a),d.get(a),e.get(a)])});f.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});var g=b.fa(),k=xc(b),p=Jc(b),w=[];g.forEach(function(a){w.push([g.get(a),k.get(a),p.get(a)])});w.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});return Fa(f,w,function(a,b){return Fa(a,b)})?!0:!1}
t("jsnx.algorithms.isomorphism.could_be_isomorphic",Kc);t("jsnx.could_be_isomorphic",Kc);function Lc(a,b){if(a.order()!=b.order())return!1;var c=a.fa(),d=xc(a),e=[];c.forEach(function(a){e.push([c.get(a),d.get(a)])});e.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});var f=b.fa(),g=xc(b),k=[];f.forEach(function(a){k.push([f.get(a),g.get(a)])});k.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});return Fa(e,k,function(a,b){return Fa(a,b)})?!0:!1}
t("jsnx.algorithms.isomorphism.fast_could_be_isomorphic",Lc);t("jsnx.fast_could_be_isomorphic",Lc);function Mc(a,b){if(a.order()!=b.order())return!1;var c=a.fa().values();c.sort();var d=b.fa().values();d.sort();return Fa(c,d)?!0:!1}t("jsnx.algorithms.isomorphism.faster_could_be_isomorphic",Mc);t("jsnx.faster_could_be_isomorphic",Mc);function Nc(a,b){if("eg"===b)return Oc(a);if(null!=b&&"hh"!==b)throw new hb("`opt_method` must be 'eg' or 'hh'");return Pc(a)}t("jsnx.algorithms.graphical.is_valid_degree_sequence",Nc);t("jsnx.is_valid_degree_sequence",Nc);
function Pc(a){if(0===a.length)return!0;if(!Sa(a)||0>Math.min.apply(null,a)||0!==y.sum.apply(null,a)%2)return!1;for(a=Ba(a);0<a.length;){u.sort.call(a,Ha);if(0>a[0])break;var b=a.pop();if(0===b)return!0;if(b>a.length)break;for(var c=a.length-1,b=a.length-(b+1);c>b;c--)a[c]-=1}return!1}t("jsnx.algorithms.graphical.is_valid_degree_sequence_havel_hakimi",Pc);t("jsnx.is_valid_degree_sequence_havel_hakimi",Pc);
function Oc(a){if(0===a.length)return!0;if(!Sa(a)||0>Math.min.apply(null,a)||0!==y.sum.apply(null,a)%2)return!1;var b=a.length,c=Ba(a).sort(function(a,b){return b-a}),d=[],e;e=1;for(a=c.length;e<a;e++)c[e]<c[e-1]&&d.push(e);var f,g;e=0;for(a=d.length;e<a;e++)if(f=y.sum.apply(null,c.slice(0,d[e])),g=d[e]*(d[e]-1)+y.sum.apply(null,Na(F(T(d[e],b),function(a){return Math.min(d[e],c[a])}))),f>g)return!1;return!0}t("jsnx.algorithms.graphical.is_valid_degree_sequence_erdos_gallai",Oc);
t("jsnx.is_valid_degree_sequence_erdos_gallai",Oc);function Qc(a){try{return Rc(a),!0}catch(b){if(b instanceof kb)return!1;throw b;}}t("jsnx.algorithms.dag.is_directed_acyclic_graph",Qc);t("jsnx.is_directed_acyclic_graph",Qc);
function Rc(a,b){if(!a.u())throw new L("Topological sort not defined on undirected graphs.");var c=new P,d=[],e=new P;null!=b||(b=a.ka());O(b,function(b){if(!e.has(b))for(b=[b];0<b.length;){var g=b[b.length-1];if(e.has(g))b.pop();else{c.add(g);var k=[];a.get(g).forEach(function(a){if(!e.has(a)){if(c.has(a))throw new kb("Graph contains a cycle");k.push(a)}});0<k.length?b.push.apply(b,k):(e.add(g),Ca(d,void 0,0,g))}}});return d}t("jsnx.algorithms.dag.topological_sort",Rc);
t("jsnx.topological_sort",Rc);function Sc(a,b){function c(a,b,d,e){b.add(e);a.get(e).forEach(function(e){if(!b.has(e)){if(!c(a,b,d,e))return!1}else if(b.has(e)&&!(0<=ra(d,e)))throw new kb("Graph contains a cycle");});Ca(d,void 0,0,e);return!0}if(!a.u())throw new L("Topological sort not defined on undirected graphs.");var d=new P,e=[];null!=b||(b=a.ka());O(b,function(b){if(!(0<=ra(e,b)||c(a,d,e,b)))throw new kb("Graph contains a cycle");});return e}
t("jsnx.algorithms.dag.topological_sort_recursive",Sc);t("jsnx.topological_sort_recursive",Sc);var Uc=function Tc(b){if(!b.u())throw new L("is_aperiodic not defined for undirected graphs.");var c=b.ka().next(),d=new N;d.set(c,0);for(var c=[c],e=0,f=1;0<c.length;){var g=[];v(c,function(c){b.get(c).forEach(function(b){d.has(b)?e=Fb(e,d.get(c)-d.get(b)+1):(g.push(b),d.set(b,f))})});c=g;f+=1}return d.count()===vb(b)?1===e:1===e&&Tc(b.na((new P(b.nodes())).ta(d.keys())))};
t("jsnx.algorithms.dag.is_aperiodic",Uc);t("jsnx.is_aperiodic",Uc);function Vc(a,b){this.$a=a;this.Wa=b}Vc.prototype.getKey=function(){return this.$a};Vc.prototype.Ma=function(){return new Vc(this.$a,this.Wa)};function Wc(a){this.ea=[];if(a)a:{var b,c;if(a instanceof Wc){if(b=a.Sa(),c=a.ua(),0>=a.Na()){a=this.ea;for(var d=0;d<b.length;d++)a.push(new Vc(b[d],c[d]));break a}}else b=Ya(a),c=Xa(a);for(d=0;d<b.length;d++)this.insert(b[d],c[d])}}h=Wc.prototype;h.insert=function(a,b){var c=this.ea;c.push(new Vc(a,b));for(var c=c.length-1,d=this.ea,e=d[c];0<c;){var f=c-1>>1;if(d[f].getKey()>e.getKey())d[c]=d[f],c=f;else break}d[c]=e};
h.remove=function(){var a=this.ea,b=a.length,c=a[0];if(!(0>=b)){if(1==b)ya(a);else{a[0]=a.pop();for(var a=0,b=this.ea,d=b.length,e=b[a];a<d>>1;){var f=2*a+1,g=2*a+2,f=g<d&&b[g].getKey()<b[f].getKey()?g:f;if(b[f].getKey()>e.getKey())break;b[a]=b[f];a=f}b[a]=e}return c.Wa}};h.ua=function(){for(var a=this.ea,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].Wa);return b};h.Sa=function(){for(var a=this.ea,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getKey());return b};
h.Xa=function(a){return xa(this.ea,function(b){return b.getKey()==a})};h.Ma=function(){return new Wc(this)};h.Na=function(){return this.ea.length};h.Oa=function(){return 0==this.ea.length};h.clear=function(){ya(this.ea)};function Xc(){Wc.call(this)}oa(Xc,Wc);function Yc(a,b){a.insert(0,b)};function Zc(a,b){null!=b||(b={});if("object"!==l(b))throw new L("The arg_dict argument must be an object.");var c=ub(a),d=a.nodes();"k"in b&&(Ka(d),d=d.slice(0,b.k));O(d.sort(),function(d){var f=[],f=null===J(b,"weight",null)?$c(a,d):ad(a,d,b.weight),g=f[0],k=f[1],f=f[2];c=J(b,"endpoints",!1)?bd(c,g,k,f,d):cd(c,g,k,f,d)});return c=dd(c,vb(a),J(b,"normalized",!0),a.u(),J(b,"k",null))}t("jsnx.algorithms.centrality.betweenness.betweenness_centrality",Zc);t("jsnx.betweenness_centrality",Zc);
function ed(a,b){null!=b||(b={});if("object"!==l(b))throw new L("The arg_dict argument must be an object.");var c=ub(a);E(a.K(),function(a){c.set(a,0)});var d=a.nodes();O(d.sort(),function(d){var f=[],f=null===J(b,"weight",null)?$c(a,d):ad(a,d,b.weight);c=fd(c,f[0],f[1],f[2],d)});O(d,function(a){c.remove(a)});return c=gd(c,vb(a),J(b,"normalized",!0),a.u())}t("jsnx.algorithms.centrality.betweenness.edge_betweenness_centrality",ed);t("jsnx.edge_betweenness_centrality",ed);
function $c(a,b){var c=[],d=new N;E(a.ka(),function(a){d.set(a,[])});var e=ub(a),f=new N;e.set(b,1);f.set(b,0);for(var g=[b];0<g.length;){var k=g.shift();c.push(k);var p=f.get(k),w=e.get(k);v(a.ja(k),function(a){f.has(a)||(g.push(a),f.set(a,p+1));f.get(a)===p+1&&(e.set(a,e.get(a)+w),d.get(a).push(k))})}return[c,d,e]}
function ad(a,b,c){var d=[],e=new N;O(a.nodes(),function(a){e.set(a,[])});var f=ub(a),g=new N;f.set(b,1);var k=new N;k.set(b,0);var p=new Xc;for(Yc(p,[b,b]);!p.Oa();){var w=p.ea[0]&&p.ea[0].getKey();b=p.remove();var q=b[0],C=b[1];g.has(C)||(f.set(C,f.get(C)+f.get(q)),d.push(C),g.set(C,w),E(a.K(C,!0),function(a){var b=a[1];a=w+J(a[2],c,1);g.has(b)||k.has(b)&&!(a<k.get(b))?a===k.get(b)&&(f.set(b,f.get(b)+f.get(C)),e.get(b).push(C)):(k.set(b,a),p.insert(a,[C,b]),f.set(b,0),e.set(b,[C]))}))}return[d,
e,f]}function cd(a,b,c,d,e){for(var f=ub(b);0<b.length;){var g=b.pop(),k=(1+f.get(g))/d.get(g);v(c.get(g),function(a){f.set(a,f.get(a)+d.get(a)*k)});(g!==e||ga(g)&&g.toString()!==e.toString())&&a.set(g,a.get(g)+f.get(g))}return a}function bd(a,b,c,d,e){a.set(e,a.get(e)+b.length-1);for(var f=ub(b);0<b.length;){var g=b.pop(),k=(1+f.get(g))/d.get(g);v(c.get(g),function(a){f.set(a,f.get(a)+d.get(a)*k)});(g!==e||ga(g)&&g.toString()!==e.toString())&&a.set(g,a.get(g)+f.get(g)+1)}return a}
function fd(a,b,c,d,e){for(var f=ub(b);0<b.length;){var g=b.pop(),k=(1+f.get(g))/d.get(g);v(c.get(g),function(b){var c=d.get(b)*k,e=[b,g];a.has(e)||(e=[g,b]);a.set(e,a.get(e)+c);f.set(b,f.get(b)+c)});(g!==e||ga(g)&&g.toString()!==e.toString())&&a.set(g,a.get(g)+f.get(g))}return a}function dd(a,b,c,d,e){var f;s(c)&&c?2<b&&(f=1/((b-1)*(b-2))):s(d)&&!d&&(f=0.5);m(f)&&(null!=e&&(f=f*b/e),a.forEach(function(b,c){a.set(b,c*f)}));return a}
function gd(a,b,c,d){var e;s(c)&&c?1<b&&(e=1/(b*(b-1))):s(d)&&!d&&(e=0.5);m(e)&&a.forEach(function(b,c){a.set(b,c*e)});return a};function kd(a,b,c){var d=new N,e=0,f=new N;for(f.set(b,1);0<f.count();){b=f;f=new N;b.forEach(function(b){d.has(b)||(d.set(b,e),a.get(b).forEach(function(a){f.set(a,1)}))});if(ea(c)&&c<=e)break;e+=1}return d}t("jsnx.algorithms.shortest_paths.unweighted.single_source_shortest_path_length",kd);t("jsnx.single_source_shortest_path_length",kd);function ld(a,b){var c=new N;O(a,function(d){c.set(d,kd(a,d,b))});return c}t("jsnx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path_length",ld);
t("jsnx.all_pairs_shortest_path_length",ld);function md(a,b,c){c=nd(a,b,c);a=c[0];b=c[1];c=c[2];for(var d=[];null!=c;)d.push(c),c=b.get(c);for(c=a.get(d[0]);null!=c;)d.unshift(c),c=a.get(c);return d}t("jsnx.algorithms.shortest_paths.unweighted.bidirectional_shortest_path",md);t("jsnx.bidirectional_shortest_path",md);
function nd(a,b,c){if(!m(b)||!m(c))throw new hb("Bidirectional shortest path called without source or target");var d=new N,e=new N;if(c===b)return d.set(c,null),e.set(b,null),[d,e,b];var f,g;a.u()?(f=a.bb,g=a.Va):g=f=a.Ga;d.set(b,null);e.set(c,null);for(var k=[b],p=[c],w,q;0<k.length&&0<p.length&&!q;)k.length<=p.length?(w=k,k=[],v(w,function(b){q||E(g.call(a,b),function(a){q||(d.has(a)||(k.push(a),d.set(a,b)),e.has(a)&&(q=[d,e,a]))})})):(w=p,p=[],v(w,function(b){q||E(f.call(a,b),function(a){q||(e.has(a)||
(e.set(a,b),p.push(a)),d.has(a)&&(q=[d,e,a]))})}));if(q)return q;throw new lb("No path between "+b+" and "+c+".");}function od(a,b,c){var d=0,e=new N([[b,1]]),f=new N([[b,[b]]]);if(0===c)return f;for(;0<e.count()&&!(b=e,e=new N,b.forEach(function(b){a.get(b).forEach(function(a){f.has(a)||(f.set(a,f.get(b).concat([a])),e.set(a,1))})}),d+=1,m(c)&&c<=d););return f}t("jsnx.algorithms.shortest_paths.unweighted.single_source_shortest_path",od);t("jsnx.single_source_shortest_path",od);
function pd(a,b){var c=new N;O(a,function(d){c.set(d,od(a,d,b))});return c}t("jsnx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path",pd);t("jsnx.all_pairs_shortest_path",pd);
function qd(a,b,c,d,e){for(var f=0,g=[b],k=new N([[b,f]]),p=new N([[b,[]]]);0<g.length&&!(f+=1,b=g,g=[],v(b,function(b){a.get(b).forEach(function(a){k.has(a)?k.get(a)===f&&p.get(a).push(b):(p.set(a,[b]),k.set(a,f),g.push(a))})}),null!=d&&d<=f););return null!=c?e?p.has(c)?[p.get(c),k.get(c)]:[[],-1]:p.has(c)?p.get(c):[]:e?[p,k]:p}t("jsnx.algorithms.shortest_paths.unweighted.predecessor",qd);t("jsnx.predecessor",qd);var rd,sd=null,td="add_node add_nodes_from add_edge add_edges_from remove_node remove_nodes_from remove_edge remove_edges_from clear".split(" ");
t("jsnx.draw",function(a,b,c){function d(){ta.T.attr("transform",function(a){return["translate(",a.x,",",a.y,")scale(",I,")"].join("")});hd()}s(b)&&(c=b,b=null);b=b||sd||{};var e=b.d3||window.d3,f={};Cb(f,ud,b);sd=b;if(!e)throw Error("D3 requried for draw()");if(null==f.element&&null==rd)throw Error("Output element required for draw()");rd=J(f,"element",rd);e.select(rd).select("svg.jsnx").remove();var g=e.select(rd),k=g.append("svg").classed("jsnx",!0).attr("pointer-events","all"),p=k.append("g");
b=p.append("g").classed("edges",!0).selectAll("g.edge");var w=p.append("g").classed("nodes",!0).selectAll("g.node"),q=e.layout.force(),C=f.width||parseInt(g.style("width"),10),U=f.height||parseInt(g.style("height"),10),ha=f.layout_attr,g=f.nodelist||null,D,aa,V,id=a.u(),ua=f.weighted,ta={T:w,V:b};if(f.with_labels){var Da=f.labels;D="object"===l(Da)?function(a){return J(Da,a.node,"")}:fa(Da)?Da:r(Da)?function(a){return a.data[Da]}:function(a){return a.node}}f.labels=D;if(ua){var Oa=f.weights;V="object"===
l(Oa)?function(a){return J(Oa,a.node,1)}:fa(Oa)?Oa:r(Oa)?function(a){return J(a.data,Oa,1)}:function(){return 1}}if(f.with_edge_labels){var Pa=f.edge_labels;aa=ua&&!m(Pa)?V:"object"===l(Pa)?function(a){return J(Da,a.node,"")}:fa(Pa)?Pa:r(Pa)?function(a){return a.data[Pa]}:function(a){return a.edge};f.edge_labels=aa}if(ua&&f.weighted_stroke){var ua=La(a.K(null,!0),function(a,b){b=V({data:b[2]});return a>b?a:b}),ae=e.scale.linear().range([2,f.edge_style["stroke-width"]]).domain([0,ua]);f.edge_style["stroke-width"]=
function(a){return ae(V.call(this,a))}}k.select("svg.jsnx").remove();k.attr("width",C+"px").attr("height",U+"px").style("opacity",1E-6).transition().duration(1E3).style("opacity",1);var be={size:!0,nodes:!0,links:!0,start:!0};O(ha,function(a){if(!(a in be))q[a](ha[a])});q.nodes([]).links([]).size([C,U]);var $a=1,I=1;if(f.pan_zoom.enabled){var jd=f.pan_zoom.scale;(function(){var a=!1,b=1,c=$a;k.call(e.behavior.zoom().on("zoom",function(){var f=e.event.sourceEvent.shiftKey;(f=jd&&f||!(jd||f))&&!a?(b=
e.event.scale,c=$a,a=!0):!f&&a&&(a=!1);$a=f?e.event.scale/b*c:$a;I=f?I:$a/e.event.scale;f=e.event.translate;p.attr("transform","translate("+f[0]+","+f[1]+")scale("+e.event.scale+")");d()}))})()}var hd=ca,qa=f.edge_offset,rb=f.node_attr.r,sb=f.node_style["stroke-width"];"circle"===f.node_shape?(fa(rb)||(rb=function(){return f.node_attr.r}),fa(sb)||(sb=function(){return f.node_style["stroke-width"]}),qa=function(a){return[rb(a.source)+sb(a.source),rb(a.target)+sb(a.target)]}):(da(qa)&&(qa=function(){return f.edge_offset}),
ea(qa)&&(qa=function(){return[f.edge_offset,f.edge_offset]}));var ia=f.edge_style["stroke-width"];fa(ia)||(ia=function(){return f.edge_style["stroke-width"]});var tb=f.edge_style.fill;fa(tb)||(tb=function(){return f.edge_style.fill});var va=f.edge_label_offset,hd=id?function(){ta.V.each(function(a){if(a.source===a.target){var b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,k=a.target.y,p=y.angle(c,d,g,k),g=Math.sqrt(Math.pow(g-c,2)+Math.pow(k-d,2)),w=g/2,k=qa(a),k=[k[0]*I,k[1]*I],q=1/I,D=
ia(a)*I,D=90<p&&279>p;b.attr("transform",["translate(",c,",",d,")rotate(",p,")"].join(""));b.select(".line").attr("d",e.svg.line().interpolate("bundle")([[0,-k[0]/2],[20,-k[0]/2-45],[-20,-k[0]/2-45],[0,-k[0]/2]]));b.select(".line").style("fill","none").style("stroke",tb(a)).style("stroke-width",ia(a)/2*I);f.with_edge_labels&&b.select("text").attr("x",(D?1:-1)*va.x*q+k[0]+(g*q-k[0]-k[1])/2).attr("y",-ia(a)/4+-va.y*q+k[0]/2-45).attr("transform","scale("+I+")"+(D?"rotate(180,"+1/I*w+",0)":""))}else b=
e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,k=a.target.y,p=y.angle(c,d,g,k),g=Math.sqrt(Math.pow(g-c,2)+Math.pow(k-d,2)),k=qa(a),k=[k[0]*I,k[1]*I],b.attr("transform",["translate(",c,",",d,")rotate(",p,")"].join("")),D=ia(a)*I,c=g-k[1]-2*D,d=D/2,b.select(".line").attr("d",["M",k[0],0,"L",k[0],-d,"L",c,-d,"L",c,-D,"L",g-k[1],0,"z"].join(" ")),q=1/I,b.select("text").attr("x",va.x*q+k[0]+(g*q-k[0]-k[1])/2).attr("y",-ia(a)/2+-va.y*q).attr("transform","scale("+I+")")})}:function(){ta.V.each(function(a){if(a.source===
a.target){var b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,k=a.target.y,p=y.angle(c,d,g,k),g=Math.sqrt(Math.pow(g-c,2)+Math.pow(k-d,2)),k=g/2,q=qa(a),q=[q[0]*I,q[1]*I],w=1/I,D=ia(a)*I,ha=90<p&&279>p;b.attr("transform",["translate(",c,",",d,")rotate(",p,")"].join(""));b.select(".line").attr("d",e.svg.line().interpolate("bundle")([[0,-q[0]/2],[20,-q[0]/2-45],[-20,-q[0]/2-45],[0,-q[0]/2]]));b.select(".line").style("fill","none").style("stroke",tb(a)).style("stroke-width",ia(a)/2*I);f.with_edge_labels&&
b.select("text").attr("x",(ha?1:-1)*va.x*w+q[0]+(g*w-q[0]-q[1])/2).attr("y",-ia(a)/4+-va.y*w+q[0]/2-45).attr("transform","scale("+I+")"+(ha?"rotate(180,"+1/I*k+",0)":""))}else b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,k=a.target.y,p=y.angle(c,d,g,k),g=Math.sqrt(Math.pow(g-c,2)+Math.pow(k-d,2)),k=g/2,q=qa(a),q=[q[0]*I,q[1]*I],w=1/I,D=ia(a)*I,ha=90<p&&279>p,b.attr("transform",["translate(",c,",",d,")rotate(",p,")"].join("")),b.select(".line").attr("d",["M",q[0],D/4,"L",q[0],-D/4,"L",g-
q[1],-D/4,"L",g-q[1],D/4,"z"].join(" ")),f.with_edge_labels&&b.select("text").attr("x",(ha?1:-1)*va.x*w+q[0]+(g*w-q[0]-q[1])/2).attr("y",-ia(a)/4+-va.y*w).attr("transform","scale("+I+")"+(ha?"rotate(180,"+1/I*k+",0)":""))})};q.on("tick",d);C=a.ka();U=a.K();g&&(c=!1,C=a.J(g),U=a.K(g));ta.T=vd(a,C,q,w,f.node_shape,D);ta.V=wd(a,U,q,b,aa);xd(ta.T,{attr:f.node_attr,style:f.node_style,Fa:f.label_style,Ea:f.label_attr},f.with_labels);yd(ta.V,{attr:f.edge_attr,style:f.edge_style,Fa:f.edge_label_style,Ea:f.edge_label_attr},
f.with_edge_labels,null,id);c?zd(a,q,f,ta):a.bound?Ad(a):Bd(a);q.start();return q});function vd(a,b,c,d,e,f){var g=c.nodes();O(b,function(b){var c=a.node.get(b);b={node:b,data:c,G:a};g.push(b);c.__d3datum__=b});d=d.data(g,Cd);b=d.enter().append("g").classed("node",!0).call(c.drag);b.append(e).classed("node-shape",!0);f&&b.append("text").text(f);return d}
function wd(a,b,c,d,e){var f=c.links();O(b,function(b){var c=b[0],d=b[1];b=b[2]||a.Ba(c,d);c={edge:[c,d],redge:[d,c],source:a.node.get(c).__d3datum__,target:a.node.get(d).__d3datum__,data:b,G:a};f.push(c);b.__d3datum__=c});d=d.data(f,Dd);b=d.enter().append("g").classed("edge",!0);b.append("path").classed("line",!0);e&&b.append("text").text(e);return d}
function xd(a,b,c,d){if(null!=d){var e={};O(d,function(a){e[n(a)?a[0]:a]=!0});a=a.filter(function(a){return a.node in e})}var f=a.selectAll(".node-shape");G(b.attr,function(a,b){f.attr(b,a)});G(b.style,function(a,b){f.style(b,a)});if(c){var g=a.selectAll("text");G(b.Ea,function(a,b){g.attr(b,a)});G(b.Fa,function(a,b){g.style(b,a)})}}
function yd(a,b,c,d,e){if(null!=d){var f={};O(d,function(a){f[[a[0],a[1]]]=!0});a=a.filter(function(a){return a.edge in f||e||a.redge in f})}var g=a.selectAll(".line");G(b.attr,function(a,b){g.attr(b,a)});G(b.style,function(a,b){"stroke-width"!=b&&g.style(b,a)});g.style("stroke-width",0);if(c){var k=a.selectAll("text");G(b.Ea,function(a,b){k.attr(b,a)});G(b.Fa,function(a,b){k.style(b,a)})}}function Cd(a){return a.node}function Dd(a){return a.edge}
function Ed(a,b,c,d){var e=c.nodes();O(a.J(b),function(b){za(e,a.node.get(b).__d3datum__)});d=d.data(e,Cd);d.exit().remove();return d}function Fd(a,b,c,d){var e=c.links();O(b,function(b){za(e,J(a.Ba(b[0],b[1],{}),"__d3datum__",null))});d=d.data(e,Dd);d.exit().remove();return d}
function zd(a,b,c,d){Ad(a,!1);var e=a.constructor.prototype,f=c.node_shape,g={attr:c.node_attr,style:c.node_style,Ea:c.label_attr,Fa:c.label_style},k={attr:c.edge_attr,style:c.edge_style,Ea:c.edge_label_attr,Fa:c.edge_label_style},p=c.labels,w=c.edge_labels,q=c.with_labels,C=c.with_edge_labels,U=a.u();a.add_node=a.sa=function(a){var c=!this.ba(a);e.add_node.apply(this,arguments);c&&(d.T=vd(this,[a],b,d.T,f,p));xd(d.T,g,q,[a]);b.start()};a.add_nodes_from=a.Q=function(a){var c=sa(S(a),function(a){return!this.ba(n(a)?
a[0]:a)},this);e.add_nodes_from.apply(this,arguments);0<c.length&&(d.T=vd(this,c,b,d.T,f,p));xd(d.T,g,q,a);b.start()};a.add_edge=a.q=function(c,D){var aa=!this.ya(c,D),V=[];aa&&(V=sa(c==D?[c]:[c,D],function(a){return!this.ba(a)},this));e.add_edge.apply(a,arguments);0<V.length&&(d.T=vd(this,V,b,d.T,f,p),xd(d.T,g,q,V));aa&&(d.V=wd(this,[[c,D]],b,d.V,w));yd(d.V,k,C,[[c,D]],U);b.start()};a.add_edges_from=a.D=function(c){var D=[],aa=[],V={},U={},ua=this.u();O(c,function(a){var b=a[0];a=a[1];var c;(c=this.ya(b,
a))||(c=[b,a]in V)||!(c=!ua)||(c=[a,b]in V);c||(D.push([b,a]),V[[b,a]]=!0,this.ba(b)||b in U||(aa.push(b),U[b]=!0),this.ba(a)||a in U||(aa.push(a),U[a]=!0))},this);e.add_edges_from.apply(a,arguments);0<aa.length&&(d.T=vd(this,aa,b,d.T,f,p),xd(d.T,g,q,aa));0<D.length&&(d.V=wd(this,D,b,d.V,w));yd(d.V,k,C,D,ua);b.start()};a.remove_node=a.za=function(c){try{if(this.ba(c)){d.T=Ed(this,[c],b,d.T);var f=this.K([c]);this.u()&&(f=Ma(f,this.va([c])));d.V=Fd(this,f,b,d.V);b.resume()}}catch(g){}e.remove_node.apply(a,
arguments)};a.remove_nodes_from=a.Ia=function(c){try{d.T=Ed(this,c,b,d.T);var f=this.K(c);this.u()&&(f=Ma(f,this.va(c)));d.V=Fd(this,f,b,d.V);b.resume()}catch(g){}e.remove_nodes_from.apply(a,arguments)};a.remove_edge=a.ha=function(c,f){try{d.V=Fd(this,[[c,f]],b,d.V),b.resume()}catch(g){}e.remove_edge.apply(a,arguments)};a.remove_edges_from=a.qa=function(c){try{d.V=Fd(this,c,b,d.V),b.resume()}catch(f){}e.remove_edges_from.apply(a,arguments)};a.clear=a.clear=function(){d.T=d.T.data([],Cd);d.T.exit().remove();
d.V=d.V.data([],Dd);d.V.exit().remove();b.nodes([]).links([]).resume();e.clear.apply(a,arguments)};a.bound=!0}t("jsnx.is_bound",function(a){return a.bound});function Ad(a,b){if(a.bound){var c=a.constructor.prototype;v(td,function(b){a[b]=c[b]});delete a.bound;m(b)&&!b||Bd(a)}}t("jsnx.unbind",Ad);function Bd(a){O(a.ka(!0),function(a){ab(a[1],"__d3datum__")});O(a.K(null,!0),function(a){ab(a[2],"__d3datum__")})}
var ud={layout_attr:{charge:-120,linkDistance:60},node_shape:"circle",node_attr:{r:10},node_style:{"stroke-width":2,stroke:"#333",fill:"#999",cursor:"pointer"},edge_attr:{},edge_style:{fill:"#000","stroke-width":3},label_attr:{},label_style:{"text-anchor":"middle","dominant-baseline":"central",cursor:"pointer","-webkit-user-select":"none",fill:"#000"},edge_label_attr:{},edge_label_style:{"font-size":"0.8em","text-anchor":"middle","-webkit-user-select":"none"},edge_label_offset:{x:0,y:0.5},with_labels:!1,
with_edge_labels:!1,edge_offset:10,weighted:!1,weights:"weight",weighted_stroke:!0,pan_zoom:{enabled:!0,scale:!0}};function Gd(a,b){var c=T(a),d,e,f=new A;try{e=[c.next()]}catch(g){if(g!==z)throw g;return f}f.next=function(){if(0===e.length)throw z;return e.splice(0,1)[0]};return W(f,function(a){d=a;return T(b)},function(){try{var a=c.next();e.push(a);return[d,a]}catch(b){if(b!==z)throw b;}})}function Hd(a,b,c){c=Id(b,c);c.D(Gd(b,a));return c}t("jsnx.generators.classic.full_rary_tree",Hd);t("jsnx.full_rary_tree",Hd);
function Jd(a,b,c){b=1===a?2:Math.floor((1-Math.pow(a,b+1))/(1-a));c=Id(b,c);c.D(Gd(b,a));return c}t("jsnx.generators.classic.balanced_tree",Jd);t("jsnx.balanced_tree",Jd);function Kd(a,b){var c=Id(a,b);c.name("complete_graph("+a+")");1<a&&c.D(c.u()?Bb(T(a)):Ab(T(a)));return c}t("jsnx.generators.classic.complete_graph",Kd);t("jsnx.complete_graph",Kd);function Ld(a,b){var c=Md(a,b);c.name("cycle_graph("+a+")");1<a&&c.q(a-1,0);return c}t("jsnx.generators.classic.cycle_graph",Ld);
t("jsnx.cycle_graph",Ld);function Id(a,b){a instanceof Q&&(b=a,a=null);null!=a||(a=0);var c;null!=b?(c=b,c.clear()):c=new Q;c.Q(T(a));c.name("empty_graph("+a+")");return c}t("jsnx.generators.classic.empty_graph",Id);t("jsnx.empty_graph",Id);
function Nd(a,b,c,d){var e=Id(0,d);e.name("grid_2d_graph");d=Na(T(a));var f=Na(T(b));v(d,function(a){v(f,function(b){e.sa([a,b])})});E(T(1,a),function(a){v(f,function(b){e.q([a,b],[a-1,b])})});v(d,function(a){E(T(1,b),function(b){e.q([a,b],[a,b-1])})});e.u()&&(E(T(0,a-1),function(a){v(f,function(b){e.q([a,b],[a+1,b])})}),v(d,function(a){E(T(0,b-1),function(b){e.q([a,b],[a,b+1])})}));c&&(2<b&&(v(d,function(a){e.q([a,0],[a,b-1])}),e.u()&&v(d,function(a){e.q([a,b-1],[a,0])})),2<a&&(v(f,function(b){e.q([0,
b],[a-1,b])}),e.u()&&v(f,function(b){e.q([a-1,b],[0,b])})),e.name("periodic_grid_2d_graph("+a+","+b+")"));return e}t("jsnx.generators.classic.grid_2d_graph",Nd);t("jsnx.grid_2d_graph",Nd);function Od(a){a=Id(0,a);a.name("null_graph()");return a}t("jsnx.generators.classic.null_graph",Od);t("jsnx.null_graph",Od);function Md(a,b){var c=Id(a,b);c.name("path_graph("+a+")");c.D(F(T(a-1),function(a){return[a,a+1]}));return c}t("jsnx.generators.classic.path_graph",Md);t("jsnx.path_graph",Md);
function Pd(a){a=Id(1,a);a.name("null_graph()");return a}t("jsnx.generators.classic.trivial_graph",Pd);t("jsnx.trivial_graph",Pd);function Qd(a,b,c){null!=c||(c=!1);var d=Id(a);d.name("fast_gnp_random_graph("+a+","+b+")");if(0>=b||1<=b)return Rd(a,b,c);var e=1,f=-1;b=Math.log(1-b);if(c)for(d=new Y(d);e<a;){c=Math.log(1-Math.random());f=f+1+Math.floor(c/b);for(e===f&&(f+=1);f>=a&&e<a;)f-=a,e+=1,e==f&&(f+=1);e<a&&d.q(e,f)}else for(;e<a;){c=Math.log(1-Math.random());for(f=f+1+Math.floor(c/b);f>=e&&e<a;)f-=e,e+=1;e<a&&d.q(e,f)}return d}t("jsnx.generators.random_graphs.fast_gnp_random_graph",Qd);t("jsnx.fast_gnp_random_graph",Qd);
function Rd(a,b,c){var d;d=c?new Y:new Q;d.Q(T(a));d.name("gnp_random_graph("+a+","+b+")");if(0>=b)return d;if(1<=b)return Kd(a,d);a=d.u()?Bb(T(a)):Ab(T(a));E(a,function(a){Math.random()<b&&d.q(a[0],a[1])});return d}t("jsnx.generators.random_graphs.gnp_random_graph",Rd);t("jsnx.gnp_random_graph",Rd);t("jsnx.binomial_graph",Rd);t("jsnx.erdos_renyi_graph",Rd);function Sd(a,b){if(!Nc(a))throw new L("Invalid degree sequence");if(null!=b){if(b.u())throw new L("Directed Graph not supported");if(b.aa())throw new L("Havel-Hakimi requires simple graph");}var c=a.length,d=Id(c,b);if(0===c||0===Math.max.apply(null,a))return d;for(c=Na(R(d,function(b){return[a[b],b]}));0<c.length;){c.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:+a[1]-+b[1]});if(0>c[0][0])return!1;var e=c.pop();if(0===e[0])break;if(e[0]>c.length)return!1;for(var f=c.length,g=f-e[0];g<f;g++)d.q(e[1],
c[g][1]),c[g][0]-=1}d.name("havel_hakimi_graph "+d.order()+" nodes "+d.size()+" edges");return d}t("jsnx.generators.degree_seq.havel_hakimi_graph",Sd);t("jsnx.havel_hakimi_graph",Sd);function Td(){var a=new Q;a.Q(T(34));a.name("Zachary's Karate Club");var b=0;v("0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0;1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0;1 1 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0;1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1;0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1;0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0 0 1 1 1 0 1;0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0".split(";"),
function(c){O(c.split(" "),function(c,e){"1"===c&&a.q(b,e)});b+=1});return a}t("jsnx.generators.social.karate_club_graph",Td);t("jsnx.karate_club_graph",Td);
function Ud(){var a=new Q;a.Q("Evelyn Jefferson;Laura Mandeville;Theresa Anderson;Brenda Rogers;Charlotte McDowd;Frances Anderson;Eleanor Nye;Pearl Oglethorpe;Ruth DeSand;Verne Sanderson;Myra Liddel;Katherina Rogers;Sylvia Avondale;Nora Fayette;Helen Lloyd;Dorothy Murchison;Olivia Carleton;Flora Price".split(";"),{mb:0});a.Q("E1 E2 E3 E4 E5 E6 E7 E8 E9 E10 E11 E12 E13 E14".split(" "),{mb:1});a.D([["Evelyn Jefferson","E1"],["Evelyn Jefferson","E2"],["Evelyn Jefferson","E3"],["Evelyn Jefferson","E4"],
["Evelyn Jefferson","E5"],["Evelyn Jefferson","E6"],["Evelyn Jefferson","E8"],["Evelyn Jefferson","E9"],["Laura Mandeville","E1"],["Laura Mandeville","E2"],["Laura Mandeville","E3"],["Laura Mandeville","E5"],["Laura Mandeville","E6"],["Laura Mandeville","E7"],["Laura Mandeville","E8"],["Theresa Anderson","E2"],["Theresa Anderson","E3"],["Theresa Anderson","E4"],["Theresa Anderson","E5"],["Theresa Anderson","E6"],["Theresa Anderson","E7"],["Theresa Anderson","E8"],["Theresa Anderson","E9"],["Brenda Rogers",
"E1"],["Brenda Rogers","E3"],["Brenda Rogers","E4"],["Brenda Rogers","E5"],["Brenda Rogers","E6"],["Brenda Rogers","E7"],["Brenda Rogers","E8"],["Charlotte McDowd","E3"],["Charlotte McDowd","E4"],["Charlotte McDowd","E5"],["Charlotte McDowd","E7"],["Frances Anderson","E3"],["Frances Anderson","E5"],["Frances Anderson","E6"],["Frances Anderson","E8"],["Eleanor Nye","E5"],["Eleanor Nye","E6"],["Eleanor Nye","E7"],["Eleanor Nye","E8"],["Pearl Oglethorpe","E6"],["Pearl Oglethorpe","E8"],["Pearl Oglethorpe",
"E9"],["Ruth DeSand","E5"],["Ruth DeSand","E7"],["Ruth DeSand","E8"],["Ruth DeSand","E9"],["Verne Sanderson","E7"],["Verne Sanderson","E8"],["Verne Sanderson","E9"],["Verne Sanderson","E12"],["Myra Liddel","E8"],["Myra Liddel","E9"],["Myra Liddel","E10"],["Myra Liddel","E12"],["Katherina Rogers","E8"],["Katherina Rogers","E9"],["Katherina Rogers","E10"],["Katherina Rogers","E12"],["Katherina Rogers","E13"],["Katherina Rogers","E14"],["Sylvia Avondale","E7"],["Sylvia Avondale","E8"],["Sylvia Avondale",
"E9"],["Sylvia Avondale","E10"],["Sylvia Avondale","E12"],["Sylvia Avondale","E13"],["Sylvia Avondale","E14"],["Nora Fayette","E6"],["Nora Fayette","E7"],["Nora Fayette","E9"],["Nora Fayette","E10"],["Nora Fayette","E11"],["Nora Fayette","E12"],["Nora Fayette","E13"],["Nora Fayette","E14"],["Helen Lloyd","E7"],["Helen Lloyd","E8"],["Helen Lloyd","E10"],["Helen Lloyd","E11"],["Helen Lloyd","E12"],["Dorothy Murchison","E8"],["Dorothy Murchison","E9"],["Olivia Carleton","E9"],["Olivia Carleton","E11"],
["Flora Price","E9"],["Flora Price","E11"]]);return a}t("jsnx.generators.social.davis_southern_women_graph",Ud);t("jsnx.davis_southern_women_graph",Ud);
function Vd(){var a=new Q;a.q("Acciaiuoli","Medici");a.q("Castellani","Peruzzi");a.q("Castellani","Strozzi");a.q("Castellani","Barbadori");a.q("Medici","Barbadori");a.q("Medici","Ridolfi");a.q("Medici","Tornabuoni");a.q("Medici","Albizzi");a.q("Medici","Salviati");a.q("Salviati","Pazzi");a.q("Peruzzi","Strozzi");a.q("Peruzzi","Bischeri");a.q("Strozzi","Ridolfi");a.q("Strozzi","Bischeri");a.q("Ridolfi","Tornabuoni");a.q("Tornabuoni","Guadagni");a.q("Albizzi","Ginori");a.q("Albizzi","Guadagni");a.q("Bischeri",
"Guadagni");a.q("Guadagni","Lamberteschi");return a}t("jsnx.generators.social.florentine_families_graph",Vd);t("jsnx.florentine_families_graph",Vd);function Wd(a,b){if(null!=b&&b.u())throw new L("Directed Graph not supported");return Xd(a,b)}t("jsnx.generators.small.make_small_undirected_graph",Wd);
function Xd(a,b){var c=a[0],d=a[1],e=a[2],f=Id(e,b),g=f.nodes();if("adjacencylist"==c){var k=a[3];if(k.length!=e)throw new L("invalid graph_description");v(g,function(a){O(k[a],function(b){f.q(b-1,a)})})}else"edgelist"==c&&O(a[3],function(a){var b=a[0]-1;a=a[1]-1;if(0>b||b>e-1||0>a||a>e-1)throw new L("invalid graph_description");f.q(b,a)});f.name=d;return f}t("jsnx.generators.small.make_small_graph",Xd);t("jsnx.make_small_graph",Xd);
function Yd(a){return Wd(["adjacencylist","Bull Graph",5,[[2,3],[1,3,4],[1,2,5],[2],[3]]],a)}t("jsnx.generators.small.bull_graph",Yd);t("jsnx.bull_graph",Yd);function Zd(a){return Wd(["adjacencylist","Krackhardt Kite Social Network",10,[[2,3,4,6],[1,4,5,7],[1,4,6],[1,2,3,5,6,7],[2,4,7],[1,3,4,7,8],[2,4,5,6,8],[6,7,9],[8,10],[9]]],a)}t("jsnx.generators.small.krackhardt_kite_graph",Zd);t("jsnx.krackhardt_kite_graph",Zd);function $d(a,b,c){var d=b;fa(d.set)||fa(d.get)||(d=new N(d));fa(b)&&(d=new N,E(a.ka(),function(a){d.set(a,b(a))}));return!m(c)||c?ce(a,d):de(a,d)}t("jsnx.relabel.relabel_nodes",$d);t("jsnx.relabel_nodes",$d);
function de(a,b){var c=new P(b.keys()),d;if(0<c.da(b.values()).count()){c=new Y(b);c.qa(c.Ja());try{d=Rc(c)}catch(e){if(e instanceof kb)throw new kb("The node label sets are overlapping and no ordering can resolve the mapping. Use copy=True.");}d.reverse()}else d=c;var f=a.aa(),g=a.u(),k;E(d,function(c){var d;if(b.has(c)){d=b.get(c);if(!a.ba(c))throw new L("Node "+c+" is not in the graph.");a.sa(d,a.node.get(c));f?(k=x(a.edges(c,!0,!0),function(a){return[d,a[1],a[2],a[3]]}),g&&(k=Aa(k,x(a.Da(c,!0,
!0),function(a){return[a[0],d,a[2],a[3]]})))):(k=x(a.edges(c,!0),function(a){return[d,a[1],a[2]]}),g&&(k=Aa(k,x(a.Da(c,!0),function(a){return[a[0],d,a[2]]}))));a.za(c);a.D(k)}});return a}
function ce(a,b){var c=new a.constructor;c.name("("+a.name()+")");a.aa()?c.D(F(a.K(null,!0,!0),function(a){return[b.get(a[0],a[0]),b.get(a[1],a[1]),a[2],bb(a[3])]})):c.D(F(a.K(null,!0),function(a){return[b.get(a[0],a[0]),b.get(a[1],a[1]),bb(a[2])]}));c.Q(F(xb(a),function(a){return b.get(a,a)}));var d=new N;a.node.forEach(function(c){d.set(b.get(c,c),bb(a.node.get(c)))});d.forEach(function(a,b){c.node.set(a,b)});K(c.graph,bb(a.graph));return c}
function ee(a,b,c,d){3===arguments.length&&s(c)?(d=c,c=null):2===arguments.length&&(s(b)?(d=b,b=null):r(b)&&(c=b,b=null));null!=b||(b=0);null!=c||(c="default");null!=d||(d=!0);a.xa();var e=new N,f,g,k,p;if("default"===c)for(f=a.nodes(),g=0,k=b,p=f.length;g<p;g++,k++)e.set(f[g],k);else if("sorted"===c)for(f=a.nodes(),u.sort.call(f,Ha),g=0,k=b,p=f.length;g<p;g++,k++)e.set(f[g],k);else if("increasing degree"===c)for(f=Na(a.ga()),f.sort(function(a,b){return a[1]-b[1]}),g=0,k=b,p=f.length;g<p;g++,k++)e.set(f[g][0],
k);else if("decreasing degree"===c)for(f=Na(a.ga()),f.sort(function(a,b){return b[1]-a[1]}),g=0,k=b,p=f.length;g<p;g++,k++)e.set(f[g][0],k);else throw new L("Unkown node ordering: "+c);g=$d(a,e);g.name("("+a.name()+")_with_int_labels");d||(g.node_labels=e);return g}t("jsnx.relabel.convert_node_labels_to_integers",ee);t("jsnx.convert_node_labels_to_integers",ee);}));
