(function(global, factory) { function extractNS(){ var g = {}; return factory.call(g, global),g.jsnx;} if(typeof define === 'function' && define.amd){ /*AMD*/ define(extractNS); } else if (typeof module !== 'undefined' && module.exports){ /*node*/ module.exports = extractNS(); } else { factory.call(global, global); } }(this, function(window) {var h,aa=this;function ca(){}
function l(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function m(a){return void 0!==a}function da(a){return"array"==l(a)}function n(a){var b=l(a);return"array"==b||"object"==b&&"number"==typeof a.length}function r(a){return"string"==typeof a}function t(a){return"boolean"==typeof a}function ea(a){return"number"==typeof a}function u(a){return"function"==l(a)}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var ga="closure_uid_"+(1E9*Math.random()>>>0),ha=0;
function ia(a,b,c){return a.call.apply(a.bind,arguments)}function ja(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function la(a,b,c){la=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return la.apply(null,arguments)}
function v(a,b){var c=a.split("."),d=aa;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}function ma(a,b){function c(){}c.prototype=b.prototype;a.jb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ya=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};function na(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")}Math.random();var w=Array.prototype,pa=w.indexOf?function(a,b,c){return w.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(r(a))return r(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},x=w.forEach?function(a,b,c){w.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},qa=w.filter?function(a,b,c){return w.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=r(a)?
a.split(""):a,k=0;k<d;k++)if(k in g){var p=g[k];b.call(c,p,k,a)&&(e[f++]=p)}return e},ra=w.map?function(a,b,c){return w.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=r(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e},va=w.reduce?function(a,b,c,d){d&&(b=la(b,d));return w.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;x(a,function(c,g){e=b.call(d,e,c,g,a)});return e},wa=w.some?function(a,b,c){return w.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?
a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};function xa(a){if(!da(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0}function ya(a,b){var c=pa(a,b);0<=c&&w.splice.call(a,c,1)}function za(a){return w.concat.apply(w,arguments)}function Aa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ba(a,b,c,d){w.splice.apply(a,Ea(arguments,1))}function Ea(a,b,c){return 2>=arguments.length?w.slice.call(a,b):w.slice.call(a,b,c)}
function Fa(a,b,c){if(!n(a)||!n(b)||a.length!=b.length)return!1;var d=a.length;c=c||Ga;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return!1;return!0}function Ha(a,b){return a>b?1:a<b?-1:0}function Ga(a,b){return a===b}function Ia(a){for(var b=[],c=0;c<a;c++)b[c]=0;return b}function Ja(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}}
function Ka(a){for(var b=Math.random,c=a.length-1;0<c;c--){var d=Math.floor(b()*(c+1)),e=a[c];a[c]=a[d];a[d]=e}};var y={eb:function(a){return Math.floor(Math.random()*a)},kb:function(a,b){return a+Math.random()*(b-a)},clamp:function(a,b,c){return Math.min(Math.max(a,b),c)},Ma:function(a,b){var c=a%b;return 0>c*b?c+b:c},ab:function(a,b,c){return a+c*(b-a)},cb:function(a,b,c){return Math.abs(a-b)<=(c||1E-6)},na:function(a){return y.Ma(a,360)},xa:function(a){return a*Math.PI/180},Ua:function(a){return 180*a/Math.PI},Wa:function(a,b){return b*Math.cos(y.xa(a))},Xa:function(a,b){return b*Math.sin(y.xa(a))},angle:function(a,
b,c,d){return y.na(y.Ua(Math.atan2(d-b,c-a)))},Va:function(a,b){var c=y.na(b)-y.na(a);180<c?c-=360:-180>=c&&(c=360+c);return c},hb:function(a){return 0==a?0:0>a?-1:1},bb:function(a,b,c,d){c=c||function(a,b){return a==b};d=d||function(b){return a[b]};for(var e=a.length,f=b.length,g=[],k=0;k<e+1;k++)g[k]=[],g[k][0]=0;for(var p=0;p<f+1;p++)g[0][p]=0;for(k=1;k<=e;k++)for(p=1;p<=f;p++)c(a[k-1],b[p-1])?g[k][p]=g[k-1][p-1]+1:g[k][p]=Math.max(g[k-1][p],g[k][p-1]);for(var q=[],k=e,p=f;0<k&&0<p;)c(a[k-1],b[p-
1])?(q.unshift(d(k-1,p-1)),k--,p--):g[k-1][p]>g[k][p-1]?k--:p--;return q},sum:function(a){return va(arguments,function(a,c){return a+c},0)},Ea:function(a){return y.sum.apply(null,arguments)/arguments.length},Sa:function(a){var b=arguments.length;if(2>b)return 0;var c=y.Ea.apply(null,arguments);return y.sum.apply(null,ra(arguments,function(a){return Math.pow(a-c,2)}))/(b-1)},ib:function(a){return Math.sqrt(y.Sa.apply(null,arguments))},$a:function(a){return isFinite(a)&&0==a%1},Za:function(a){return isFinite(a)&&
!isNaN(a)},gb:function(a,b){return Math.floor(a+(b||2E-15))},fb:function(a,b){return Math.ceil(a-(b||2E-15))}};var z="StopIteration"in aa?aa.StopIteration:Error("StopIteration");function A(){}A.prototype.b=function(){throw z;};A.prototype.H=function(){return this};function B(a){if(a instanceof A)return a;if("function"==typeof a.H)return a.H(!1);if(n(a)){var b=0,c=new A;c.b=function(){for(;;){if(b>=a.length)throw z;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function D(a,b,c){if(n(a))try{x(a,b,c)}catch(d){if(d!==z)throw d;}else{a=B(a);try{for(;;)b.call(c,a.b(),void 0,a)}catch(e){if(e!==z)throw e;}}}function E(a,b,c){var d=B(a);a=new A;a.b=function(){for(;;){var a=d.b();return b.call(c,a,void 0,d)}};return a}function La(a,b){var c=0;D(a,function(a){c=b.call(void 0,c,a)});return c}function Ma(a){var b=B(arguments),c=new A,d=null;c.b=function(){for(;;){if(null==d){var a=b.b();d=B(a)}try{return d.b()}catch(c){if(c!==z)throw c;d=null}}};return c}
function Na(a){if(n(a))return Aa(a);a=B(a);var b=[];D(a,function(a){b.push(a)});return b}function Qa(a,b){try{return B(a).b()}catch(c){if(c!=z)throw c;return b}};function Ra(){}Ra.Ia=function(){return Ra.sa?Ra.sa:Ra.sa=new Ra};Ra.prototype.Na=0;function Sa(a){if(!n(a))return!1;for(var b=0,c=a.length;b<c;b++)if(isNaN(a[b]))return!1;return!0}v("jsnx.utils.misc.is_list_of_ints",Sa);v("jsnx.utils.is_list_of_ints",Sa);function Ta(a){var b=0;return E(a,function(a){return b+=a})}v("jsnx.utils.misc.cumulative_sum",Ta);v("jsnx.utils.cumulative_sum",Ta);function Ua(){return":"+(Ra.Ia().Na++).toString(36)}v("jsnx.utils.misc.generate_unique_node",Ua);v("jsnx.utils.generate_unique_node",Ua);function F(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Va(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function G(a){var b=0,c;for(c in a)b++;return b}function Wa(a){for(var b in a)return b}function Xa(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ya(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Za(a){for(var b in a)delete a[b]}function ab(a,b){b in a&&delete a[b]}function I(a,b,c){return b in a?a[b]:c}
function bb(a){var b={},c;for(c in a)b[c]=a[c];return b}var cb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function J(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<cb.length;f++)c=cb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}
function db(a){var b=arguments.length;if(1==b&&da(arguments[0]))return db.apply(null,arguments[0]);if(b%2)throw Error("Uneven number of arguments");for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};function eb(a){var b=arguments;1===arguments.length&&n(arguments[0])&&(b=arguments[0]);this.da="t";for(var c=0,d=b.length;c<d;c++)this[c]=b[c],this.da+=fb(b[c]);this.length=b.length;b=this;Object.isFrozen&&!Object.isFrozen(this)&&(b=Object.create(this),Object.freeze(b));return b}eb.prototype.da="";eb.prototype.length=0;v("jsnx.contrib.Tuple.prototype.length",eb.prototype.length);eb.prototype.toString=function(){return this.da};v("jsnx.contrib.Tuple.prototype.toString",eb.prototype.toString);
function gb(a){return n(arguments[0])?new eb(arguments[0]):new eb(arguments)}v("jsnx.Tuple",gb);v("jsnx.t",gb);function hb(a){this.name="JSNetworkXException";this.message=a}v("jsnx.exception.JSNetworkXException",hb);hb.prototype=Error();hb.prototype.constructor=hb;v("jsnx.JSNetworkXException",hb);function K(a){hb.call(this,a);this.name="JSNetworkXError"}ma(K,hb);v("jsnx.exception.JSNetworkXError",K);v("jsnx.JSNetworkXError",K);function ib(a){hb.call(this,a);this.name="JSNetworkXPointlessConcept"}ma(ib,hb);v("jsnx.exception.JSNetworkXPointlessConcept",ib);v("jsnx.JSNetworkXPointlessConcept",ib);
function jb(a){hb.call(this,a);this.name="JSNetworkXAlgorithmError"}ma(jb,hb);v("jsnx.exception.JSNetworkXAlgorithmError",jb);v("jsnx.JSNetworkXAlgorithmError",jb);function kb(a){jb.call(this,a);this.name="JSNetworkXUnfeasible"}ma(kb,jb);v("jsnx.exception.JSNetworkXUnfeasible",kb);v("jsnx.JSNetworkXUnfeasible",kb);function lb(a){kb.call(this,a);this.name="JSNetworkXNoPath"}ma(lb,kb);v("jsnx.exception.JSNetworkXNoPath",lb);v("jsnx.JSNetworkXNoPath",lb);
function mb(a){jb.call(this,a);this.name="JSNetworkXUnbounded"}ma(mb,jb);v("jsnx.exception.JSNetworkXUnbounded",mb);v("jsnx.JSNetworkXUnbounded",mb);function L(a){this.name="KeyError";this.message=a}L.prototype=Error();L.prototype.constructor=L;v("jsnx.KeyError",L);v("jsnx.version","0.2.0");function fb(a,b){var c=typeof a;return"object"===c||"function"===c?a.hasOwnProperty("__hash__")?a.__hash__:a.toString!==Object.prototype.toString&&a.toString!==Array.prototype.toString?a.toString():b?b(a):"o"+(a[ga]||(a[ga]=++ha)):c.substr(0,1)+a}v("jsnx.contrib.misc.get_hash",fb);function M(a){this.D={};this.C={};this.w={};this.h={};if(null!=a)if(nb(a)||n(a))N(a,function(a){this.set.apply(this,a)},this);else if(fa(a))for(var b in a)this.set(isNaN(+b)?b:+b,a[b])}v("jsnx.contrib.Map",M);v("jsnx.Map",M);function ob(a,b){switch(typeof b){case "number":return a.C;case "string":return a.D;default:return a.w}}M.prototype.get=function(a,b){var c=ob(this,a);if("undefined"!==typeof c[a])return c[a];if(m(b))return b;throw new L("Map does not contain key "+pb(a));};M.prototype.get=M.prototype.get;
M.prototype.has=function(a){return"undefined"!==typeof ob(this,a)[a]};M.prototype.has=M.prototype.has;M.prototype.set=function(a,b){var c=ob(this,a);c[a]=b;c===this.w&&(this.h[a]=a);return b};M.prototype.set=M.prototype.set;M.prototype.remove=function(a){var b=ob(this,a);if("undefined"!==typeof b[a])delete b[a],b===this.w&&delete this.h[a];else throw new L("Map does not contain key "+pb(a));};M.prototype.remove=M.prototype.remove;
M.prototype.items=function(){var a=[],b;for(b in this.C)a.push([+b,this.C[b]]);for(b in this.D)a.push([b,this.D[b]]);for(b in this.w)a.push([this.h[b],this.w[b]]);return a};M.prototype.items=M.prototype.items;M.prototype.copy=function(a){return qb(this,a)};M.prototype.keys=function(){return ra(Ya(this.C),function(a){return+a}).concat(Ya(this.D)).concat(Xa(this.h))};M.prototype.keys=M.prototype.keys;M.prototype.values=function(){return Xa(this.C).concat(Xa(this.D)).concat(Xa(this.w))};
M.prototype.values=M.prototype.values;M.prototype.H=function(){var a=new A,b=Ya(this.D),c=Ya(this.C),d=Ya(this.w),e=0,f=0,g=0;a.b=la(function(){var a;if(e<c.length)return a=c[e++],[+a,this.C[a]];if(f<b.length)return a=b[f++],[a,this.D[a]];if(g<d.length)return a=d[g++],[this.h[a],this.w[a]];throw z;},this);return a};M.prototype.count=function(){return G(this.w)+G(this.C)+G(this.D)};M.prototype.count=M.prototype.count;M.prototype.clear=function(){Za(this.D);Za(this.C);Za(this.w);Za(this.h)};
M.prototype.clear=M.prototype.clear;M.prototype.forEach=function(a,b){D(this,function(c){a.apply(b,c)})};M.prototype.forEach=M.prototype.forEach;function O(a){this.e=new M;null!=a&&(nb(a)||n(a))&&N(a,function(a){this.add(a)},this)}v("jsnx.contrib.Set",O);v("jsnx.Set",O);O.prototype.has=function(a){return this.e.has(a)};O.prototype.has=O.prototype.has;O.prototype.add=function(a){this.e.set(a,!0)};O.prototype.add=O.prototype.add;O.prototype.remove=function(a){try{this.e.remove(a)}catch(b){if(!(b instanceof L))throw b;}};O.prototype.remove=O.prototype.remove;O.prototype.copy=function(a){return qb(this,a)};O.prototype.values=function(){return this.e.keys()};
O.prototype.values=O.prototype.values;O.prototype.H=function(){return E(this.e,function(a){return a[0]})};O.prototype.M=function(a){for(var b=new O(this.values()),c=0,d=arguments.length;c<d;c++){var e=arguments[c];e instanceof O&&(e=e.values());for(var f=0,g=e.length;f<g;f++)b.remove(e[f])}return b};O.prototype.difference=O.prototype.M;
O.prototype.p=function(a){for(var b=new O,c=0,d=arguments.length;c<d;c++){var e=arguments[c];e instanceof O&&(e=e.values());for(var f=0,g=e.length;f<g;f++)this.has(e[f])&&b.add(e[f])}return b};O.prototype.intersection=O.prototype.p;O.prototype.count=function(){return this.e.count()};O.prototype.count=O.prototype.count;O.prototype.clear=function(){this.e.clear()};O.prototype.clear=O.prototype.clear;O.prototype.forEach=function(a,b){D(this,a,b)};O.prototype.forEach=O.prototype.forEach;v("jsnx.filter",function(a,b,c){var d=B(a);a=new A;a.b=function(){for(;;){var a=d.b();if(b.call(c,a,void 0,d))return a}};return a});function ub(a){var b=0;m(b)||(b=null);var c=new M;N(a,function(a){c.set(a,b)});return c}function nb(a){return null!=a&&(a instanceof A||u(a.H))}function vb(a){if(a instanceof P)return a.Q();if(r(a)||n(a))return a.length;if(wb(a))return G(a);throw new TypeError;}
function N(a,b,c,d){t(c)&&(d=c,c=null);if(d){var e=b;b=function(a){e.apply(this,a)}}a instanceof P?D(xb(a),b,c):nb(a)?D(a,b,c):n(a)||r(a)?x(a,b,c):fa(a)&&N(Ya(a),b,c)}v("jsnx.forEach",N);function Q(a,b,c){if(a instanceof P)return Q(xb(a),b,c);if(n(a))return ra(a,b,c);if(nb(a))return E(a,b,c);if(fa(a))return Va(a,b,c);throw new TypeError;}v("jsnx.map",Q);
function yb(a){var b=arguments,c=b[0];if(n(c))return Ja.apply(null,b);if(nb(c)){var c=new A,d=b.length;c.b=function(){for(var a=[],c=0;c<d;c++)a.push(b[c].b());return a};return c}if(fa(c))return Ja.apply(null,ra(b,Ya));throw new TypeError;}function zb(a,b){a=u(b)?R(Q(a,function(){return b.apply(null,arguments)})):R(a);return Math.max.apply(null,a)}
function V(a,b,c){if(0===arguments.length)return B([]);if(1===arguments.length)b=a,a=0,c=1;else if(2===arguments.length)c=1;else if(3===arguments.length&&0===arguments[2])throw"range() step argument must not be zero";var d=new A,e=0>c,f=a,g;d.b=function(){if(e&&f<=b||!e&&f>=b)throw z;g=f;f+=c;return g};return d}
function Ab(a){var b=R(a),c=b.length;if(2>c)return new A;var d=R(V(2));a=new A;a.b=function(){var a=ra(d,function(a){return b[a]});this.b=function(){var a=!1,e;for(e=2;e--;)if(d[e]!=e+c-2){a=!0;break}if(!a)throw z;d[e]+=1;for(a=e+1;2>a;a++)d[a]=d[a-1]+1;return ra(d,function(a){return b[a]})};return a};return a}
function Bb(a){var b=R(a),c=b.length,d=ea(2)?2:c;if(d>c)return new A;var e=R(V(c)),f=R(V(c,c-d,-1));a=new A;var g=new A,k,p=!0;a.b=function(){this.b=k.b;return ra(e.slice(0,d),function(a){return b[a]})};g.b=function(){return p};k=W(g,function(a){if(!a)throw z;p=!1;return V(d-1,-1,-1)},function(a){if(!p)if(f[a]-=1,0===f[a])e.splice.apply(e,[a,e.length].concat(e.slice(a+1).concat([e[a]]))),f[a]=c-a;else{var g=f[a],k=e[a];e[a]=e[e.length-g];e[e.length-g]=k;p=!0;return xb([ra(e.slice(0,d),function(a){return b[a]})])}},
function(a){return a});return a}function Cb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)m(a[c])&&"object"===l(a[c])?"object"===l(a[c])&&"object"===l(d)&&Cb(a[c],d[c]):a[c]=X(d[c]);for(var f=0;f<cb.length;f++)c=cb[f],Object.prototype.hasOwnProperty.call(d,c)&&(m(a[c])&&"object"===l(a[c])?"object"===l(a[c])&&"object"===l(d)&&Cb(a[c],d[c]):a[c]=X(d[c]))}}
function R(a){if(a instanceof P)return R(xb(a));if(n(a))return Aa(a);if(nb(a))return Na(a);if(fa(a))return Ya(a);throw new TypeError;}v("jsnx.toArray",R);function Db(a){var b=new A,c=B(Ya(a));b.b=function(){var b=c.b();return[b,a[b]]};return b}function xb(a){if(a instanceof P)return xb(a.adj.keys());"object"!==l(a)||n(a)||nb(a)||(a=Ya(a));return B(a)}
function W(a,b){var c=new A,d=Ea(arguments,1);if(0===d.length)return a;try{a=B(a)}catch(e){return c.b=function(){if("Not implemented"===e.message)throw new TypeError;},c}var f=0,g=d.length,k=[a];c.b=function(){do try{var a,b;do a=k[f].b(),m(a)&&(b=d[f](a));while(!m(a));if(nb(b)){if(f===g-1)return b;k.push(b);f+=1}else if(m(b))return b}catch(c){if(c!==z)throw c;if(0<f)k.pop(),f-=1;else throw c;}while(1)};return c}v("jsnx.sentinelIterator",function(a,b){var c=new A;c.b=function(){return Qa(a,b)};return c});
function wb(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==l(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var d in a);return void 0===d||b.call(a,d)}
function X(a,b){b=b||[];var c=l(a);if("object"==c&&(u(a.copy)||wb(a))||"array"==c){for(var d=0,e=b.length;d<e;d+=2)if(a===b[d])return b[d+1];if(u(a.copy))return c=a.copy(b),b.push(a,c),c;c="array"==c?[]:{};b.push(a,c);for(var f in a)c[f]=X(a[f],b);return c}return a}function qb(a,b){function c(){}var d={},e,f;c.prototype=a.constructor.prototype;for(e in a)a.hasOwnProperty(e)&&(d[e]=a[e]);d=X(d,b);f=new c;for(e in d)f[e]=d[e];return f}var Fb=function Eb(b,c){return 0===c?b:Eb(c,b%c)};function Gb(a,b){var c=new M;if(null!=b){b=R(b);var d=function(a){return 0<=pa(b,a)};x(b,function(b){c.set(b,qa(a.A(b),d))})}else N(a,function(b){c.set(b,a.A(b))});return c}v("jsnx.contrib.convert.to_map_of_lists",Gb);v("jsnx.to_map_of_lists",Gb);function Hb(a,b){var c=Ib(b);c.i(a.keys());if(c.m()&&!c.c()){var d=new M;a.forEach(function(a,b){x(b,function(b){d.has(b)||c.a(a,b)});d.set(a,1)})}else a.forEach(function(a,b){x(b,function(b){c.a(a,b)})});return c}
v("jsnx.contrib.convert.from_map_of_lists",Hb);v("jsnx.contrib.convert.to_map_of_maps",function(a,b,c){var d=new M;null!=b?(b=R(b),null!=c?x(b,function(e){var f=d.set(e,new M);a.get(e).forEach(function(a){0<=pa(b,a)&&f.set(a,c)})}):x(b,function(c){var f=d.set(c,new M);a.get(c).forEach(function(a,c){0<=pa(b,a)&&f.set(a,c)})})):null!=c?D(a.o(),function(a,b){var g=d.set(b,new M);a.forEach(function(a){g.set(a,c)})}):D(a.o(),function(a,b){var c=d.set(b,new M);a.forEach(function(a,b){c.set(a,b)})});return d});
function Jb(a,b,c){var d=Ib(b),e=new M,f=[];d.i(a.keys());c?d.c()?d.m()?a.forEach(function(a,b){if(n(b))throw Error("Value is not a map.");b.forEach(function(b,c){F(c,function(c,e){d.a(a,b,e,c)})})}):a.forEach(function(a,b){if(n(b))throw Error();b.forEach(function(b,c){F(c,function(c){d.a(a,b,c)})})}):d.m()?a.forEach(function(a,b){if(n(b))throw Error();b.forEach(function(b,c){f[0]=a;f[1]=b;e.has(f)||(F(c,function(c,e){d.a(a,b,e,c)}),f[0]=b,f[1]=a,e.set(f,1))})}):a.forEach(function(a,b){if(n(b))throw Error();
b.forEach(function(b,c){f[0]=a;f[1]=b;e.has(f)||(F(c,function(c){d.a(a,b,c)}),f[0]=b,f[1]=a,e.set(f,1))})}):d.m()&&!d.c()?a.forEach(function(a,b){if(n(b))throw Error();b.forEach(function(b,c){f[0]=a;f[1]=b;e.has(f)||(d.a(a,b,c),f[0]=b,f[1]=a,e.set(f,1))})}):a.forEach(function(a,b){if(n(b))throw Error();b.forEach(function(b,c){d.a(a,b,c)})});return d}v("jsnx.contrib.convert.from_map_of_maps",Jb);function Kb(a){if("function"==typeof a.N)return a.N();if(r(a))return a.split("");if(n(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Xa(a)};function Lb(a,b){this.e={};this.h=[];this.ca=this.I=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.ja(a)}h=Lb.prototype;h.fa=function(){return this.I};h.N=function(){Mb(this);for(var a=[],b=0;b<this.h.length;b++)a.push(this.e[this.h[b]]);return a};h.la=function(){Mb(this);return this.h.concat()};h.qa=function(a){return Nb(this.e,a)};h.ga=function(){return 0==this.I};
h.clear=function(){this.e={};this.ca=this.I=this.h.length=0};h.remove=function(a){return Nb(this.e,a)?(delete this.e[a],this.I--,this.ca++,this.h.length>2*this.I&&Mb(this),!0):!1};function Mb(a){if(a.I!=a.h.length){for(var b=0,c=0;b<a.h.length;){var d=a.h[b];Nb(a.e,d)&&(a.h[c++]=d);b++}a.h.length=c}if(a.I!=a.h.length){for(var e={},c=b=0;b<a.h.length;)d=a.h[b],Nb(e,d)||(a.h[c++]=d,e[d]=1),b++;a.h.length=c}}h.get=function(a,b){return Nb(this.e,a)?this.e[a]:b};
h.set=function(a,b){Nb(this.e,a)||(this.I++,this.h.push(a),this.ca++);this.e[a]=b};h.ja=function(a){var b;a instanceof Lb?(b=a.la(),a=a.N()):(b=Ya(a),a=Xa(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};h.ea=function(){return new Lb(this)};h.H=function(a){Mb(this);var b=0,c=this.h,d=this.e,e=this.ca,f=this,g=new A;g.b=function(){for(;;){if(e!=f.ca)throw Error("The map has changed since the iterator was created");if(b>=c.length)throw z;var g=c[b++];return a?g:d[g]}};return g};
function Nb(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function Ob(a){this.e=new Lb;a&&this.ja(a)}function Pb(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ga]||(a[ga]=++ha)):b.substr(0,1)+a}h=Ob.prototype;h.fa=function(){return this.e.fa()};h.add=function(a){this.e.set(Pb(a),a)};h.ja=function(a){a=Kb(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};h.remove=function(a){return this.e.remove(Pb(a))};h.clear=function(){this.e.clear()};h.ga=function(){return this.e.ga()};h.contains=function(a){return this.e.qa(Pb(a))};
h.p=function(a){var b=new Ob;a=Kb(a);for(var c=0;c<a.length;c++){var d=a[c];this.contains(d)&&b.add(d)}return b};h.M=function(a){var b=this.ea();a=Kb(a);for(var c=a.length,d=0;d<c;d++)b.remove(a[d]);return b};h.N=function(){return this.e.N()};h.ea=function(){return new Ob(this)};h.H=function(){return this.e.H(!1)};function Ib(a){if(null!=a)try{a.clear()}catch(b){throw Error("Input graph is not a jsnx graph type");}else a=new P;return a}
function Qb(a,b,c){var d=null;if(a.hasOwnProperty("adj"))try{return d=Jb(a.adj,b,a.m()),"graph"in a&&"object"===l(a.graph)&&(d.graph=bb(a.graph)),"node"in a&&a.node instanceof M&&(d.node=new M,a.node.forEach(function(a,b){d.node.set(a,bb(b))})),d}catch(e){throw e;}if(a instanceof M)try{return Jb(a,b,c)}catch(f){try{return Hb(a,b)}catch(g){throw Error("Input is not known type.");}}if("object"===l(a))try{return Rb(a,b,c)}catch(k){try{return Sb(a,b)}catch(p){throw Error("Input is not known type.");}}if(n(a))try{return Tb(a,
b)}catch(q){throw Error("Input is not valid edge list");}return d}v("jsnx.convert.to_networkx_graph",Qb);v("jsnx.to_networkx_graph",Qb);function Ub(a){return a.T()}v("jsnx.convert.convert_to_undirected",Ub);v("jsnx.convert_to_undirected",Ub);function Vb(a){return a.K()}v("jsnx.convert.convert_to_directed",Vb);v("jsnx.convert_to_undirected",Vb);function Wb(a,b){function c(a){return 0<=pa(b,a)}var d={};null!=b?b=R(b):(b=a,c=function(a){return b.n(a)});N(b,function(b){d[b]=qa(a.A(b),c)});return d}
v("jsnx.convert.to_dict_of_lists",Wb);v("jsnx.to_dict_of_lists",Wb);function Sb(a,b){var c=Ib(b);c.i(E(Db(a),function(a){return isNaN(a[0])?a[0]:+a[0]}));if(c.m()&&!c.c()){var d={};F(a,function(a,b){b=isNaN(b)?b:+b;x(a,function(a){a in d||c.a(b,a)});d[b]=1})}else{var e=[];F(a,function(a,b){b=isNaN(b)?b:+b;x(a,function(a){e.push([b,a])})});c.d(e)}return c}v("jsnx.convert.from_dict_of_lists",Sb);
v("jsnx.convert.to_dict_of_dicts",function(a,b,c){var d={};null!=b?(b=R(b),null!=c?x(b,function(e){d[e]={};F(a.get(e),function(a,g){0<=pa(b,g)&&(d[e][g]=c)})}):x(b,function(c){d[c]={};F(a.get(c),function(a,g){0<=pa(b,g)&&(d[c][g]=a)})})):null!=c?D(a.o(),function(a,b){d[b]=Va(a,function(){return c})}):D(a.o(),function(a,b){d[b]=bb(a)});return d});
function Rb(a,b,c){var d=Ib(b),e,f;d.i(E(Db(a),function(a){return isNaN(a[0])?a[0]:+a[0]}));c?d.c()?(d.m()?(e=[],F(a,function(a,b){if(n(a))throw Error();b=isNaN(b)?b:+b;F(a,function(a,c){c=isNaN(c)?c:+c;F(a,function(a,d){e.push([b,c,d,a])})})})):(e=[],F(a,function(a,b){if(n(a))throw Error();b=isNaN(b)?b:+b;F(a,function(a,c){c=isNaN(c)?c:+c;F(a,function(a){e.push([b,c,a])})})})),d.d(e)):d.m()?(f=new Ob,F(a,function(a,b){if(n(a))throw Error();b=isNaN(b)?b:+b;F(a,function(a,c){c=isNaN(c)?c:+c;f.contains([b,
c].toString())||(e=[],F(a,function(a,d){e.push([b,c,d,a])}),d.d(e),f.add([c,b].toString()))})})):(f=new Ob,F(a,function(a,b){if(n(a))throw Error();b=isNaN(b)?b:+b;F(a,function(a,c){c=isNaN(c)?c:+c;f.contains([b,c].toString())||(e=[],F(a,function(a){e.push([b,c,a])}),d.d(e),f.add([c,b].toString()))})})):d.m()&&!d.c()?(f=new Ob,F(a,function(a,b){if(n(a))throw Error();b=isNaN(b)?b:+b;F(a,function(a,c){c=isNaN(c)?c:+c;f.contains([b,c].toString())||(d.a(b,c,a),f.add([c,b].toString()))})})):(e=[],F(a,function(a,
b){if(n(a))throw Error();b=isNaN(b)?b:+b;F(a,function(a,c){c=isNaN(c)?c:+c;e.push([b,c,a])})}),d.d(e));return d}v("jsnx.convert.from_dict_of_dicts",Rb);v("jsnx.convert.to_edgelist",function(a,b){return null!=b?a.u(b,!0):a.u(null,!0)});function Tb(a,b){var c=Ib(b);c.d(a);return c}v("jsnx.convert.from_edgelist",Tb);function pb(a){var b=[];Xb(new Yb,a,b);return b.join("")}function Yb(){this.ia=void 0}
function Xb(a,b,c){switch(typeof b){case "string":Zb(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(da(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Xb(a,a.ia?a.ia.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),Zb(f,c),
c.push(":"),Xb(a,a.ia?a.ia.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var $b={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},ac=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Zb(a,b){b.push('"',a.replace(ac,function(a){if(a in $b)return $b[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return $b[a]=e+b.toString(16)}),'"')};function P(a,b){if(!(this instanceof P))return new P(a,b);this.graph={};this.node=new M;this.adj=new M;null!=a&&Qb(a,this);J(this.graph,b||{});this.edge=this.adj}v("jsnx.classes.Graph",P);v("jsnx.Graph",P);P.__name__="Graph";P.prototype.Ja=null;P.prototype.graph=P.prototype.Ja;P.prototype.node=null;P.prototype.node=P.prototype.node;P.prototype.Ca=null;P.prototype.adj=P.prototype.Ca;P.prototype.Ga=null;P.prototype.edge=P.prototype.Ga;
P.prototype.name=function(a){if(m(a))this.graph.name=a.toString();else return this.graph.name||""};P.prototype.name=P.prototype.name;P.prototype.toString=function(){return this.name()};P.prototype.toString=P.prototype.toString;P.prototype.get=function(a){try{return this.adj.get(a)}catch(b){if(!(b instanceof L))throw b;throw new L("Graph does not contain node "+a+".");}};P.prototype.get=P.prototype.get;
P.prototype.L=function(a,b){null!=b||(b={});if("object"!==l(b))throw new K("The attr_dict argument must be an object.");this.adj.has(a)?J(this.node.get(a),b):(this.adj.set(a,new M),this.node.set(a,b))};P.prototype.add_node=P.prototype.L;
P.prototype.i=function(a,b){null!=b||(b={});N(a,function(a){if(da(a)&&2===a.length&&fa(a[1])){var d=a[0];a=a[1];if(this.adj.has(d))d=this.node.get(d),J(d,b,a);else{this.adj.set(d,new M);var e=bb(b);J(e,a);this.node.set(d,e)}}else this.adj.has(a)?J(this.node.get(a),b):(this.adj.set(a,new M),this.node.set(a,bb(b)))},this)};P.prototype.add_nodes_from=P.prototype.i;
P.prototype.S=function(a){var b=this.adj;try{var c=this.adj.get(a).keys();this.node.remove(a);x(c,function(c){b.get(c).remove(a)});b.remove(a)}catch(d){if(!(d instanceof L))throw d;throw new K(na("The node %s is not in the graph",pb(a)));}};P.prototype.remove_node=P.prototype.S;P.prototype.aa=function(a){var b=this.adj;N(a,function(a){try{this.node.remove(a),b.get(a).forEach(function(d){b.get(d).remove(a)}),b.remove(a)}catch(d){if(!(d instanceof L))throw d;}},this)};
P.prototype.remove_nodes_from=P.prototype.aa;P.prototype.B=function(a){return a?B(this.node):B(this.adj.keys())};P.prototype.nodes_iter=P.prototype.B;P.prototype.nodes=function(a){return a?this.node.items():this.node.keys()};P.prototype.nodes=P.prototype.nodes;P.prototype.Q=function(){return this.adj.count()};P.prototype.number_of_nodes=P.prototype.Q;P.prototype.order=function(){return this.adj.count()};P.prototype.order=P.prototype.order;
P.prototype.n=function(a){try{return this.adj.has(a)}catch(b){if(b instanceof TypeError)return!1;throw b;}};P.prototype.has_node=P.prototype.n;P.prototype.a=function(a,b,c){c=c||{};if("object"!==l(c))throw new K("The attr_dict argument must be an object.");this.adj.has(a)||(this.adj.set(a,new M),this.node.set(a,{}));this.adj.has(b)||(this.adj.set(b,new M),this.node.set(b,{}));var d=this.adj.get(a).get(b,{});J(d,c);this.adj.get(a).set(b,d);this.adj.get(b).set(a,d)};P.prototype.add_edge=P.prototype.a;
P.prototype.d=function(a,b){b=b||{};if("object"!==l(b))throw new K("The attr_dict argument must be an object.");N(a,function(a){var d=vb(a),e;if(3===d)d=a[0],e=a[1],a=a[2];else if(2===d)d=a[0],e=a[1],a={};else throw new K(na("Edge tuple %s must be a 2-tuple or 3-tuple.",pb(a)));this.adj.has(d)||(this.adj.set(d,new M),this.node.set(d,{}));this.adj.has(e)||(this.adj.set(e,new M),this.node.set(e,{}));var f=this.adj.get(d).get(e,{});J(f,b,a);this.adj.get(d).set(e,f);this.adj.get(e).set(d,f)},this)};
P.prototype.add_edges_from=P.prototype.d;P.prototype.Ba=function(a,b,c){c=c||{};r(b)||(c=b,b="weight");this.d(Q(a,function(a){var c={};c[b]=a[2];if(!m(c[b]))throw new TypeError("Values must consist of three elements: "+pb(a));return[a[0],a[1],c]}),c)};P.prototype.add_weighted_edges_from=P.prototype.Ba;
P.prototype.v=function(a,b){try{this.adj.get(a).remove(b),fb(a)!==fb(b)&&this.adj.get(b).remove(a)}catch(c){if(c instanceof L)throw new K(na("The edge %s-%s is not in the graph",pb(a),pb(b)));throw c;}};P.prototype.remove_edge=P.prototype.v;P.prototype.J=function(a){N(a,function(a){var c=a[0];a=a[1];this.adj.has(c)&&this.adj.get(c).has(a)&&(this.adj.get(c).remove(a),fb(c)!==fb(a)&&this.adj.get(a).remove(c))},this)};P.prototype.remove_edges_from=P.prototype.J;
P.prototype.R=function(a,b){return this.adj.has(a)&&this.adj.get(a).has(b)};P.prototype.has_edge=P.prototype.R;P.prototype.A=function(a){try{return this.adj.get(a).keys()}catch(b){if(b instanceof L)throw new K(na("The node %s is not in the graph.",pb(a)));throw b;}};P.prototype.neighbors=P.prototype.A;P.prototype.Z=function(a){try{return B(this.adj.get(a).keys())}catch(b){if(b instanceof L)throw new K(na("The node %s is not in the graph.",pb(a)));throw b;}};P.prototype.neighbors_iter=P.prototype.Z;
P.prototype.u=function(a,b){return Na(this.g(a,b))};P.prototype.edges=P.prototype.u;
P.prototype.g=function(a,b){t(a)&&(b=a,a=null);var c=new M,d,e;d=null!=a?E(this.f(a),function(a){return[a,this.adj.get(a)]},this):B(this.adj);return b?W(d,function(a){e=a[0];var b=new A,d=B(a[1]);b.b=function(){try{return d.b()}catch(a){throw a===z&&c.set(e,1),a;}};return b},function(a){if(!c.has(a[0]))return[e,a[0],a[1]]}):W(d,function(a){e=a[0];var b=new A,d=B(a[1]);b.b=function(){try{return d.b()}catch(a){throw a===z&&c.set(e,1),a;}};return b},function(a){if(!c.has(a[0]))return[e,a[0]]})};
P.prototype.edges_iter=P.prototype.g;P.prototype.U=function(a,b,c){try{return this.adj.get(a).get(b)}catch(d){if(d instanceof L)return c;throw d;}};P.prototype.get_edge_data=P.prototype.U;P.prototype.Da=function(){return Na(E(this.o(),function(a){return a[1].keys()}))};P.prototype.adjacency_list=P.prototype.Da;P.prototype.o=function(){return B(this.adj)};P.prototype.adjacency_iter=P.prototype.o;P.prototype.s=function(a,b){return null!=a&&this.n(a)?this.t(a,b).b()[1]:new M(this.t(a,b))};
P.prototype.degree=P.prototype.s;P.prototype.t=function(a,b){var c;c=null!=a?E(this.f(a),function(a){return[a,this.adj.get(a)]},this):B(this.adj);return b?E(c,function(a){var c=a[0],f=a[1],g=0;f.forEach(function(a,c){g+=+I(c,b,1)});g+=+(f.has(c)&&I(f.get(c),b,1));a[1]=g;return a}):E(c,function(a){a[1]=a[1].count()+ +a[1].has(a[0]);return a})};P.prototype.degree_iter=P.prototype.t;P.prototype.clear=function(){this.name("");this.adj.clear();this.node.clear();Za(this.graph)};P.prototype.clear=P.prototype.clear;
P.prototype.copy=function(){return qb(this)};P.prototype.copy=P.prototype.copy;P.prototype.m=function(){return!1};P.prototype.is_multigraph=P.prototype.m;P.prototype.c=function(){return!1};P.prototype.is_directed=P.prototype.c;P.prototype.K=function(){var a=new Y;a.name(this.name());a.i(this);a.d(function(){var a;return W(this.o(),function(c){a=c[0];return B(c[1])},function(c){c[2]=X(c[1]);c[1]=c[0];c[0]=a;return c})}.call(this));a.graph=X(this.graph);a.node=X(this.node);return a};
P.prototype.to_directed=P.prototype.K;P.prototype.T=function(){return qb(this)};P.prototype.to_undirected=P.prototype.T;P.prototype.F=function(a){a=this.f(a);var b=new this.constructor,c=b.adj,d=this.adj;D(a,function(a){var b=new M;c.set(a,b);d.get(a).forEach(function(d,k){c.has(d)&&(b.set(d,k),c.get(d).set(a,k))})});N(b,function(a){b.node.set(a,this.node.get(a))},this);b.graph=this.graph;return b};P.prototype.subgraph=P.prototype.F;
P.prototype.Oa=function(){return ra(qa(this.adj.items(),function(a){return a[1].has(a[0])}),function(a){return a[0]})};P.prototype.nodes_with_selfloops=P.prototype.Oa;P.prototype.ba=function(a){return a?ra(qa(this.adj.items(),function(a){return a[1].has(a[0])}),function(a){a[2]=a[1].get(a[0]);a[1]=a[0];return a}):ra(qa(this.adj.items(),function(a){return a[1].has(a[0])}),function(a){a[1]=a[0];return a})};P.prototype.selfloop_edges=P.prototype.ba;P.prototype.Pa=function(){return this.ba().length};
P.prototype.number_of_selfloops=P.prototype.Pa;P.prototype.size=function(a){var b=y.sum.apply(null,this.s(null,a).values())/2;return null!=a?b:Math.floor(b)};P.prototype.size=P.prototype.size;P.prototype.P=function(a,b){return null!=a?this.adj.get(a).has(b)?1:0:Math.floor(this.size())};P.prototype.number_of_edges=P.prototype.P;P.prototype.Aa=function(a,b){var c=R(a),d=c[0],c=E(Ea(c,1),function(a){return[d,a]});this.d(c,b)};P.prototype.add_star=P.prototype.Aa;
P.prototype.za=function(a,b){var c=R(a),c=Ja(Ea(c,0,c.length-1),Ea(c,1));this.d(c,b)};P.prototype.add_path=P.prototype.za;P.prototype.ya=function(a,b){var c=R(a),c=Ja(c,za(Ea(c,1),[c[0]]));this.d(c,b)};P.prototype.add_cycle=P.prototype.ya;
P.prototype.f=function(a){return null!=a?this.n(a)?B([a]):function(a,c){var d=new A,e=W(a,function(a){if(c.has(a))return a});d.b=function(){try{return e.b()}catch(a){if(a instanceof TypeError)throw new K("nbunch is not a node or a sequence of nodes");throw a;}};return d}(a,this.adj):B(this.adj.keys())};P.prototype.nbunch_iter=P.prototype.f;function Y(a,b){if(!(this instanceof Y))return new Y(a,b);this.graph={};this.node=new M;this.adj=new M;this.pred=new M;this.succ=this.adj;null!=a&&Qb(a,this);J(this.graph,b||{});this.edge=this.adj}v("jsnx.classes.DiGraph",Y);v("jsnx.DiGraph",Y);ma(Y,P);Y.__name__="DiGraph";Y.prototype.Qa=null;Y.prototype.pred=Y.prototype.Qa;Y.prototype.Ta=null;Y.prototype.succ=Y.prototype.Ta;
Y.prototype.L=function(a,b){null!=b||(b={});if("object"!==l(b))throw new K("The attr_dict argument must be an object.");this.succ.has(a)?J(this.node.get(a),b):(this.succ.set(a,new M),this.pred.set(a,new M),this.node.set(a,b))};Y.prototype.add_node=Y.prototype.L;
Y.prototype.i=function(a,b){var c,d,e,f,g;null!=b||(b={});N(xb(a),function(a){c=!this.succ.has(a);da(a)&&2===a.length&&fa(a[1])?(d=a[0],e=a[1],this.succ.has(d)?(g=this.node.get(d),J(g,b,e)):(this.succ.set(d,new M),this.pred.set(d,new M),f=bb(b),J(f,e),this.node.set(d,f))):c?(this.succ.set(a,new M),this.pred.set(a,new M),this.node.set(a,bb(b))):J(this.node.get(a),b)},this)};Y.prototype.add_nodes_from=Y.prototype.i;
Y.prototype.S=function(a){var b;try{b=this.succ.get(a),this.node.remove(a)}catch(c){if(!(c instanceof L))throw c;throw new K(na("The node %s is not in the graph",pb(a)));}b.forEach(function(b){this.pred.get(b).remove(a)},this);this.succ.remove(a);this.pred.get(a).forEach(function(b){this.succ.get(b).remove(a)},this);this.pred.remove(a)};Y.prototype.remove_node=Y.prototype.S;
Y.prototype.aa=function(a){var b;N(a,function(a){this.succ.has(a)&&(b=this.succ.get(a),this.node.remove(a),b.forEach(function(b){this.pred.get(b).remove(a)},this),this.succ.remove(a),this.pred.get(a).forEach(function(b){this.succ.get(b).remove(a)},this),this.pred.remove(a))},this)};Y.prototype.remove_nodes_from=Y.prototype.aa;
Y.prototype.a=function(a,b,c){c=c||{};if("object"!==l(c))throw new K("The attr_dict argument must be an object.");this.succ.has(a)||(this.succ.set(a,new M),this.pred.set(a,new M),this.node.set(a,{}));this.succ.has(b)||(this.succ.set(b,new M),this.pred.set(b,new M),this.node.set(b,{}));var d=this.adj.get(a).get(b,{});J(d,c);this.succ.get(a).set(b,d);this.pred.get(b).set(a,d)};Y.prototype.add_edge=Y.prototype.a;
Y.prototype.d=function(a,b){b=b||{};if("object"!==l(b))throw new K("The attr_dict argument must be an object.");N(a,function(a){var d=vb(a),e;if(3===d)d=a[0],e=a[1],a=a[2];else if(2===d)d=a[0],e=a[1],a={};else throw new K("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple.");this.succ.has(d)||(this.succ.set(d,new M),this.pred.set(d,new M),this.node.set(d,{}));this.succ.has(e)||(this.succ.set(e,new M),this.pred.set(e,new M),this.node.set(e,{}));var f=this.adj.get(d).get(e,{});J(f,b,a);this.succ.get(d).set(e,
f);this.pred.get(e).set(d,f)},this)};Y.prototype.add_edges_from=Y.prototype.d;Y.prototype.v=function(a,b){try{this.succ.get(a).remove(b),this.pred.get(b).remove(a)}catch(c){if(c instanceof TypeError)throw new K(na("The edge %s-%s is not in the graph",pb(a),pb(b)));throw c;}};Y.prototype.remove_edge=Y.prototype.v;Y.prototype.J=function(a){N(a,function(a){var c=a[0];a=a[1];try{this.succ.get(c).remove(a),this.pred.get(a).remove(c)}catch(d){}},this)};Y.prototype.remove_edges_from=Y.prototype.J;
Y.prototype.La=function(a,b){return this.succ.has(a)&&this.succ.get(a).has(b)};Y.prototype.has_successor=Y.prototype.La;Y.prototype.Ka=function(a,b){return this.pred.has(a)&&this.pred.get(a).has(b)};Y.prototype.has_predecessor=Y.prototype.Ka;Y.prototype.oa=function(a){try{return E(this.succ.get(a),function(a){return a[0]})}catch(b){if(!(b instanceof L))throw b;throw new K("The node "+a+" is not in the digraph.");}};Y.prototype.successors_iter=Y.prototype.oa;
Y.prototype.va=function(a){try{return E(this.pred.get(a),function(a){return a[0]})}catch(b){if(!(b instanceof L))throw b;throw new K("The node "+a+" is not in the digraph.");}};Y.prototype.predecessors_iter=Y.prototype.va;Y.prototype.wa=function(a){try{return this.succ.get(a).keys()}catch(b){if(!(b instanceof L))throw b;throw new K("The node "+a+" is not in the digraph.");}};Y.prototype.successors=Y.prototype.wa;
Y.prototype.Ra=function(a){try{return this.pred.get(a).keys()}catch(b){if(!(b instanceof L))throw b;throw new K("The node "+a+" is not in the digraph.");}};Y.prototype.predecessors=Y.prototype.Ra;Y.prototype.A=Y.prototype.wa;Y.prototype.neighbors=Y.prototype.A;Y.prototype.Z=Y.prototype.oa;Y.prototype.neighbors_iter=Y.prototype.Z;
Y.prototype.g=function(a,b){t(a)&&(b=a,a=null);var c,d;if(null!=a){var e=[];c=Q(this.f(a),function(a){e[0]=a;e[1]=this.adj.get(a);return e},this)}else c=this.adj;return b?W(c,function(a){d=a[0];return B(a[1])},function(a){return[d,a[0],a[1]]}):W(c,function(a){d=a[0];return B(a[1])},function(a){return[d,a[0]]})};Y.prototype.edges_iter=Y.prototype.g;Y.prototype.ha=Y.prototype.g;Y.prototype.out_edges_iter=Y.prototype.ha;Y.prototype.ma=P.prototype.u;Y.prototype.out_edges=Y.prototype.ma;
Y.prototype.O=function(a,b){t(a)&&(b=a,a=null);var c,d;if(null!=a){var e=[];c=Q(this.f(a),function(a){e[0]=a;e[1]=this.pred.get(a);return e},this)}else c=this.pred;return b?W(c,function(a){d=a[0];return B(a[1])},function(a){a[2]=a[1];a[1]=d;return a}):W(c,function(a){d=a[0];return B(a[1])},function(a){a[1]=d;return a})};Y.prototype.in_edges_iter=Y.prototype.O;Y.prototype.W=function(a,b){return R(this.O(a,b))};Y.prototype.in_edges=Y.prototype.W;
Y.prototype.t=function(a,b){var c;c=null!=a?yb(E(this.f(a),function(a){return[a,this.succ.get(a)]},this),Q(this.f(a),function(a){return[a,this.pred.get(a)]},this)):yb(B(this.succ),B(this.pred));return r(b)?Q(c,function(a){var c=a[1][1],f=0;a[0][1].forEach(function(a,c){f+=+I(c,b,1)});c.forEach(function(a,c){f+=+I(c,b,1)});return[a[0][0],f]}):E(c,function(a){return[a[0][0],a[0][1].count()+a[1][1].count()]})};Y.prototype.degree_iter=Y.prototype.t;
Y.prototype.V=function(a,b){var c;c=null!=a?Q(this.f(a),function(a){return[a,this.pred.get(a)]},this):this.pred;return null!=b?Q(c,function(a){var c=0;a[1].forEach(function(a,d){c+=+I(d,b,1)});a[1]=c;return a}):Q(c,function(a){a[1]=a[1].count();return a})};Y.prototype.in_degree_iter=Y.prototype.V;
Y.prototype.$=function(a,b){var c;if(null!=a){var d=[];c=Q(this.f(a),function(a){d[0]=a;d[1]=this.succ.get(a);return d},this)}else c=B(this.succ);return null!=b?Q(c,function(a){var c=0;a[1].forEach(function(a,d){c+=+I(d,b,1)});return[a[0],c]}):Q(c,function(a){return[a[0],a[1].count()]})};Y.prototype.out_degree_iter=Y.prototype.$;Y.prototype.ra=function(a,b){return null!=a&&this.n(a)?this.V(a,b).b()[1]:new M(this.V(a,b))};Y.prototype.in_degree=Y.prototype.ra;
Y.prototype.ua=function(a,b){return null!=a&&this.n(a)?this.$(a,b).b()[1]:new M(this.$(a,b))};Y.prototype.out_degree=Y.prototype.ua;Y.prototype.clear=function(){this.succ.clear();this.pred.clear();this.node.clear();Za(this.graph)};Y.prototype.clear=Y.prototype.clear;Y.prototype.m=function(){return!1};Y.prototype.is_multigraph=Y.prototype.m;Y.prototype.c=function(){return!0};Y.prototype.is_directed=Y.prototype.c;Y.prototype.K=function(){return qb(this)};Y.prototype.to_directed=Y.prototype.K;
Y.prototype.T=function(a){var b=new P;b.name(this.name());b.i(this);var c=this.pred,d=[];a?b.d(W(this.o(),function(a){d[0]=a[0];return B(a[1])},function(a){if(c.get(d[0]).has(a[0]))return d[1]=a[0],d[2]=X(a[1]),d})):b.d(W(this.o(),function(a){d[0]=a[0];return B(a[1])},function(a){d[1]=a[0];d[2]=X(a[1]);return d}));b.graph=X(this.graph);b.node=X(this.node);return b};Y.prototype.to_undirected=Y.prototype.T;
Y.prototype.reverse=function(a){(a=!m(a)||a)?(a=new this.constructor(null,{name:"Reverse of ("+this.name()+")"}),a.i(this),a.d(Q(this.g(null,!0),function(a){var c=a[0];a[0]=a[1];a[1]=c;a[2]=X(a[2]);return a})),a.graph=X(this.graph),a.node=X(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};Y.prototype.reverse=Y.prototype.reverse;
Y.prototype.F=function(a){a=this.f(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;N(a,function(a){c.set(a,new M);d.set(a,new M)});c.forEach(function(a,b){e.get(a).forEach(function(e,p){c.has(e)&&(b.set(e,p),d.get(e).set(a,p))})});N(b,function(a){b.node.set(a,this.node.get(a))},this);b.graph=this.graph;return b};Y.prototype.subgraph=Y.prototype.F;function Z(a,b){if(!(this instanceof Z))return new Z(a,b);P.call(this,a,b)}ma(Z,P);v("jsnx.classes.MultiGraph",Z);v("jsnx.MultiGraph",Z);Z.__name__="MultiGraph";
Z.prototype.a=function(a,b,c,d){var e,f;null==c||r(c)||ea(c)||(d=c,c=null);d=d||{};if("object"!==l(d))throw new K("The attr_dict argument must be an object.");this.adj.has(a)||(this.adj.set(a,new M),this.node.set(a,{}));this.adj.has(b)||(this.adj.set(b,new M),this.node.set(b,{}));if(this.adj.get(a).has(b)){f=this.adj.get(a).get(b);if(null==c)for(c=G(f);c in f;)c+=1;e=I(f,""+c,{});J(e,d);f[c]=e}else null!=c||(c=0),e={},J(e,d),f=db(c,e),this.adj.get(a).set(b,f),this.adj.get(b).set(a,f)};
Z.prototype.add_edge=Z.prototype.a;Z.prototype.d=function(a,b){b=b||{};if("object"!==l(b))throw new K("The attr_dict argument must be an object.");N(a,function(a){var d=vb(a),e,f=null,g={};if(4===d)d=a[0],e=a[1],f=a[2],g=a[3];else if(3===d)d=a[0],e=a[1],g=a[2];else if(2===d)d=a[0],e=a[1];else throw new K("Edge tuple "+pb(a)+" must be a 2-tuple, 3-tuple or 4-tuple.");a=this.adj.has(d)?this.adj.get(d).get(e,{}):{};if(null==f)for(f=G(a);f in a;)f+=1;a=I(a,f,{});J(a,b,g);this.a(d,e,f,a)},this)};
Z.prototype.add_edges_from=Z.prototype.d;Z.prototype.v=function(a,b,c){var d;try{d=this.adj.get(a).get(b)}catch(e){if(!(e instanceof L))throw e;throw new K("The edge "+a+"-"+b+" is not in the graph");}if(null!=c){if(!(c in d))throw new K("The edge "+a+"-"+b+" with key "+c+" is not in the graph");ab(d,c)}else ab(d,Wa(d));0===G(d)&&(this.adj.get(a).remove(b),a!==b&&this.adj.get(b).remove(a))};Z.prototype.remove_edge=Z.prototype.v;
Z.prototype.J=function(a){N(a,function(a){try{this.v(a[0],a[1],a[2])}catch(c){if(!(c instanceof K))throw c;}},this)};Z.prototype.remove_edges_from=Z.prototype.J;Z.prototype.R=function(a,b,c){try{var d;if(null!=c){var e=this.adj.get(a).get(b);d=c in e}else d=this.adj.get(a).has(b);return d}catch(f){if(!(f instanceof L))throw f;return!1}};Z.prototype.has_edge=Z.prototype.R;Z.prototype.u=function(a,b,c){return Na(this.g(a,b,c))};Z.prototype.edges=Z.prototype.u;
Z.prototype.g=function(a,b,c){t(a)&&(t(b)&&(c=b),b=a,a=null);var d=new M,e,f;if(null!=a){var g=[];a=Q(this.f(a),function(a){g[0]=a;g[1]=this.adj.get(a);return g},this)}else a=B(this.adj);return b?W(a,function(a){e=a[0];var b=new A,c=B(a[1]);b.b=function(){try{return c.b()}catch(a){throw a===z&&d.set(e,!0),a;}};return b},function(a){f=a[0];if(!d.has(f))return Db(a[1])},function(a){return c?[e,f,a[0],a[1]]:[e,f,a[1]]}):W(a,function(a){e=a[0];var b=new A,c=B(a[1]);b.b=function(){try{return c.b()}catch(a){throw a===
z&&d.set(e,!0),a;}};return b},function(a){f=a[0];if(!d.has(f))return Db(a[1])},function(a){return c?[e,f,a[0]]:[e,f]})};Z.prototype.edges_iter=Z.prototype.g;Z.prototype.U=function(a,b,c,d){m(d)||(d=null);try{return null!=c?I(this.adj.get(a).get(b),""+c,d):this.adj.get(a).get(b)}catch(e){if(!(e instanceof L))throw e;return d}};Z.prototype.get_edge_data=Z.prototype.U;
Z.prototype.t=function(a,b){var c;if(null!=a){var d=[];c=Q(this.f(a),function(a){d[0]=a;d[1]=this.adj.get(a);return d},this)}else c=B(this.adj);return null!=b?E(c,function(a){var c=a[0];a=a[1];var d=0;a.forEach(function(a,c){F(c,function(a){d+=I(a,b,1)})});a.has(c)&&F(a.get(c),function(a){d+=I(a,b,1)});return[c,d]}):E(c,function(a){var b=a[0];a=a[1];var c=0;a.forEach(function(a,b){c+=G(b)});return[b,c+ +(a.has(b)&&G(a.get(b)))]})};Z.prototype.degree_iter=Z.prototype.t;Z.prototype.m=function(){return!0};
Z.prototype.is_multigraph=Z.prototype.m;Z.prototype.c=function(){return!1};Z.prototype.is_directed=Z.prototype.c;Z.prototype.K=function(){var a=new $;a.i(this);a.d(function(){var a,c;return W(this.o(),function(c){a=c[0];return B(c[1])},function(a){c=a[0];return Db(a[1])},function(d){return[a,c,d[0],X(d[1])]})}.call(this));a.graph=X(this.graph);a.node=X(this.node);return a};Z.prototype.to_directed=Z.prototype.K;
Z.prototype.ba=function(a,b){var c=[];a?b?this.adj.forEach(function(a,b){b.has(a)&&F(b.get(a),function(b,e){c.push([a,a,e,b])})}):this.adj.forEach(function(a,b){b.has(a)&&F(b.get(a),function(b){c.push([a,a,b])})}):b?this.adj.forEach(function(a,b){b.has(a)&&F(b.get(a),function(b,e){c.push([a,a,e])})}):this.adj.forEach(function(a,b){b.has(a)&&F(b.get(a),function(){c.push([a,a])})});return c};Z.prototype.selfloop_edges=Z.prototype.ba;
Z.prototype.P=function(a){if(null==a)return this.size();try{return G(this.adj.get(a).get(a))}catch(b){if(!(b instanceof L))throw b;return 0}};Z.prototype.number_of_edges=Z.prototype.P;Z.prototype.F=function(a){a=this.f(a);var b=new this.constructor,c=b.adj,d=this.adj;D(a,function(a){var b=new M;c.set(a,b);d.get(a).forEach(function(d,k){if(c.has(d)){var p=bb(k);b.set(d,p);c.get(d).set(a,p)}})});this.node.forEach(function(a,c){b.node.set(a,c)});b.graph=this.graph;return b};Z.prototype.subgraph=Z.prototype.F;function $(a,b){if(!(this instanceof $))return new $(a,b);Y.call(this,a,b)}ma($,Y);var bc=$.prototype,cc=Z.prototype,dc;for(dc in cc)cc.hasOwnProperty(dc)&&"constructor"!==dc&&(bc[dc]=cc[dc]);v("jsnx.classes.MultiDiGraph",$);v("jsnx.MultiDiGraph",$);$.__name__="MultiDiGraph";
$.prototype.a=function(a,b,c,d){var e,f;null==c||r(c)||ea(c)||(d=c,c=null);d=d||{};if("object"!==l(d))throw new K("The attr_dict argument must be an object.");this.succ.has(a)||(this.succ.set(a,new M),this.pred.set(a,new M),this.node.set(a,{}));this.succ.has(b)||(this.succ.set(b,new M),this.pred.set(b,new M),this.node.set(b,{}));if(this.succ.get(a).has(b)){f=this.adj.get(a).get(b);if(null==c)for(c=G(f);c in f;)c+=1;e=I(f,c.toString(),{});J(e,d);f[c]=e}else null!=c||(c=0),e={},J(e,d),f=db(c,e),this.succ.get(a).set(b,
f),this.pred.get(b).set(a,f)};$.prototype.add_edge=$.prototype.a;$.prototype.v=function(a,b,c){var d;try{d=this.adj.get(a).get(b)}catch(e){if(!(e instanceof L))throw e;throw new K("The edge "+a+"-"+b+" is not in the graph");}if(null!=c){if(!(c in d))throw new K("The edge "+a+"-"+b+" with key "+c+" is not in the graph");ab(d,c)}else ab(d,Wa(d));0===G(d)&&(this.succ.get(a).remove(b),this.pred.get(b).remove(a))};$.prototype.remove_edge=$.prototype.v;
$.prototype.g=function(a,b,c){t(a)&&(t(b)&&(c=b),b=a,a=null);var d,e;if(null!=a){var f=[];a=Q(this.f(a),function(a){f[0]=a;f[1]=this.adj.get(a);return f},this)}else a=B(this.adj);return b?W(a,function(a){d=a[0];return B(a[1])},function(a){e=a[0];return Db(a[1])},function(a){return c?[d,e,a[0],a[1]]:[d,e,a[1]]}):W(a,function(a){d=a[0];return B(a[1])},function(a){e=a[0];return Db(a[1])},function(a){return c?[d,e,a[0]]:[d,e]})};$.prototype.edges_iter=$.prototype.g;$.prototype.ha=$.prototype.g;
$.prototype.out_edges_iter=$.prototype.ha;$.prototype.ma=function(a,b,c){return Na(this.ha(a,b,c))};$.prototype.out_edges=$.prototype.ma;
$.prototype.O=function(a,b,c){t(a)&&(b=a,a=null);var d,e;if(null!=a){var f=[];a=Q(this.f(a),function(a){f[0]=a;f[1]=this.pred.get(a);return f},this)}else a=B(this.pred);return b?W(a,function(a){d=a[0];return B(a[1])},function(a){e=a[0];return Db(a[1])},function(a){return c?[e,d,a[0],a[1]]:[e,d,a[1]]}):W(a,function(a){d=a[0];return B(a[1])},function(a){e=a[0];return Db(a[1])},function(a){return c?[e,d,a[0]]:[e,d]})};$.prototype.in_edges_iter=$.prototype.O;
$.prototype.W=function(a,b,c){return Na(this.O(a,b,c))};$.prototype.in_edges=$.prototype.W;
$.prototype.t=function(a,b){var c;if(null!=a){var d=[],e=[];c=yb(E(this.f(a),function(a){d[0]=a;d[1]=this.succ.get(a);return d},this),E(this.f(a),function(a){e[0]=a;e[1]=this.pred.get(a);return e},this))}else c=yb(B(this.succ),B(this.pred));return null!=b?Q(c,function(a){var c=a[0][1],d=0;a[1][1].forEach(function(a,c){F(c,function(a){d+=+I(a,b,1)})});c.forEach(function(a,c){F(c,function(a){d+=+I(a,b,1)})});return[a[0][0],d]}):Q(c,function(a){var b=0,c=0;a[1][1].forEach(function(a,c){b+=G(c)});a[0][1].forEach(function(a,
b){c+=G(b)});return[a[0][0],b+c]})};$.prototype.degree_iter=$.prototype.t;$.prototype.V=function(a,b){var c;if(null!=a){var d=[];c=Q(this.f(a),function(a){d[0]=a;d[1]=this.pred.get(a);return d},this)}else c=B(this.pred);return null!=b?Q(c,function(a){var c=0;a[1].forEach(function(a,d){F(d,function(a){c+=+I(a,b,1)})});return[a[0],c]}):Q(c,function(a){var b=0;a[1].forEach(function(a,c){b+=G(c)});return[a[0],b]})};$.prototype.in_degree_iter=$.prototype.V;
$.prototype.$=function(a,b){var c;if(null!=a){var d=[];c=Q(this.f(a),function(a){d[0]=a;d[1]=this.succ.get(a);return d},this)}else c=B(this.succ);return null!=b?Q(c,function(a){var c=0;a[1].forEach(function(a,d){F(d,function(a){c+=+I(a,b,1)})});return[a[0],c]}):Q(c,function(a){var b=0;a[1].forEach(function(a,c){b+=G(c)});return[a[0],b]})};$.prototype.out_degree_iter=$.prototype.$;$.prototype.m=function(){return!0};$.prototype.is_multigraph=$.prototype.m;$.prototype.c=function(){return!0};
$.prototype.is_directed=$.prototype.c;$.prototype.K=function(){return qb(this)};$.prototype.to_directed=$.prototype.K;
$.prototype.T=function(a){var b=new Z;b.name(this.name());b.i(this);var c,d;a?b.d(W(this.o(),function(a){c=a[0];return B(a[1])},function(a){d=a[0];return Db(a[1])},la(function(a){if(this.R(d,c,a[0]))return[c,d,a[0],X(a[1])]},this))):b.d(W(this.o(),function(a){c=a[0];return B(a[1])},function(a){d=a[0];return Db(a[1])},function(a){return[c,d,a[0],X(a[1])]}));b.graph=X(this.graph);b.node=X(this.node);return b};$.prototype.to_undirected=$.prototype.T;
$.prototype.F=function(a){a=this.f(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;D(a,function(a){c.set(a,new M);d.set(a,new M)});c.forEach(function(a,b){e.get(a).forEach(function(e,p){if(c.has(e)){var q=bb(p);b.set(e,q);d.get(e).set(a,q)}})});this.node.forEach(function(a,c){b.node.set(a,c)});b.graph=this.graph;return b};$.prototype.subgraph=$.prototype.F;
$.prototype.reverse=function(a){(a=!m(a)||a)?(a=new this.constructor(null,{name:"Reverse of ("+this.name()+")"}),a.i(this),a.d(E(this.g(null,!0,!0),function(a){return[a[1],a[0],a[2],X(a[3])]})),a.graph=X(this.graph),a.node=X(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};$.prototype.reverse=$.prototype.reverse;function ec(a){return a.nodes()}v("jsnx.classes.func.nodes",ec);v("jsnx.nodes",ec);function fc(a){return a.B()}v("jsnx.classes.func.nodes_iter",fc);v("jsnx.nodes_iter",fc);function gc(a,b){return a.u(b)}v("jsnx.classes.func.edges",gc);v("jsnx.edges",gc);function hc(a,b){return a.g(b)}v("jsnx.classes.func.edges_iter",hc);v("jsnx.edges_iter",hc);v("jsnx.degree",function(a,b,c){return a.s(b,c)});function ic(a,b){return a.A(b)}v("jsnx.classes.func.neighbors",ic);v("jsnx.neighbors",ic);
function jc(a){return a.Q()}v("jsnx.classes.func.number_of_nodes",jc);v("jsnx.number_of_nodes",jc);function kc(a){return a.P()}v("jsnx.classes.func.number_of_edges",kc);v("jsnx.number_of_edges",kc);function lc(a){var b=a.Q(),c=a.P();return 0===c?0:a.c()?c/(b*(b-1)):2*c/(b*(b-1))}v("jsnx.classes.func.density",lc);v("jsnx.density",lc);function mc(a){a=a.s().values();var b=Math.max.apply(Math,a)+1,c=Ia(b);x(a,function(a){c[a]+=1});return c}v("jsnx.classes.func.degree_histogram",mc);
v("jsnx.degree_histogram",mc);function nc(a){return a.c()}v("jsnx.classes.func.is_directed",nc);v("jsnx.is_directed",nc);function oc(a){function b(){throw new K("Frozen graph can't be modified");}a.add_node=a.L=b;a.add_nodes_from=a.i=b;a.remove_node=a.S=b;a.remove_nodes_from=a.aa=b;a.add_edge=a.a=b;a.add_edges_from=a.d=b;a.remove_edge=a.v=b;a.remove_edges_from=a.J=b;a.clear=a.clear=b;a.frozen=a.Ha=!0;return a}v("jsnx.classes.func.freeze",oc);v("jsnx.freeze",oc);function pc(a){return!!a.Ha}
v("jsnx.classes.func.is_frozen",pc);v("jsnx.is_frozen",pc);function qc(a,b){return a.F(b)}v("jsnx.classes.func.subgraph",qc);v("jsnx.subgraph",qc);function rc(a,b){m(b)||(b=!0);var c=new a.constructor;b&&c.i(a);return c}v("jsnx.classes.func.create_empty_copy",rc);v("jsnx.create_empty_copy",rc);
function sc(a,b){var c="";if(null!=b){if(!a.n(b))throw new K("node "+b+" not in graph");c=c+("Node "+b+" has the following properties:\n")+("Degree: "+a.s(b)+"\n");c+="Neighbors: "+a.A(b).join(" ")}else{var c=c+("Name: "+a.name()+"\n"),c=c+("Type: "+a.constructor.__name__+"\n"),c=c+("Number of nodes: "+a.Q()+"\n"),c=c+("Number of edges: "+a.P()+"\n"),d=a.Q();if(0<d)if(a.c())c+="Average in degree: "+(y.sum.apply(null,a.ra().values())/d).toFixed(4)+"\n",c+="Average out degree: "+(y.sum.apply(null,a.ua().values())/
d).toFixed(4);else var e=y.sum.apply(null,a.s().values()),c=c+("Average degree: "+(e/d).toFixed(4))}return c}v("jsnx.classes.func.info",sc);v("jsnx.info",sc);function tc(a,b,c){F(c,function(c,e){a.node.get(e)[b]=c})}v("jsnx.classes.func.set_node_attributes",tc);v("jsnx.set_node_attributes",tc);function uc(a,b){var c=new M;a.node.forEach(function(a,e){b in e&&c.set(a,e[b])});return c}v("jsnx.classes.func.get_node_attributes",uc);v("jsnx.get_node_attributes",uc);
function vc(a,b,c){c.forEach(function(c,e){a.get(c[0]).get(c[1])[b]=e})}v("jsnx.classes.func.set_edge_attributes",vc);v("jsnx.set_edge_attributes",vc);function wc(a,b){var c=new M;F(a.u(null,!0),function(a){if(b in a[2]){var e=a[2][b];a.length=2;c.set(a,e)}});return c}v("jsnx.classes.func.get_edge_attributes",wc);v("jsnx.get_edge_attributes",wc);function xc(a,b){if(a.c())throw new K("triangles() is not defined for directed graphs.");if(null!=b&&a.n(b))return Math.floor(yc(a,b).b()[2]/2);var c=new M;D(yc(a,b),function(a){c.set(a[0],Math.floor(a[2]/2))});return c}v("jsnx.algorithms.cluster.triangles",xc);v("jsnx.triangles",xc);
function yc(a,b){if(a.m())throw new K("Not defined for multigraphs.");var c;c=null!=b?W(a.f(b),function(b){return[b,a.get(b)]}):B(a.adj);return E(c,function(b){var c=new O(b[1].keys()),f=0;c.remove(b[0]);D(c,function(b){var d=new O(a.get(b).keys());d.remove(b);f+=c.p(d).count()});return[b[0],c.count(),f]})}
function zc(a,b,c){if(a.m())throw new K("Not defined for multigraphs.");r(c)||(c="weight");var d;d=0===a.P()?1:zb(a.u(!0),function(a){return I(a[2],c,1)});b=null!=b?W(a.f(b),function(b){return[b,a.get(b)]}):B(a.adj);return E(b,function(b){var f=b[0],g=new O(b[1].keys());g.remove(f);var k=0,p=new O;D(g,function(b){var e=I(a.get(f).get(b),c,1)/d;p.add(b);var C=(new O(a.get(b).keys())).M(p);D(g.p(C),function(g){var p=I(a.get(b).get(g),c,1)/d;g=I(a.get(f).get(g),c,1)/d;k+=Math.pow(e*p*g,1/3)})});return[f,
g.count(),2*k]})}function Ac(a,b,c,d){2===arguments.length?r(b)?(c=b,b=null):t(b)&&(d=b,b=null):3===arguments.length&&t(c)&&(d=c,c=null);null!=d||(d=!0);var e=Bc(a,b,c).values();d||(e=qa(e,function(a){return 0<a}));return y.sum.apply(y,e)/e.length}v("jsnx.algorithms.cluster.average_clustering",Ac);v("jsnx.average_clustering",Ac);
function Bc(a,b,c){if(a.c())throw new K("Clustering algorithms are not defined for directed graphs.");c=null!=c?zc(a,b,c):yc(a,b);var d=new M;D(c,function(a){d.set(a[0],0===a[2]?0:a[2]/(a[1]*(a[1]-1)))});return null!=b&&a.n(b)?d.values()[0]:d}v("jsnx.algorithms.cluster.clustering",Bc);v("jsnx.clustering",Bc);function Cc(a){var b=0,c=0;D(yc(a),function(a){c+=a[1]*(a[1]-1);b+=a[2]});return 0===b?0:b/c}v("jsnx.algorithms.cluster.transitivity",Cc);v("jsnx.transitivity",Cc);
function Dc(a,b){var c=null!=b?a.f(b):xb(a),d=new M;D(c,function(b){d.set(b,0);var c=0;D(Ab(a.get(b).keys()),function(g){var k=g[0];g=g[1];var p=(new O(a.get(k).keys())).p(a.get(g).keys());p.remove(b);p=p.count();d.set(b,d.get(b)+p);var q=p+1;a.get(k).has(g)&&(q+=1);c+=(a.get(k).count()-q)*(a.get(g).count()-q)+p});0<c&&d.set(b,d.get(b)/c)});return null!=b&&a.n(b)?d.values()[0]:d}v("jsnx.algorithms.cluster.square_clustering",Dc);v("jsnx.square_clustering",Dc);function Ec(a){var b=-1,c=new M,d=new O;D(a.o(),function(a){var e=new O(a[1].keys());e.remove(a[0]);var f=e.count();f>b?(c.set(a[0],e),d=e,b=f):c.set(a[0],e)});var e=new O(c.keys()),f=e.M(d),g=new O,k=[],p=[];a=new A;a.b=function(){if(0===f.count()&&0===k.length)throw z;var a,s;if(0<f.count())a=B(f).b(),f.remove(a);else{var C=k.pop();e=C[0];g=C[1];f=C[2];p.pop();return this.b()}p.push(a);e.remove(a);g.add(a);var S=c.get(a),C=e.p(S),S=g.p(S);if(0===C.count()&&(0===S.count()&&(s=Aa(p)),p.pop(),s))return s;
if(0===S.count()&&1===C.count())return s=za(p,C.values()),p.pop(),s;var ka=C.count(),H=-1,ba,T;for(s=B(S);null!==(a=Qa(s,null))&&!(a=C.p(c.get(a)),T=a.count(),T>H&&(ba=a,H=T,H===ka)););if(H===ka)return p.pop(),this.b();b=-1;for(s=B(C);null!==(a=Qa(s,null))&&!(a=C.p(c.get(a)),T=a.count(),T>b&&(d=a,b=T,b===ka-1)););H>b&&(d=ba);k.push([e,g,f]);e=C;g=S;f=e.M(d);return this.b()};return a}v("jsnx.algorithms.clique.find_cliques",Ec);v("jsnx.find_cliques",Ec);
function Fc(a){var b=new M;D(a.o(),function(a){var c=new O(a[1].keys());c.remove(a[0]);b.set(a[0],c)});if(0===b.count())return[];a=new O(b.keys());var c=new O,d=[];Gc(b,a,c,[],d);return d}v("jsnx.algorithms.clique.find_cliques_recursive",Fc);v("jsnx.find_cliques_recursive",Fc);
function Gc(a,b,c,d,e){var f=-1,g=b.count(),k,p,q,s;for(p=B(c);null!==(q=Qa(p,null));)if(q=b.p(a.get(q)),s=q.count(),s>f&&(k=q,f=s,s===g))return;D(b,function(c){c=b.p(a.get(c));var d=c.count();d>f&&(k=c,f=d)});g=b.M(k);D(g,function(f){b.remove(f);d.push(f);var g=a.get(f);f=b.p(g);g=c.p(g);0===f.count()&&0===g.count()?e.push(Aa(d)):0===g.count()&&1===f.count()?e.push(za(d,f.values())):Gc(a,f,g,d,e);c.add(d.pop())})}
function Hc(a,b){null!=b||(b=Ec(a));var c=0;N(b,function(a){c=a.length>c?a.length:c});return c}v("jsnx.algorithms.clique.graph_clique_number",Hc);v("jsnx.graph_clique_number",Hc);function Ic(a,b){null!=b||(b=Ec(a));return R(b).length}v("jsnx.algorithms.clique.graph_number_of_cliques",Ic);v("jsnx.graph_number_of_cliques",Ic);
function Jc(a,b,c){c=null!=c?Na(c):Na(Ec(a));null!=b||(b=a.nodes());var d;if(da(b))d=new M,x(b,function(a){d.set(a,qa(c,function(b){return(new O(b)).has(a)}).length)});else{var e=b;d=qa(c,function(a){return(new O(a)).has(e)}).length}return d}v("jsnx.algorithms.clique.number_of_cliques",Jc);v("jsnx.number_of_cliques",Jc);function Kc(a,b){if(a.order()!=b.order())return!1;var c=a.s(),d=xc(a),e=Jc(a),f=[];c.forEach(function(a){f.push([c.get(a),d.get(a),e.get(a)])});f.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});var g=b.s(),k=xc(b),p=Jc(b),q=[];g.forEach(function(a){q.push([g.get(a),k.get(a),p.get(a)])});q.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});return Fa(f,q,function(a,b){return Fa(a,b)})?!0:!1}
v("jsnx.algorithms.isomorphism.could_be_isomorphic",Kc);v("jsnx.could_be_isomorphic",Kc);function Lc(a,b){if(a.order()!=b.order())return!1;var c=a.s(),d=xc(a),e=[];c.forEach(function(a){e.push([c.get(a),d.get(a)])});e.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});var f=b.s(),g=xc(b),k=[];f.forEach(function(a){k.push([f.get(a),g.get(a)])});k.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});return Fa(e,k,function(a,b){return Fa(a,b)})?!0:!1}
v("jsnx.algorithms.isomorphism.fast_could_be_isomorphic",Lc);v("jsnx.fast_could_be_isomorphic",Lc);function Mc(a,b){if(a.order()!=b.order())return!1;var c=a.s().values();c.sort();var d=b.s().values();d.sort();return Fa(c,d)?!0:!1}v("jsnx.algorithms.isomorphism.faster_could_be_isomorphic",Mc);v("jsnx.faster_could_be_isomorphic",Mc);function Nc(a,b){if("eg"===b)return Oc(a);if(null!=b&&"hh"!==b)throw new hb("`opt_method` must be 'eg' or 'hh'");return Pc(a)}v("jsnx.algorithms.graphical.is_valid_degree_sequence",Nc);v("jsnx.is_valid_degree_sequence",Nc);
function Pc(a){if(0===a.length)return!0;if(!Sa(a)||0>Math.min.apply(null,a)||0!==y.sum.apply(null,a)%2)return!1;for(a=Aa(a);0<a.length;){a.sort(Ha);if(0>a[0])break;var b=a.pop();if(0===b)return!0;if(b>a.length)break;for(var c=a.length-1,b=a.length-(b+1);c>b;c--)a[c]-=1}return!1}v("jsnx.algorithms.graphical.is_valid_degree_sequence_havel_hakimi",Pc);v("jsnx.is_valid_degree_sequence_havel_hakimi",Pc);
function Oc(a){if(0===a.length)return!0;if(!Sa(a)||0>Math.min.apply(null,a)||0!==y.sum.apply(null,a)%2)return!1;var b=a.length,c=Aa(a).sort(function(a,b){return b-a}),d=[],e;e=1;for(a=c.length;e<a;e++)c[e]<c[e-1]&&d.push(e);var f,g;e=0;for(a=d.length;e<a;e++)if(f=y.sum.apply(null,c.slice(0,d[e])),g=d[e]*(d[e]-1)+y.sum.apply(null,Na(E(V(d[e],b),function(a){return Math.min(d[e],c[a])}))),f>g)return!1;return!0}v("jsnx.algorithms.graphical.is_valid_degree_sequence_erdos_gallai",Oc);
v("jsnx.is_valid_degree_sequence_erdos_gallai",Oc);function Qc(a){try{return Rc(a),!0}catch(b){if(b instanceof kb)return!1;throw b;}}v("jsnx.algorithms.dag.is_directed_acyclic_graph",Qc);v("jsnx.is_directed_acyclic_graph",Qc);
function Rc(a,b){if(!a.c())throw new K("Topological sort not defined on undirected graphs.");var c=new O,d=[],e=new O;null!=b||(b=a.B());N(b,function(b){if(!e.has(b))for(b=[b];0<b.length;){var g=b[b.length-1];if(e.has(g))b.pop();else{c.add(g);var k=[];a.get(g).forEach(function(a){if(!e.has(a)){if(c.has(a))throw new kb("Graph contains a cycle");k.push(a)}});0<k.length?b.push.apply(b,k):(e.add(g),Ba(d,void 0,0,g))}}});return d}v("jsnx.algorithms.dag.topological_sort",Rc);v("jsnx.topological_sort",Rc);
function Sc(a,b){function c(a,b,d,e){b.add(e);a.get(e).forEach(function(e){if(!b.has(e)){if(!c(a,b,d,e))return!1}else if(b.has(e)&&!(0<=pa(d,e)))throw new kb("Graph contains a cycle");});Ba(d,void 0,0,e);return!0}if(!a.c())throw new K("Topological sort not defined on undirected graphs.");var d=new O,e=[];null!=b||(b=a.B());N(b,function(b){if(!(0<=pa(e,b)||c(a,d,e,b)))throw new kb("Graph contains a cycle");});return e}v("jsnx.algorithms.dag.topological_sort_recursive",Sc);
v("jsnx.topological_sort_recursive",Sc);var Uc=function Tc(b){if(!b.c())throw new K("is_aperiodic not defined for undirected graphs.");var c=b.B().b(),d=new M;d.set(c,0);for(var c=[c],e=0,f=1;0<c.length;){var g=[];x(c,function(c){b.get(c).forEach(function(b){d.has(b)?e=Fb(e,d.get(c)-d.get(b)+1):(g.push(b),d.set(b,f))})});c=g;f+=1}return d.count()===vb(b)?1===e:1===e&&Tc(b.F((new O(b.nodes())).M(d.keys())))};v("jsnx.algorithms.dag.is_aperiodic",Uc);v("jsnx.is_aperiodic",Uc);function Vc(a,b){this.ta=a;this.pa=b}Vc.prototype.getKey=function(){return this.ta};Vc.prototype.ea=function(){return new Vc(this.ta,this.pa)};function Wc(a){this.q=[];if(a)a:{var b,c;if(a instanceof Wc){if(b=a.la(),c=a.N(),0>=a.fa()){a=this.q;for(var d=0;d<b.length;d++)a.push(new Vc(b[d],c[d]));break a}}else b=Ya(a),c=Xa(a);for(d=0;d<b.length;d++)this.insert(b[d],c[d])}}h=Wc.prototype;h.insert=function(a,b){var c=this.q;c.push(new Vc(a,b));for(var c=c.length-1,d=this.q,e=d[c];0<c;){var f=c-1>>1;if(d[f].getKey()>e.getKey())d[c]=d[f],c=f;else break}d[c]=e};
h.remove=function(){var a=this.q,b=a.length,c=a[0];if(!(0>=b)){if(1==b)xa(a);else{a[0]=a.pop();for(var a=0,b=this.q,d=b.length,e=b[a];a<d>>1;){var f=2*a+1,g=2*a+2,f=g<d&&b[g].getKey()<b[f].getKey()?g:f;if(b[f].getKey()>e.getKey())break;b[a]=b[f];a=f}b[a]=e}return c.pa}};h.N=function(){for(var a=this.q,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].pa);return b};h.la=function(){for(var a=this.q,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getKey());return b};
h.qa=function(a){return wa(this.q,function(b){return b.getKey()==a})};h.ea=function(){return new Wc(this)};h.fa=function(){return this.q.length};h.ga=function(){return 0==this.q.length};h.clear=function(){xa(this.q)};function Xc(){Wc.call(this)}ma(Xc,Wc);function Yc(a,b){a.insert(0,b)};function Zc(a,b){null!=b||(b={});if("object"!==l(b))throw new K("The arg_dict argument must be an object.");var c=ub(a),d=a.nodes();"k"in b&&(Ka(d),d=d.slice(0,b.k));N(d.sort(),function(d){var f=[],f=null===I(b,"weight",null)?$c(a,d):ad(a,d,b.weight),g=f[0],k=f[1],f=f[2];c=I(b,"endpoints",!1)?bd(c,g,k,f,d):cd(c,g,k,f,d)});return c=dd(c,vb(a),I(b,"normalized",!0),a.c(),I(b,"k",null))}v("jsnx.algorithms.centrality.betweenness.betweenness_centrality",Zc);v("jsnx.betweenness_centrality",Zc);
function ed(a,b){null!=b||(b={});if("object"!==l(b))throw new K("The arg_dict argument must be an object.");var c=ub(a);D(a.g(),function(a){c.set(a,0)});var d=a.nodes();N(d.sort(),function(d){var f=[],f=null===I(b,"weight",null)?$c(a,d):ad(a,d,b.weight);c=fd(c,f[0],f[1],f[2],d)});N(d,function(a){c.remove(a)});return c=gd(c,vb(a),I(b,"normalized",!0),a.c())}v("jsnx.algorithms.centrality.betweenness.edge_betweenness_centrality",ed);v("jsnx.edge_betweenness_centrality",ed);
function $c(a,b){var c=[],d=new M;D(a.B(),function(a){d.set(a,[])});var e=ub(a),f=new M;e.set(b,1);f.set(b,0);for(var g=[b];0<g.length;){var k=g.shift();c.push(k);var p=f.get(k),q=e.get(k);x(a.A(k),function(a){f.has(a)||(g.push(a),f.set(a,p+1));f.get(a)===p+1&&(e.set(a,e.get(a)+q),d.get(a).push(k))})}return[c,d,e]}
function ad(a,b,c){var d=[],e=new M;N(a.nodes(),function(a){e.set(a,[])});var f=ub(a),g=new M;f.set(b,1);var k=new M;k.set(b,0);var p=new Xc;for(Yc(p,[b,b]);!p.ga();){var q=p.q[0]&&p.q[0].getKey();b=p.remove();var s=b[0],C=b[1];g.has(C)||(f.set(C,f.get(C)+f.get(s)),d.push(C),g.set(C,q),D(a.g(C,!0),function(a){var b=a[1];a=q+I(a[2],c,1);g.has(b)||k.has(b)&&!(a<k.get(b))?a===k.get(b)&&(f.set(b,f.get(b)+f.get(C)),e.get(b).push(C)):(k.set(b,a),p.insert(a,[C,b]),f.set(b,0),e.set(b,[C]))}))}return[d,e,
f]}function cd(a,b,c,d,e){for(var f=ub(b);0<b.length;){var g=b.pop(),k=(1+f.get(g))/d.get(g);x(c.get(g),function(a){f.set(a,f.get(a)+d.get(a)*k)});(g!==e||fa(g)&&g.toString()!==e.toString())&&a.set(g,a.get(g)+f.get(g))}return a}function bd(a,b,c,d,e){a.set(e,a.get(e)+b.length-1);for(var f=ub(b);0<b.length;){var g=b.pop(),k=(1+f.get(g))/d.get(g);x(c.get(g),function(a){f.set(a,f.get(a)+d.get(a)*k)});(g!==e||fa(g)&&g.toString()!==e.toString())&&a.set(g,a.get(g)+f.get(g)+1)}return a}
function fd(a,b,c,d,e){for(var f=ub(b);0<b.length;){var g=b.pop(),k=(1+f.get(g))/d.get(g);x(c.get(g),function(b){var c=d.get(b)*k,e=[b,g];a.has(e)||(e=[g,b]);a.set(e,a.get(e)+c);f.set(b,f.get(b)+c)});(g!==e||fa(g)&&g.toString()!==e.toString())&&a.set(g,a.get(g)+f.get(g))}return a}function dd(a,b,c,d,e){var f;t(c)&&c?2<b&&(f=1/((b-1)*(b-2))):t(d)&&!d&&(f=0.5);m(f)&&(null!=e&&(f=f*b/e),a.forEach(function(b,c){a.set(b,c*f)}));return a}
function gd(a,b,c,d){var e;t(c)&&c?1<b&&(e=1/(b*(b-1))):t(d)&&!d&&(e=0.5);m(e)&&a.forEach(function(b,c){a.set(b,c*e)});return a};function kd(a,b,c){var d=new M,e=0,f=new M;for(f.set(b,1);0<f.count();){b=f;f=new M;b.forEach(function(b){d.has(b)||(d.set(b,e),a.get(b).forEach(function(a){f.set(a,1)}))});if(ea(c)&&c<=e)break;e+=1}return d}v("jsnx.algorithms.shortest_paths.unweighted.single_source_shortest_path_length",kd);v("jsnx.single_source_shortest_path_length",kd);function ld(a,b){var c=new M;N(a,function(d){c.set(d,kd(a,d,b))});return c}v("jsnx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path_length",ld);
v("jsnx.all_pairs_shortest_path_length",ld);function md(a,b,c){c=nd(a,b,c);a=c[0];b=c[1];c=c[2];for(var d=[];null!=c;)d.push(c),c=b.get(c);for(c=a.get(d[0]);null!=c;)d.unshift(c),c=a.get(c);return d}v("jsnx.algorithms.shortest_paths.unweighted.bidirectional_shortest_path",md);v("jsnx.bidirectional_shortest_path",md);
function nd(a,b,c){if(!m(b)||!m(c))throw new hb("Bidirectional shortest path called without source or target");var d=new M,e=new M;if(c===b)return d.set(c,null),e.set(b,null),[d,e,b];var f,g;a.c()?(f=a.va,g=a.oa):g=f=a.Z;d.set(b,null);e.set(c,null);for(var k=[b],p=[c],q,s;0<k.length&&0<p.length&&!s;)k.length<=p.length?(q=k,k=[],x(q,function(b){s||D(g.call(a,b),function(a){s||(d.has(a)||(k.push(a),d.set(a,b)),e.has(a)&&(s=[d,e,a]))})})):(q=p,p=[],x(q,function(b){s||D(f.call(a,b),function(a){s||(e.has(a)||
(e.set(a,b),p.push(a)),d.has(a)&&(s=[d,e,a]))})}));if(s)return s;throw new lb("No path between "+b+" and "+c+".");}function od(a,b,c){var d=0,e=new M([[b,1]]),f=new M([[b,[b]]]);if(0===c)return f;for(;0<e.count()&&!(b=e,e=new M,b.forEach(function(b){a.get(b).forEach(function(a){f.has(a)||(f.set(a,f.get(b).concat([a])),e.set(a,1))})}),d+=1,m(c)&&c<=d););return f}v("jsnx.algorithms.shortest_paths.unweighted.single_source_shortest_path",od);v("jsnx.single_source_shortest_path",od);
function pd(a,b){var c=new M;N(a,function(d){c.set(d,od(a,d,b))});return c}v("jsnx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path",pd);v("jsnx.all_pairs_shortest_path",pd);
function qd(a,b,c,d,e){for(var f=0,g=[b],k=new M([[b,f]]),p=new M([[b,[]]]);0<g.length&&!(f+=1,b=g,g=[],x(b,function(b){a.get(b).forEach(function(a){k.has(a)?k.get(a)===f&&p.get(a).push(b):(p.set(a,[b]),k.set(a,f),g.push(a))})}),null!=d&&d<=f););return null!=c?e?p.has(c)?[p.get(c),k.get(c)]:[[],-1]:p.has(c)?p.get(c):[]:e?[p,k]:p}v("jsnx.algorithms.shortest_paths.unweighted.predecessor",qd);v("jsnx.predecessor",qd);var rd,sd=null,td="add_node add_nodes_from add_edge add_edges_from remove_node remove_nodes_from remove_edge remove_edges_from clear".split(" ");
v("jsnx.draw",function(a,b,c){function d(){sa.j.attr("transform",function(a){return["translate(",a.x,",",a.y,")scale(",U,")"].join("")});hd()}t(b)&&(c=b,b=null);b=b||sd||{};var e=b.d3||window.d3,f={};Cb(f,ud,b);sd=b;if(!e)throw Error("D3 requried for draw()");if(null==f.element&&null==rd)throw Error("Output element required for draw()");rd=I(f,"element",rd);e.select(rd).select("svg.jsnx").remove();var g=e.select(rd),k=g.append("svg").classed("jsnx",!0).attr("pointer-events","all"),p=k.append("g");
b=p.append("g").classed("edges",!0).selectAll("g.edge");var q=p.append("g").classed("nodes",!0).selectAll("g.node"),s=(f.layout||e.layout.force)(),C=f.width||parseInt(g.style("width"),10),S=f.height||parseInt(g.style("height"),10),ka=f.layout_attr,g=f.nodelist||null,H,ba,T,id=a.c(),ta=f.weighted,sa={j:q,l:b};if(f.with_labels){var Ca=f.labels;H="object"===l(Ca)?function(a){return I(Ca,a.node,"")}:u(Ca)?Ca:r(Ca)?function(a){return a.data[Ca]}:function(a){return a.node}}f.labels=H;if(ta){var Oa=f.weights;
T="object"===l(Oa)?function(a){return I(Oa,a.node,1)}:u(Oa)?Oa:r(Oa)?function(a){return I(a.data,Oa,1)}:function(){return 1}}if(f.with_edge_labels){var Pa=f.edge_labels;ba=ta&&!m(Pa)?T:"object"===l(Pa)?function(a){return I(Ca,a.node,"")}:u(Pa)?Pa:r(Pa)?function(a){return a.data[Pa]}:function(a){return a.edge};f.edge_labels=ba}if(ta&&f.weighted_stroke){var ta=La(a.g(null,!0),function(a,b){b=T({data:b[2]});return a>b?a:b}),ae=e.scale.linear().range([2,f.edge_style["stroke-width"]]).domain([0,ta]);f.edge_style["stroke-width"]=
function(a){return ae(T.call(this,a))}}k.select("svg.jsnx").remove();k.attr("width",C+"px").attr("height",S+"px").style("opacity",1E-6).transition().duration(1E3).style("opacity",1);var be={size:!0,nodes:!0,links:!0,start:!0};N(ka,function(a){if(!(a in be)&&u(s[a]))s[a](ka[a])});s.nodes([]).links([]).size([C,S]);var $a=1,U=1;if(f.pan_zoom.enabled){var jd=f.pan_zoom.scale;(function(){var a=!1,b=1,c=$a;k.call(e.behavior.zoom().on("zoom",function(){var f=e.event.sourceEvent.shiftKey;(f=jd&&f||!(jd||
f))&&!a?(b=e.event.scale,c=$a,a=!0):!f&&a&&(a=!1);$a=f?e.event.scale/b*c:$a;U=f?U:$a/e.event.scale;f=e.event.translate;p.attr("transform","translate("+f[0]+","+f[1]+")scale("+e.event.scale+")");d()}))})()}var hd=ca,Da=f.edge_offset,rb=f.node_attr.r,sb=f.node_style["stroke-width"];"circle"===f.node_shape?(u(rb)||(rb=function(){return f.node_attr.r}),u(sb)||(sb=function(){return f.node_style["stroke-width"]}),Da=function(a){return[rb(a.source)+sb(a.source),rb(a.target)+sb(a.target)]}):(da(Da)&&(Da=
function(){return f.edge_offset}),ea(Da)&&(Da=function(){return[f.edge_offset,f.edge_offset]}));var oa=f.edge_style["stroke-width"];u(oa)||(oa=function(){return f.edge_style["stroke-width"]});var ua=f.edge_label_offset,tb=f.edge_len;u(tb)||(tb=function(){return f.edge_len});hd=id?function(){sa.l.each(function(a){var b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,k=a.target.y,p=y.angle(c,d,g,k),g=Math.sqrt(Math.pow(g-c,2)+Math.pow(k-d,2))*tb(a),k=Da(a),q=oa(a)*U,s=1/U,k=[k[0]*U,k[1]*U];if(a.source===
a.target){var q=g/2,H=90<p&&279>p;b.attr("transform",["translate(",c,",",d,")rotate(",p,")"].join(""));b.select(".line").attr("d",e.svg.line().interpolate("bundle")([[0,-k[0]/2],[20,-k[0]/2-45],[-20,-k[0]/2-45],[0,-k[0]/2]]));b.select(".line").style("stroke-width",oa(a)/2*U);f.with_edge_labels&&b.select("text").attr("x",(H?1:-1)*ua.x*s+k[0]+(g*s-k[0]-k[1])/2).attr("y",-oa(a)/4+-ua.y*s+k[0]/2-45).attr("transform","scale("+U+")"+(H?"rotate(180,"+1/U*q+",0)":""))}else b.attr("transform",["translate(",
c,",",d,")rotate(",p,")"].join("")),c=g-k[1]-2*q,d=q/2,b.select(".line").attr("d",["M",k[0],0,"L",k[0],-d,"L",c,-d,"L",c,-q,"L",g-k[1],0,"z"].join(" ")),b.select("text").attr("x",ua.x*s+k[0]+(g*s-k[0]-k[1])/2).attr("y",-oa(a)/2+-ua.y*s).attr("transform","scale("+U+")")})}:function(){sa.l.each(function(a){var b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,k=a.target.y,p=y.angle(c,d,g,k),g=Math.sqrt(Math.pow(g-c,2)+Math.pow(k-d,2))*tb(a),k=g/2,q=Da(a),q=[q[0]*U,q[1]*U],s=1/U,H=oa(a)*U,ka=90<
p&&279>p;a.source===a.target?(b.attr("transform",["translate(",c,",",d,")rotate(",p,")"].join("")),b.select(".line").attr("d",e.svg.line().interpolate("bundle")([[0,-q[0]/2],[20,-q[0]/2-45],[-20,-q[0]/2-45],[0,-q[0]/2]])),b.select(".line").style("stroke-width",oa(a)/2*U),f.with_edge_labels&&b.select("text").attr("x",(ka?1:-1)*ua.x*s+q[0]+(g*s-q[0]-q[1])/2).attr("y",-oa(a)/4+-ua.y*s+q[0]/2-45).attr("transform","scale("+U+")"+(ka?"rotate(180,"+1/U*k+",0)":""))):(b.attr("transform",["translate(",c,",",
d,")rotate(",p,")"].join("")),b.select(".line").attr("d",["M",q[0],H/4,"L",q[0],-H/4,"L",g-q[1],-H/4,"L",g-q[1],H/4,"z"].join(" ")),f.with_edge_labels&&b.select("text").attr("x",(ka?1:-1)*ua.x*s+q[0]+(g*s-q[0]-q[1])/2).attr("y",-oa(a)/4+-ua.y*s).attr("transform","scale("+U+")"+(ka?"rotate(180,"+1/U*k+",0)":"")))})};s.on("tick",d);C=a.B();S=a.g();g&&(c=!1,C=a.f(g),S=a.g(g));sa.j=vd(a,C,s,q,f.node_shape,H);sa.l=wd(a,S,s,b,ba);xd(sa.j,{attr:f.node_attr,style:f.node_style,Y:f.label_style,X:f.label_attr},
f.with_labels);yd(sa.l,{attr:f.edge_attr,style:f.edge_style,Y:f.edge_label_style,X:f.edge_label_attr},f.with_edge_labels,null,id);c?zd(a,s,f,sa):a.bound?Ad(a):Bd(a);s.start();return s});
function vd(a,b,c,d,e,f){var g=c.nodes();N(b,function(b){var c=a.node.get(b);b={node:b,data:c,G:a};g.push(b);c.__d3datum__=b});d=d.data(g,Cd);b=c.drag().on("dragstart",function(){d3.event.sourceEvent.stopPropagation()});b=d.enter().append("g").classed("node",!0).call(b);b.append(e).classed("node-shape",!0);f&&b.append("text").text(f);return d}
function wd(a,b,c,d,e){var f=c.links();N(b,function(b){var c=b[0],d=b[1];b=b[2]||a.U(c,d);c={edge:[c,d],redge:[d,c],source:a.node.get(c).__d3datum__,target:a.node.get(d).__d3datum__,data:b,G:a};f.push(c);b.__d3datum__=c});d=d.data(f,Dd);b=d.enter().append("g").classed("edge",!0);b.append("path").classed("line",!0);e&&b.append("text").text(e);return d}
function xd(a,b,c,d){if(null!=d){var e={};N(d,function(a){e[n(a)?a[0]:a]=!0});a=a.filter(function(a){return a.node in e})}var f=a.selectAll(".node-shape");F(b.attr,function(a,b){f.attr(b,a)});F(b.style,function(a,b){f.style(b,a)});if(c){var g=a.selectAll("text");F(b.X,function(a,b){g.attr(b,a)});F(b.Y,function(a,b){g.style(b,a)})}}
function yd(a,b,c,d,e){if(null!=d){var f={};N(d,function(a){f[[a[0],a[1]]]=!0});a=a.filter(function(a){return a.edge in f||e||a.redge in f})}var g=a.selectAll(".line");F(b.attr,function(a,b){g.attr(b,a)});F(b.style,function(a,b){"stroke-width"!=b&&g.style(b,a)});g.style("stroke-width",0);d=a.filter(function(a){return a.source===a.target}).selectAll(".line");d.style("fill","none");d.style("stroke",b.style.fill);if(c){var k=a.selectAll("text");F(b.X,function(a,b){k.attr(b,a)});F(b.Y,function(a,b){k.style(b,
a)})}}function Cd(a){return a.node}function Dd(a){return a.edge}function Ed(a,b,c,d){var e=c.nodes();N(a.f(b),function(b){ya(e,a.node.get(b).__d3datum__)});d=d.data(e,Cd);d.ka().remove();return d}function Fd(a,b,c,d){var e=c.links();N(b,function(b){ya(e,I(a.U(b[0],b[1],{}),"__d3datum__",null))});d=d.data(e,Dd);d.ka().remove();return d}
function zd(a,b,c,d){Ad(a,!1);var e=a.constructor.prototype,f=c.node_shape,g={attr:c.node_attr,style:c.node_style,X:c.label_attr,Y:c.label_style},k={attr:c.edge_attr,style:c.edge_style,X:c.edge_label_attr,Y:c.edge_label_style},p=c.labels,q=c.edge_labels,s=c.with_labels,C=c.with_edge_labels,S=a.c();a.add_node=a.L=function(a){var c=!this.n(a);e.add_node.apply(this,arguments);c&&(d.j=vd(this,[a],b,d.j,f,p));xd(d.j,g,s,[a]);b.start()};a.add_nodes_from=a.i=function(a){var c=qa(R(a),function(a){return!this.n(n(a)?
a[0]:a)},this);e.add_nodes_from.apply(this,arguments);0<c.length&&(d.j=vd(this,c,b,d.j,f,p));xd(d.j,g,s,a);b.start()};a.add_edge=a.a=function(c,H){var ba=!this.R(c,H),T=[];ba&&(T=qa(c==H?[c]:[c,H],function(a){return!this.n(a)},this));e.add_edge.apply(a,arguments);0<T.length&&(d.j=vd(this,T,b,d.j,f,p),xd(d.j,g,s,T));ba&&(d.l=wd(this,[[c,H]],b,d.l,q));yd(d.l,k,C,[[c,H]],S);b.start()};a.add_edges_from=a.d=function(c){var H=[],ba=[],T={},S={},ta=this.c();N(c,function(a){var b=a[0];a=a[1];var c;(c=this.R(b,
a))||(c=[b,a]in T)||!(c=!ta)||(c=[a,b]in T);c||(H.push([b,a]),T[[b,a]]=!0,this.n(b)||b in S||(ba.push(b),S[b]=!0),this.n(a)||a in S||(ba.push(a),S[a]=!0))},this);e.add_edges_from.apply(a,arguments);0<ba.length&&(d.j=vd(this,ba,b,d.j,f,p),xd(d.j,g,s,ba));0<H.length&&(d.l=wd(this,H,b,d.l,q));yd(d.l,k,C,H,ta);b.start()};a.remove_node=a.S=function(c){try{if(this.n(c)){d.j=Ed(this,[c],b,d.j);var f=this.g([c]);this.c()&&(f=Ma(f,this.O([c])));d.l=Fd(this,f,b,d.l);b.resume()}}catch(g){}e.remove_node.apply(a,
arguments)};a.remove_nodes_from=a.aa=function(c){try{d.j=Ed(this,c,b,d.j);var f=this.g(c);this.c()&&(f=Ma(f,this.O(c)));d.l=Fd(this,f,b,d.l);b.resume()}catch(g){}e.remove_nodes_from.apply(a,arguments)};a.remove_edge=a.v=function(c,f){try{d.l=Fd(this,[[c,f]],b,d.l),b.resume()}catch(g){}e.remove_edge.apply(a,arguments)};a.remove_edges_from=a.J=function(c){try{d.l=Fd(this,c,b,d.l),b.resume()}catch(f){}e.remove_edges_from.apply(a,arguments)};a.clear=a.clear=function(){d.j=d.j.data([],Cd);d.j.ka().remove();
d.l=d.l.data([],Dd);d.l.ka().remove();b.nodes([]).links([]).resume();e.clear.apply(a,arguments)};a.bound=!0}v("jsnx.is_bound",function(a){return a.bound});function Ad(a,b){if(a.bound){var c=a.constructor.prototype;x(td,function(b){a[b]=c[b]});delete a.bound;m(b)&&!b||Bd(a)}}v("jsnx.unbind",Ad);function Bd(a){N(a.B(!0),function(a){ab(a[1],"__d3datum__")});N(a.g(null,!0),function(a){ab(a[2],"__d3datum__")})}
var ud={layout_attr:{charge:-120,linkDistance:60},node_shape:"circle",node_attr:{r:10},node_style:{"stroke-width":2,stroke:"#333",fill:"#999",cursor:"pointer"},edge_len:1,edge_attr:{},edge_style:{fill:"#000","stroke-width":3},label_attr:{},label_style:{"text-anchor":"middle","dominant-baseline":"central",cursor:"pointer","-webkit-user-select":"none",fill:"#000"},edge_label_attr:{},edge_label_style:{"font-size":"0.8em","text-anchor":"middle","-webkit-user-select":"none"},edge_label_offset:{x:0,y:0.5},
with_labels:!1,with_edge_labels:!1,edge_offset:10,weighted:!1,weights:"weight",weighted_stroke:!0,pan_zoom:{enabled:!0,scale:!0}};function Gd(a,b){var c=V(a),d,e,f=new A;try{e=[c.b()]}catch(g){if(g!==z)throw g;return f}f.b=function(){if(0===e.length)throw z;return e.splice(0,1)[0]};return W(f,function(a){d=a;return V(b)},function(){try{var a=c.b();e.push(a);return[d,a]}catch(b){if(b!==z)throw b;}})}function Hd(a,b,c){c=Id(b,c);c.d(Gd(b,a));return c}v("jsnx.generators.classic.full_rary_tree",Hd);v("jsnx.full_rary_tree",Hd);function Jd(a,b,c){b=1===a?2:Math.floor((1-Math.pow(a,b+1))/(1-a));c=Id(b,c);c.d(Gd(b,a));return c}
v("jsnx.generators.classic.balanced_tree",Jd);v("jsnx.balanced_tree",Jd);function Kd(a,b){var c=Id(a,b);c.name("complete_graph("+a+")");1<a&&c.d(c.c()?Bb(V(a)):Ab(V(a)));return c}v("jsnx.generators.classic.complete_graph",Kd);v("jsnx.complete_graph",Kd);function Ld(a,b){var c=Md(a,b);c.name("cycle_graph("+a+")");1<a&&c.a(a-1,0);return c}v("jsnx.generators.classic.cycle_graph",Ld);v("jsnx.cycle_graph",Ld);
function Id(a,b){a instanceof P&&(b=a,a=null);null!=a||(a=0);var c;null!=b?(c=b,c.clear()):c=new P;c.i(V(a));c.name("empty_graph("+a+")");return c}v("jsnx.generators.classic.empty_graph",Id);v("jsnx.empty_graph",Id);
function Nd(a,b,c,d){var e=Id(0,d);e.name("grid_2d_graph");d=Na(V(a));var f=Na(V(b));x(d,function(a){x(f,function(b){e.L([a,b])})});D(V(1,a),function(a){x(f,function(b){e.a([a,b],[a-1,b])})});x(d,function(a){D(V(1,b),function(b){e.a([a,b],[a,b-1])})});e.c()&&(D(V(0,a-1),function(a){x(f,function(b){e.a([a,b],[a+1,b])})}),x(d,function(a){D(V(0,b-1),function(b){e.a([a,b],[a,b+1])})}));c&&(2<b&&(x(d,function(a){e.a([a,0],[a,b-1])}),e.c()&&x(d,function(a){e.a([a,b-1],[a,0])})),2<a&&(x(f,function(b){e.a([0,
b],[a-1,b])}),e.c()&&x(f,function(b){e.a([a-1,b],[0,b])})),e.name("periodic_grid_2d_graph("+a+","+b+")"));return e}v("jsnx.generators.classic.grid_2d_graph",Nd);v("jsnx.grid_2d_graph",Nd);function Od(a){a=Id(0,a);a.name("null_graph()");return a}v("jsnx.generators.classic.null_graph",Od);v("jsnx.null_graph",Od);function Md(a,b){var c=Id(a,b);c.name("path_graph("+a+")");c.d(E(V(a-1),function(a){return[a,a+1]}));return c}v("jsnx.generators.classic.path_graph",Md);v("jsnx.path_graph",Md);
function Pd(a){a=Id(1,a);a.name("null_graph()");return a}v("jsnx.generators.classic.trivial_graph",Pd);v("jsnx.trivial_graph",Pd);function Qd(a,b,c){null!=c||(c=!1);var d=Id(a);d.name("fast_gnp_random_graph("+a+","+b+")");if(0>=b||1<=b)return Rd(a,b,c);var e=1,f=-1;b=Math.log(1-b);if(c)for(d=new Y(d);e<a;){c=Math.log(1-Math.random());f=f+1+Math.floor(c/b);for(e===f&&(f+=1);f>=a&&e<a;)f-=a,e+=1,e==f&&(f+=1);e<a&&d.a(e,f)}else for(;e<a;){c=Math.log(1-Math.random());for(f=f+1+Math.floor(c/b);f>=e&&e<a;)f-=e,e+=1;e<a&&d.a(e,f)}return d}v("jsnx.generators.random_graphs.fast_gnp_random_graph",Qd);v("jsnx.fast_gnp_random_graph",Qd);
function Rd(a,b,c){var d;d=c?new Y:new P;d.i(V(a));d.name("gnp_random_graph("+a+","+b+")");if(0>=b)return d;if(1<=b)return Kd(a,d);a=d.c()?Bb(V(a)):Ab(V(a));D(a,function(a){Math.random()<b&&d.a(a[0],a[1])});return d}v("jsnx.generators.random_graphs.gnp_random_graph",Rd);v("jsnx.gnp_random_graph",Rd);v("jsnx.binomial_graph",Rd);v("jsnx.erdos_renyi_graph",Rd);function Sd(a,b){if(!Nc(a))throw new K("Invalid degree sequence");if(null!=b){if(b.c())throw new K("Directed Graph not supported");if(b.m())throw new K("Havel-Hakimi requires simple graph");}var c=a.length,d=Id(c,b);if(0===c||0===Math.max.apply(null,a))return d;for(c=Na(Q(d,function(b){return[a[b],b]}));0<c.length;){c.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:+a[1]-+b[1]});if(0>c[0][0])return!1;var e=c.pop();if(0===e[0])break;if(e[0]>c.length)return!1;for(var f=c.length,g=f-e[0];g<f;g++)d.a(e[1],
c[g][1]),c[g][0]-=1}d.name("havel_hakimi_graph "+d.order()+" nodes "+d.size()+" edges");return d}v("jsnx.generators.degree_seq.havel_hakimi_graph",Sd);v("jsnx.havel_hakimi_graph",Sd);function Td(){var a=new P;a.i(V(34));a.name("Zachary's Karate Club");var b=0;x("0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0;1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0;1 1 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0;1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1;0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1;0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1;0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1;1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1;0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0 0 1 1 1 0 1;0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0".split(";"),
function(c){N(c.split(" "),function(c,e){"1"===c&&a.a(b,e)});b+=1});return a}v("jsnx.generators.social.karate_club_graph",Td);v("jsnx.karate_club_graph",Td);
function Ud(){var a=new P;a.i("Evelyn Jefferson;Laura Mandeville;Theresa Anderson;Brenda Rogers;Charlotte McDowd;Frances Anderson;Eleanor Nye;Pearl Oglethorpe;Ruth DeSand;Verne Sanderson;Myra Liddel;Katherina Rogers;Sylvia Avondale;Nora Fayette;Helen Lloyd;Dorothy Murchison;Olivia Carleton;Flora Price".split(";"),{Fa:0});a.i("E1 E2 E3 E4 E5 E6 E7 E8 E9 E10 E11 E12 E13 E14".split(" "),{Fa:1});a.d([["Evelyn Jefferson","E1"],["Evelyn Jefferson","E2"],["Evelyn Jefferson","E3"],["Evelyn Jefferson","E4"],
["Evelyn Jefferson","E5"],["Evelyn Jefferson","E6"],["Evelyn Jefferson","E8"],["Evelyn Jefferson","E9"],["Laura Mandeville","E1"],["Laura Mandeville","E2"],["Laura Mandeville","E3"],["Laura Mandeville","E5"],["Laura Mandeville","E6"],["Laura Mandeville","E7"],["Laura Mandeville","E8"],["Theresa Anderson","E2"],["Theresa Anderson","E3"],["Theresa Anderson","E4"],["Theresa Anderson","E5"],["Theresa Anderson","E6"],["Theresa Anderson","E7"],["Theresa Anderson","E8"],["Theresa Anderson","E9"],["Brenda Rogers",
"E1"],["Brenda Rogers","E3"],["Brenda Rogers","E4"],["Brenda Rogers","E5"],["Brenda Rogers","E6"],["Brenda Rogers","E7"],["Brenda Rogers","E8"],["Charlotte McDowd","E3"],["Charlotte McDowd","E4"],["Charlotte McDowd","E5"],["Charlotte McDowd","E7"],["Frances Anderson","E3"],["Frances Anderson","E5"],["Frances Anderson","E6"],["Frances Anderson","E8"],["Eleanor Nye","E5"],["Eleanor Nye","E6"],["Eleanor Nye","E7"],["Eleanor Nye","E8"],["Pearl Oglethorpe","E6"],["Pearl Oglethorpe","E8"],["Pearl Oglethorpe",
"E9"],["Ruth DeSand","E5"],["Ruth DeSand","E7"],["Ruth DeSand","E8"],["Ruth DeSand","E9"],["Verne Sanderson","E7"],["Verne Sanderson","E8"],["Verne Sanderson","E9"],["Verne Sanderson","E12"],["Myra Liddel","E8"],["Myra Liddel","E9"],["Myra Liddel","E10"],["Myra Liddel","E12"],["Katherina Rogers","E8"],["Katherina Rogers","E9"],["Katherina Rogers","E10"],["Katherina Rogers","E12"],["Katherina Rogers","E13"],["Katherina Rogers","E14"],["Sylvia Avondale","E7"],["Sylvia Avondale","E8"],["Sylvia Avondale",
"E9"],["Sylvia Avondale","E10"],["Sylvia Avondale","E12"],["Sylvia Avondale","E13"],["Sylvia Avondale","E14"],["Nora Fayette","E6"],["Nora Fayette","E7"],["Nora Fayette","E9"],["Nora Fayette","E10"],["Nora Fayette","E11"],["Nora Fayette","E12"],["Nora Fayette","E13"],["Nora Fayette","E14"],["Helen Lloyd","E7"],["Helen Lloyd","E8"],["Helen Lloyd","E10"],["Helen Lloyd","E11"],["Helen Lloyd","E12"],["Dorothy Murchison","E8"],["Dorothy Murchison","E9"],["Olivia Carleton","E9"],["Olivia Carleton","E11"],
["Flora Price","E9"],["Flora Price","E11"]]);return a}v("jsnx.generators.social.davis_southern_women_graph",Ud);v("jsnx.davis_southern_women_graph",Ud);
function Vd(){var a=new P;a.a("Acciaiuoli","Medici");a.a("Castellani","Peruzzi");a.a("Castellani","Strozzi");a.a("Castellani","Barbadori");a.a("Medici","Barbadori");a.a("Medici","Ridolfi");a.a("Medici","Tornabuoni");a.a("Medici","Albizzi");a.a("Medici","Salviati");a.a("Salviati","Pazzi");a.a("Peruzzi","Strozzi");a.a("Peruzzi","Bischeri");a.a("Strozzi","Ridolfi");a.a("Strozzi","Bischeri");a.a("Ridolfi","Tornabuoni");a.a("Tornabuoni","Guadagni");a.a("Albizzi","Ginori");a.a("Albizzi","Guadagni");a.a("Bischeri",
"Guadagni");a.a("Guadagni","Lamberteschi");return a}v("jsnx.generators.social.florentine_families_graph",Vd);v("jsnx.florentine_families_graph",Vd);function Wd(a,b){if(null!=b&&b.c())throw new K("Directed Graph not supported");return Xd(a,b)}v("jsnx.generators.small.make_small_undirected_graph",Wd);
function Xd(a,b){var c=a[0],d=a[1],e=a[2],f=Id(e,b),g=f.nodes();if("adjacencylist"==c){var k=a[3];if(k.length!=e)throw new K("invalid graph_description");x(g,function(a){N(k[a],function(b){f.a(b-1,a)})})}else"edgelist"==c&&N(a[3],function(a){var b=a[0]-1;a=a[1]-1;if(0>b||b>e-1||0>a||a>e-1)throw new K("invalid graph_description");f.a(b,a)});f.name=d;return f}v("jsnx.generators.small.make_small_graph",Xd);v("jsnx.make_small_graph",Xd);
function Yd(a){return Wd(["adjacencylist","Bull Graph",5,[[2,3],[1,3,4],[1,2,5],[2],[3]]],a)}v("jsnx.generators.small.bull_graph",Yd);v("jsnx.bull_graph",Yd);function Zd(a){return Wd(["adjacencylist","Krackhardt Kite Social Network",10,[[2,3,4,6],[1,4,5,7],[1,4,6],[1,2,3,5,6,7],[2,4,7],[1,3,4,7,8],[2,4,5,6,8],[6,7,9],[8,10],[9]]],a)}v("jsnx.generators.small.krackhardt_kite_graph",Zd);v("jsnx.krackhardt_kite_graph",Zd);function $d(a,b,c){var d=b;u(d.set)||u(d.get)||(d=new M(d));u(b)&&(d=new M,D(a.B(),function(a){d.set(a,b(a))}));return!m(c)||c?ce(a,d):de(a,d)}v("jsnx.relabel.relabel_nodes",$d);v("jsnx.relabel_nodes",$d);
function de(a,b){var c=new O(b.keys()),d;if(0<c.p(b.values()).count()){c=new Y(b);c.J(c.ba());try{d=Rc(c)}catch(e){if(e instanceof kb)throw new kb("The node label sets are overlapping and no ordering can resolve the mapping. Use copy=True.");}d.reverse()}else d=c;var f=a.m(),g=a.c(),k;D(d,function(c){var d;if(b.has(c)){d=b.get(c);if(!a.n(c))throw new K("Node "+c+" is not in the graph.");a.L(d,a.node.get(c));f?(k=ra(a.u(c,!0,!0),function(a){return[d,a[1],a[2],a[3]]}),g&&(k=za(k,ra(a.W(c,!0,!0),function(a){return[a[0],
d,a[2],a[3]]})))):(k=ra(a.u(c,!0),function(a){return[d,a[1],a[2]]}),g&&(k=za(k,ra(a.W(c,!0),function(a){return[a[0],d,a[2]]}))));a.S(c);a.d(k)}});return a}
function ce(a,b){var c=new a.constructor;c.name("("+a.name()+")");a.m()?c.d(E(a.g(null,!0,!0),function(a){return[b.get(a[0],a[0]),b.get(a[1],a[1]),a[2],bb(a[3])]})):c.d(E(a.g(null,!0),function(a){return[b.get(a[0],a[0]),b.get(a[1],a[1]),bb(a[2])]}));c.i(E(xb(a),function(a){return b.get(a,a)}));var d=new M;a.node.forEach(function(c){d.set(b.get(c,c),bb(a.node.get(c)))});d.forEach(function(a,b){c.node.set(a,b)});J(c.graph,bb(a.graph));return c}
function ee(a,b,c,d){3===arguments.length&&t(c)?(d=c,c=null):2===arguments.length&&(t(b)?(d=b,b=null):r(b)&&(c=b,b=null));null!=b||(b=0);null!=c||(c="default");null!=d||(d=!0);a.Q();var e=new M,f,g,k,p;if("default"===c)for(f=a.nodes(),g=0,k=b,p=f.length;g<p;g++,k++)e.set(f[g],k);else if("sorted"===c)for(f=a.nodes(),f.sort(Ha),g=0,k=b,p=f.length;g<p;g++,k++)e.set(f[g],k);else if("increasing degree"===c)for(f=Na(a.t()),f.sort(function(a,b){return a[1]-b[1]}),g=0,k=b,p=f.length;g<p;g++,k++)e.set(f[g][0],
k);else if("decreasing degree"===c)for(f=Na(a.t()),f.sort(function(a,b){return b[1]-a[1]}),g=0,k=b,p=f.length;g<p;g++,k++)e.set(f[g][0],k);else throw new K("Unkown node ordering: "+c);g=$d(a,e);g.name("("+a.name()+")_with_int_labels");d||(g.node_labels=e);return g}v("jsnx.relabel.convert_node_labels_to_integers",ee);v("jsnx.convert_node_labels_to_integers",ee);}));
